// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// Potentiometer size variants
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum PotentiometerSize {
    /// Extra compact size
    Xs,
    /// Compact size
    Sm,
    /// Default size
    #[default]
    Md,
    /// Large size
    Lg,
}

impl From<crate::ComponentSize> for PotentiometerSize {
    fn from(size: crate::ComponentSize) -> Self {
        match size {
            crate::ComponentSize::Xs => Self::Xs,
            crate::ComponentSize::Sm => Self::Sm,
            crate::ComponentSize::Md => Self::Md,
            crate::ComponentSize::Lg | crate::ComponentSize::Xl => Self::Lg,
        }
    }
}

impl PotentiometerSize {
    pub(super) fn knob_size(&self) -> f32 {
        match self {
            Self::Xs => 30.0,
            Self::Sm => 40.0,
            Self::Md => 60.0,
            Self::Lg => 80.0,
        }
    }

    pub(super) fn indicator_radius(&self) -> f32 {
        match self {
            Self::Xs => 10.0,
            Self::Sm => 14.0,
            Self::Md => 20.0,
            Self::Lg => 26.0,
        }
    }

    pub(super) fn min_width(&self) -> f32 {
        match self {
            Self::Xs => 120.0,
            Self::Sm => 130.0,
            Self::Md => 150.0,
            Self::Lg => 170.0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::PotentiometerSize;
    use crate::ComponentSize;

    #[test]
    fn default_size_is_medium() {
        assert_eq!(PotentiometerSize::default(), PotentiometerSize::Md);
    }

    #[test]
    fn sizes_increase_monotonically() {
        let sizes = [
            PotentiometerSize::Xs,
            PotentiometerSize::Sm,
            PotentiometerSize::Md,
            PotentiometerSize::Lg,
        ];
        for window in sizes.windows(2) {
            assert!(window[0].knob_size() < window[1].knob_size());
            assert!(window[0].indicator_radius() < window[1].indicator_radius());
            assert!(window[0].min_width() < window[1].min_width());
        }
    }

    #[test]
    fn component_size_maps_to_potentiometer_size() {
        assert_eq!(PotentiometerSize::from(ComponentSize::Xs), PotentiometerSize::Xs);
        assert_eq!(PotentiometerSize::from(ComponentSize::Sm), PotentiometerSize::Sm);
        assert_eq!(PotentiometerSize::from(ComponentSize::Md), PotentiometerSize::Md);
        assert_eq!(PotentiometerSize::from(ComponentSize::Lg), PotentiometerSize::Lg);
        assert_eq!(PotentiometerSize::from(ComponentSize::Xl), PotentiometerSize::Lg);
    }
}
