// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::paint::paint_qr_full_from_colors;
use crate::theme::ThemeExt;
use gpui::prelude::{IntoElement, RenderOnce, Styled};
use gpui::{App, Pixels, Rgba, Window, canvas, px};
use qrcode::QrCode as QrMatrix;

/// A QR code display component.
///
/// Encodes a string at Medium error-correction level and renders each dark
/// module as a filled rectangle scaled to the requested pixel size.
///
/// # Example
///
/// ```ignore
/// QrCode::new("https://example.com")
///     .size(px(200.0))
/// ```
pub struct QrCode {
    /// Pre-computed module colors (empty on encode failure).
    pub(super) colors: Vec<qrcode::types::Color>,
    /// Number of modules on one side of the QR.
    pub(super) modules: usize,
    /// Rendered size in pixels (width and height; the code is always square).
    pub(super) size: Pixels,
    /// Foreground (dark module) color. Defaults to theme's `text_primary`.
    pub(super) fg: Option<Rgba>,
    /// Background color. Defaults to transparent.
    pub(super) bg: Option<Rgba>,
}

impl QrCode {
    /// Create a new QR code component that encodes `data`.
    pub fn new(data: impl AsRef<[u8]>) -> Self {
        let matrix = QrMatrix::new(data.as_ref()).ok();
        let colors = matrix.as_ref().map(|m| m.to_colors()).unwrap_or_default();
        let modules = matrix.as_ref().map_or(0, |m| m.width());
        Self {
            colors,
            modules,
            size: px(200.0),
            fg: None,
            bg: None,
        }
    }

    /// Set the rendered size (both width and height) in pixels.
    pub fn size(mut self, size: Pixels) -> Self {
        self.size = size;
        self
    }

    /// Override the foreground (dark module) color.
    pub fn fg(mut self, color: Rgba) -> Self {
        self.fg = Some(color);
        self
    }

    /// Override the background color.
    pub fn bg(mut self, color: Rgba) -> Self {
        self.bg = Some(color);
        self
    }

    /// Build the canvas element with explicit colors.
    pub(super) fn build(self, fg_color: Rgba, bg_color: Rgba) -> impl IntoElement {
        let requested_size = self.size;
        let size_f32: f32 = requested_size.into();
        let colors = self.colors;
        let modules = self.modules;

        canvas(
            move |_bounds, _window, _cx| (colors, modules),
            move |bounds, (colors, modules), window, _cx| {
                paint_qr_full_from_colors(bounds, &colors, modules, size_f32, fg_color, bg_color, window);
            },
        )
        .w(requested_size)
        .h(requested_size)
    }
}

impl RenderOnce for QrCode {
    fn render(self, _window: &mut Window, cx: &mut App) -> impl IntoElement {
        let theme = cx.theme();
        let fg_color = self.fg.unwrap_or(theme.text_primary);
        let bg_color = self.bg.unwrap_or(theme.transparent);
        self.build(fg_color, bg_color)
    }
}

impl IntoElement for QrCode {
    type Element = gpui::Component<Self>;

    fn into_element(self) -> Self::Element {
        gpui::Component::new(self)
    }
}
