// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::EPSILON;
use super::Projection;
use super::albers::Albers;
use super::conic_equal_area::ConicEqualArea;
use super::equirectangular::Equirectangular;
use super::mercator::Mercator;
use super::orthographic::Orthographic;
use super::stereographic::Stereographic;
use super::transverse_mercator::TransverseMercator;

#[test]
fn test_mercator_project_origin() {
    let proj = Mercator::new().scale(100.0).translate(0.0, 0.0);
    let (x, y) = proj.project(0.0, 0.0);
    assert!(x.abs() < EPSILON);
    assert!(y.abs() < EPSILON);
}

#[test]
fn test_mercator_invert() {
    let proj = Mercator::new().scale(100.0).translate(200.0, 200.0);
    let (x, y) = proj.project(45.0, 30.0);
    let (lon, lat) = proj.invert(x, y).unwrap();
    assert!((lon - 45.0).abs() < 1e-6);
    assert!((lat - 30.0).abs() < 1e-6);
}

#[test]
fn test_equirectangular_project() {
    let proj = Equirectangular::new().scale(100.0).translate(0.0, 0.0);
    let (x, y) = proj.project(0.0, 0.0);
    assert!(x.abs() < EPSILON);
    assert!(y.abs() < EPSILON);
}

#[test]
fn test_equirectangular_invert() {
    let proj = Equirectangular::new().scale(100.0).translate(200.0, 200.0);
    let (x, y) = proj.project(45.0, 30.0);
    let (lon, lat) = proj.invert(x, y).unwrap();
    assert!((lon - 45.0).abs() < 1e-6);
    assert!((lat - 30.0).abs() < 1e-6);
}

#[test]
fn test_orthographic_project() {
    let proj = Orthographic::new().scale(100.0).translate(0.0, 0.0);
    let (x, y) = proj.project(0.0, 0.0);
    assert!(x.abs() < EPSILON);
    assert!(y.abs() < EPSILON);
}

#[test]
fn test_orthographic_invert() {
    let proj = Orthographic::new().scale(100.0).translate(200.0, 200.0);
    let (x, y) = proj.project(30.0, 20.0);
    if let Some((lon, lat)) = proj.invert(x, y) {
        assert!((lon - 30.0).abs() < 1e-6);
        assert!((lat - 20.0).abs() < 1e-6);
    }
}

#[test]
fn test_stereographic_project() {
    let proj = Stereographic::new().scale(100.0).translate(0.0, 0.0);
    let (x, y) = proj.project(0.0, 0.0);
    assert!(x.abs() < EPSILON);
    assert!(y.abs() < EPSILON);
}

#[test]
fn test_stereographic_invert() {
    // Test with centered projection (no rotation offset) for simpler math
    let proj = Stereographic::new().scale(100.0).translate(200.0, 200.0);
    // Project and invert at origin (simpler case)
    let (x0, y0) = proj.project(0.0, 0.0);
    let (lon0, lat0) = proj.invert(x0, y0).unwrap();
    assert!(lon0.abs() < 1.0, "Origin lon should be near 0: {}", lon0);
    assert!(lat0.abs() < 1.0, "Origin lat should be near 0: {}", lat0);
}

#[test]
fn test_transverse_mercator_project() {
    let proj = TransverseMercator::new().scale(100.0).translate(0.0, 0.0);
    let (x, y) = proj.project(0.0, 0.0);
    // At origin, transverse mercator gives (0, 0)
    assert!(x.abs() < 1e-3);
    assert!(y.abs() < EPSILON);
}

#[test]
fn test_conic_equal_area_project() {
    let proj = ConicEqualArea::new().scale(100.0).translate(0.0, 0.0);
    let (x, _y) = proj.project(0.0, 33.6442); // At center
    assert!(x.abs() < EPSILON);
    // y should be near 0 at center latitude
}

#[test]
fn test_albers_project() {
    let proj = Albers::new();
    // Project a point in the continental US (Kansas City area)
    let (x, y) = proj.project(-98.0, 39.0);
    // Should produce valid coordinates - the exact values depend on the projection parameters
    assert!(x.is_finite());
    assert!(y.is_finite());
    // Should be in reasonable screen coordinates (positive, given the translate offset)
    assert!(x > 0.0);
}

#[test]
fn test_projection_config_default() {
    let config = super::projection_config::ProjectionConfig::default();
    assert_eq!(config.scale, 150.0);
    assert_eq!(config.translate, (480.0, 250.0));
    assert_eq!(config.center, (0.0, 0.0));
    assert_eq!(config.rotate, (0.0, 0.0, 0.0));
    assert!(config.clip_angle.is_none());
}

#[test]
fn test_projection_config_rotation_helpers() {
    use super::projection_config::{apply_rotation, build_rotation, invert_rotation};

    let config = super::projection_config::ProjectionConfig {
        rotate: (90.0, 0.0, 0.0),
        ..Default::default()
    };
    let _rotation = build_rotation(&config);
    let (lambda, phi) = apply_rotation(&config, 0.0, 0.0);
    assert!((lambda - std::f64::consts::FRAC_PI_2).abs() < 1e-10);
    assert!(phi.abs() < 1e-10);

    let (lon, lat) = invert_rotation(&config, lambda, phi);
    assert!((lon - 0.0).abs() < 1e-6);
    assert!((lat - 0.0).abs() < 1e-6);
}

#[test]
fn test_clip_angle_visible() {
    use super::projection_config::clip_angle_visible;

    let config_no_clip = super::projection_config::ProjectionConfig::default();
    assert!(clip_angle_visible(&config_no_clip, 0.0, 0.0));

    let config_clip = super::projection_config::ProjectionConfig {
        clip_angle: Some(90.0),
        ..Default::default()
    };
    assert!(clip_angle_visible(&config_clip, 0.0, 0.0));
    assert!(!clip_angle_visible(&config_clip, 0.0, 91.0));
}

#[test]
fn test_albers_setters() {
    let proj = Albers::new()
        .scale(500.0)
        .translate(100.0, 200.0)
        .center(10.0, 20.0)
        .rotate(5.0, 0.0, 0.0);

    assert_eq!(Projection::scale(&proj), 500.0);
    assert_eq!(Projection::translate(&proj), (100.0, 200.0));
    assert_eq!(Projection::center(&proj), (10.0, 20.0));
    assert_eq!(Projection::rotate(&proj), (5.0, 0.0, 0.0));
}

#[test]
fn test_albers_mutating_setters() {
    let mut proj = Albers::new();
    proj.set_scale(500.0);
    proj.set_translate(100.0, 200.0);
    proj.set_center(10.0, 20.0);
    proj.set_rotate(5.0, 0.0, 0.0);

    assert_eq!(Projection::scale(&proj), 500.0);
    assert_eq!(Projection::translate(&proj), (100.0, 200.0));
    assert_eq!(Projection::center(&proj), (10.0, 20.0));
    assert_eq!(Projection::rotate(&proj), (5.0, 0.0, 0.0));
}

#[test]
fn test_transverse_mercator_project_invert() {
    use super::transverse_mercator::TransverseMercator;

    let proj = TransverseMercator::new().scale(100.0).translate(200.0, 200.0);
    let (x, y) = proj.project(0.0, 0.0);
    let (lon, lat) = proj.invert(x, y).unwrap();
    assert!((lon - 0.0).abs() < 1e-6);
    assert!((lat - 0.0).abs() < 1e-6);
}

#[test]
fn test_transverse_mercator_raw_functions() {
    use super::transverse_mercator::TransverseMercator;

    let (x, y) = TransverseMercator::project_raw(0.0, 0.0);
    assert!(x.is_finite());
    assert!(y.is_finite());

    let (lambda, phi) = TransverseMercator::invert_raw(x, y);
    assert!((lambda - 0.0).abs() < 1e-10);
    assert!((phi - 0.0).abs() < 1e-10);
}

#[test]
fn test_transverse_mercator_longitude_unwrap_center() {
    use super::transverse_mercator::TransverseMercator;
    use super::Projection;

    let proj = TransverseMercator::new().rotate(10.0, 0.0, 0.0).center(5.0, 0.0);
    assert_eq!(proj.longitude_unwrap_center(), Some(15.0));
}

#[test]
fn test_sphere_rotation_identity() {
    use super::sphere_rotation::SphereRotation;

    let identity = SphereRotation::identity();
    let (lon, lat) = identity.rotate(0.0, 0.0);
    assert!((lon - 0.0).abs() < 1e-10);
    assert!((lat - 0.0).abs() < 1e-10);
}

#[test]
fn test_sphere_rotation_from_radians_roundtrip() {
    use super::sphere_rotation::SphereRotation;

    let rotation = SphereRotation::from_radians(0.5, 0.3, 0.1);
    let original = (10.0f64.to_radians(), 20.0f64.to_radians());
    let rotated = rotation.rotate(original.0, original.1);
    let inverted = rotation.invert(rotated.0, rotated.1);
    assert!((inverted.0 - original.0).abs() < 1e-9);
    assert!((inverted.1 - original.1).abs() < 1e-9);
}
