// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::types::Easing;

/// Keyframe for multi-step animations
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Keyframe<T> {
    /// Progress point (0.0 to 1.0)
    pub at: f32,
    /// Value at this keyframe
    pub value: T,
    /// Easing to use when interpolating TO this keyframe
    pub easing: Easing,
}

impl<T> Keyframe<T> {
    /// Create a new keyframe
    pub fn new(at: f32, value: T) -> Self {
        Self {
            at: at.clamp(0.0, 1.0),
            value,
            easing: Easing::Linear,
        }
    }

    /// Set the easing function for interpolation to this keyframe
    pub fn with_easing(mut self, easing: Easing) -> Self {
        self.easing = easing;
        self
    }
}


#[cfg(test)]
mod tests {
    use super::{Easing, Keyframe};

    #[test]
    fn keyframe_clamps_progress_and_easing() {
        let k = Keyframe::new(-0.5, 10.0).with_easing(Easing::EaseOutQuad);
        assert_eq!(k.at, 0.0);
        assert_eq!(k.value, 10.0);
        assert_eq!(k.easing, Easing::EaseOutQuad);

        let k = Keyframe::new(1.5, 20.0);
        assert_eq!(k.at, 1.0);
        assert_eq!(k.easing, Easing::Linear);
    }
}

