// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::borrow::Cow;
use std::fmt::Write;

use super::super::projection::Projection;
use super::geo_path_config::GeoPathConfig;
use super::types::GeoJsonGeometry;

/// A path generator for GeoJSON geometries.
///
/// GeoPath projects geographic coordinates using a projection and generates
/// SVG path data or other path representations.
#[derive(Clone)]
pub struct GeoPath<P: Projection> {
    pub(super) projection: P,
    pub(super) config: GeoPathConfig,
}

impl<P: Projection> GeoPath<P> {
    /// Create a new GeoPath with the given projection.
    pub fn new(projection: P) -> Self {
        Self {
            projection,
            config: GeoPathConfig::default(),
        }
    }

    /// Set the number of decimal places for path coordinates.
    pub fn digits(mut self, digits: usize) -> Self {
        self.config.digits = digits;
        self
    }

    /// Set the point radius for point features.
    pub fn point_radius(mut self, radius: f64) -> Self {
        self.config.point_radius = radius;
        self
    }

    /// Get a reference to the projection.
    pub fn projection(&self) -> &P {
        &self.projection
    }

    /// Get a mutable reference to the projection.
    pub fn projection_mut(&mut self) -> &mut P {
        &mut self.projection
    }

    /// Render a GeoJSON geometry to an SVG path string.
    pub fn render(&self, geometry: &GeoJsonGeometry) -> String {
        match geometry {
            GeoJsonGeometry::Point(lon, lat) => self.render_point(*lon, *lat),
            GeoJsonGeometry::MultiPoint(points) => self.render_multi_point(points),
            GeoJsonGeometry::LineString(coords) => self.render_line_string(coords),
            GeoJsonGeometry::MultiLineString(lines) => self.render_multi_line_string(lines),
            GeoJsonGeometry::Polygon(rings) => self.render_polygon(rings),
            GeoJsonGeometry::MultiPolygon(polygons) => self.render_multi_polygon(polygons),
        }
    }

    /// Render a point as a circle.
    pub(super) fn render_point(&self, lon: f64, lat: f64) -> String {
        if !self.projection.is_visible(lon, lat) {
            return String::new();
        }
        let (x, y) = self.projection.project(lon, lat);
        let r = self.config.point_radius;
        let d = self.config.digits;

        // Create a circle path
        let mut s = String::with_capacity(80);
        write!(
            &mut s,
            "M{:.d$},{:.d$}m0,{:.d$}a{:.d$},{:.d$} 0 1,1 0,-{:.d$}a{:.d$},{:.d$} 0 1,1 0,{:.d$}z",
            x, y, r, r, r, 2.0 * r, r, r, 2.0 * r, d = d
        )
        .unwrap();
        s
    }

    /// Render multiple points.
    pub(super) fn render_multi_point(&self, points: &[(f64, f64)]) -> String {
        let mut path = String::with_capacity(points.len() * 80);
        for &(lon, lat) in points {
            path.push_str(&self.render_point(lon, lat));
        }
        path
    }

    /// Render a line string.
    pub(super) fn render_line_string(&self, coords: &[(f64, f64)]) -> String {
        if coords.is_empty() {
            return String::new();
        }

        let d = self.config.digits;
        let mut path = String::with_capacity(coords.len() * 24);
        let mut prev_lon: Option<f64> = None;
        let mut need_move = true;

        for &(lon, lat) in coords.iter() {
            // Pre-clip: skip points outside the projection's clip angle
            if !self.projection.is_visible(lon, lat) {
                prev_lon = None;
                need_move = true;
                continue;
            }

            let (x, y) = self.projection.project(lon, lat);

            // Check if coordinates are valid
            if !x.is_finite() || !y.is_finite() {
                prev_lon = None;
                need_move = true;
                continue;
            }

            // Detect antimeridian crossing: if longitude jumps > 180 degrees
            let crosses_antimeridian = if let Some(prev) = prev_lon {
                (lon - prev).abs() > 180.0
            } else {
                false
            };

            if need_move || crosses_antimeridian {
                write!(&mut path, "M{:.d$},{:.d$}", x, y, d = d).unwrap();
                need_move = false;
            } else {
                write!(&mut path, "L{:.d$},{:.d$}", x, y, d = d).unwrap();
            }

            prev_lon = Some(lon);
        }

        path
    }

    /// Render multiple line strings.
    pub(super) fn render_multi_line_string(&self, lines: &[Vec<(f64, f64)>]) -> String {
        let mut path = String::new();
        for line in lines {
            path.push_str(&self.render_line_string(line));
        }
        path
    }

    /// Render a polygon.
    pub(super) fn render_polygon(&self, rings: &[Vec<(f64, f64)>]) -> String {
        if rings.is_empty() {
            return String::new();
        }

        let d = self.config.digits;
        let mut path = String::with_capacity(rings.iter().map(|r| r.len()).sum::<usize>() * 24);

        for ring in rings {
            if ring.is_empty() {
                continue;
            }

            let mut prev_lon: Option<f64> = None;
            let mut ring_started = false;

            for &(lon, lat) in ring.iter() {
                // Pre-clip: skip points outside the projection's clip angle
                if !self.projection.is_visible(lon, lat) {
                    prev_lon = None;
                    if ring_started {
                        path.push('Z');
                        ring_started = false;
                    }
                    continue;
                }

                let (x, y) = self.projection.project(lon, lat);

                // Check if coordinates are valid
                if !x.is_finite() || !y.is_finite() {
                    prev_lon = None;
                    if ring_started {
                        path.push('Z');
                        ring_started = false;
                    }
                    continue;
                }

                // Detect antimeridian crossing: if longitude jumps > 180 degrees
                let crosses_antimeridian = if let Some(prev) = prev_lon {
                    (lon - prev).abs() > 180.0
                } else {
                    false
                };

                if !ring_started || crosses_antimeridian {
                    // Close previous segment if we're breaking due to antimeridian
                    if ring_started && crosses_antimeridian {
                        path.push('Z');
                    }
                    write!(&mut path, "M{:.d$},{:.d$}", x, y, d = d).unwrap();
                    ring_started = true;
                } else {
                    write!(&mut path, "L{:.d$},{:.d$}", x, y, d = d).unwrap();
                }

                prev_lon = Some(lon);
            }

            // Close the ring
            if ring_started {
                path.push('Z');
            }
        }

        path
    }

    /// Render multiple polygons.
    pub(super) fn render_multi_polygon(&self, polygons: &[Vec<Vec<(f64, f64)>>]) -> String {
        let mut path = String::new();
        for polygon in polygons {
            path.push_str(&self.render_polygon(polygon));
        }
        path
    }

    /// Render coordinates to a vector of projected (x, y) points.
    pub fn project_coords(&self, coords: &[(f64, f64)]) -> Vec<(f64, f64)> {
        coords
            .iter()
            .map(|&(lon, lat)| self.projection.project(lon, lat))
            .collect()
    }

    /// Calculate the bounds of a geometry after projection.
    ///
    /// Returns `((min_x, min_y), (max_x, max_y))`
    pub fn bounds(&self, geometry: &GeoJsonGeometry) -> ((f64, f64), (f64, f64)) {
        let coords = self.geometry_coordinates(geometry);
        if coords.is_empty() {
            return ((f64::NAN, f64::NAN), (f64::NAN, f64::NAN));
        }

        let mut min_x = f64::MAX;
        let mut max_x = f64::MIN;
        let mut min_y = f64::MAX;
        let mut max_y = f64::MIN;

        for &(lon, lat) in coords.iter() {
            let (x, y) = self.projection.project(lon, lat);
            if x < min_x {
                min_x = x;
            }
            if x > max_x {
                max_x = x;
            }
            if y < min_y {
                min_y = y;
            }
            if y > max_y {
                max_y = y;
            }
        }

        ((min_x, min_y), (max_x, max_y))
    }

    /// Calculate the centroid of a geometry after projection.
    pub fn centroid(&self, geometry: &GeoJsonGeometry) -> (f64, f64) {
        let coords = self.geometry_coordinates(geometry);
        if coords.is_empty() {
            return (f64::NAN, f64::NAN);
        }

        let mut sum_x = 0.0;
        let mut sum_y = 0.0;
        let n = coords.len() as f64;

        for &(lon, lat) in coords.iter() {
            let (x, y) = self.projection.project(lon, lat);
            sum_x += x;
            sum_y += y;
        }

        (sum_x / n, sum_y / n)
    }

    /// Extract all coordinates from a geometry.
    pub(super) fn geometry_coordinates<'a>(
        &self,
        geometry: &'a GeoJsonGeometry,
    ) -> Cow<'a, [(f64, f64)]> {
        match geometry {
            GeoJsonGeometry::Point(lon, lat) => Cow::Owned(vec![(*lon, *lat)]),
            GeoJsonGeometry::MultiPoint(points) => Cow::Borrowed(points),
            GeoJsonGeometry::LineString(coords) => Cow::Borrowed(coords),
            GeoJsonGeometry::MultiLineString(lines) => {
                Cow::Owned(lines.iter().flatten().copied().collect())
            }
            GeoJsonGeometry::Polygon(rings) => {
                Cow::Owned(rings.iter().flatten().copied().collect())
            }
            GeoJsonGeometry::MultiPolygon(polygons) => Cow::Owned(
                polygons
                    .iter()
                    .flatten()
                    .flatten()
                    .copied()
                    .collect(),
            ),
        }
    }
}
