// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::geo_path::GeoPath;
use super::types::GeoJsonGeometry;

use crate::geo::projection::{Equirectangular, Mercator};

#[test]
fn test_geo_path_point() {
    let proj = Equirectangular::new().scale(100.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::Point(0.0, 0.0);
    let svg = path.render(&geometry);
    assert!(svg.starts_with('M'));
    assert!(svg.contains('a')); // arc commands for circle
}

#[test]
fn test_geo_path_line_string() {
    let proj = Equirectangular::new().scale(100.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::LineString(vec![(0.0, 0.0), (10.0, 10.0), (20.0, 0.0)]);
    let svg = path.render(&geometry);
    assert!(svg.starts_with('M'));
    assert!(svg.contains('L'));
}

#[test]
fn test_geo_path_polygon() {
    let proj = Equirectangular::new().scale(100.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::Polygon(vec![vec![
        (0.0, 0.0),
        (10.0, 0.0),
        (10.0, 10.0),
        (0.0, 10.0),
        (0.0, 0.0),
    ]]);
    let svg = path.render(&geometry);
    assert!(svg.starts_with('M'));
    assert!(svg.ends_with('Z'));
}

#[test]
fn test_geo_path_bounds() {
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::LineString(vec![(0.0, 0.0), (90.0, 45.0)]);
    let ((min_x, min_y), (max_x, max_y)) = path.bounds(&geometry);

    assert!(min_x < max_x);
    assert!(min_y < max_y);
}

#[test]
fn test_geo_path_centroid() {
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::LineString(vec![(0.0, 0.0), (10.0, 0.0)]);
    let (cx, cy) = path.centroid(&geometry);

    // Centroid of a line from 0 to 10 should be at 5
    assert!((cx - 5.0 * std::f64::consts::PI / 180.0).abs() < 1e-6);
    assert!(cy.abs() < 1e-6);
}

#[test]
fn test_render_into_matches_render() {
    let proj = Equirectangular::new().scale(100.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometries = [
        GeoJsonGeometry::Point(0.0, 0.0),
        GeoJsonGeometry::LineString(vec![(0.0, 0.0), (10.0, 10.0), (20.0, 0.0)]),
        GeoJsonGeometry::Polygon(vec![vec![
            (0.0, 0.0),
            (10.0, 0.0),
            (10.0, 10.0),
            (0.0, 10.0),
            (0.0, 0.0),
        ]]),
    ];

    for geometry in &geometries {
        let expected = path.render(geometry);
        let mut buf = String::new();
        path.render_into(geometry, &mut buf);
        assert_eq!(
            buf, expected,
            "render_into should match render for {geometry:?}"
        );
    }
}

#[test]
fn test_render_cow_matches_render_and_borrows_empty() {
    use std::borrow::Cow;

    let proj = Equirectangular::new().scale(100.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometries = [
        GeoJsonGeometry::Point(0.0, 0.0),
        GeoJsonGeometry::LineString(vec![(0.0, 0.0), (10.0, 10.0), (20.0, 0.0)]),
        GeoJsonGeometry::MultiLineString(vec![]),
    ];

    for geometry in &geometries {
        let expected = path.render(geometry);
        let cow = path.render_cow(geometry);
        assert_eq!(
            cow.as_ref(),
            expected.as_str(),
            "render_cow should match render for {geometry:?}"
        );
        if expected.is_empty() {
            assert!(
                matches!(cow, Cow::Borrowed(_)),
                "empty geometry should borrow"
            );
        } else {
            assert!(
                matches!(cow, Cow::Owned(_)),
                "non-empty geometry should own"
            );
        }
    }
}

#[test]
fn test_geo_path_project_coords() {
    let proj = Equirectangular::new().scale(100.0).translate(500.0, 300.0);
    let path = GeoPath::new(proj);

    let coords = vec![(0.0, 0.0), (90.0, 0.0)];
    let projected = path.project_coords(&coords);

    assert_eq!(projected.len(), 2);
    // Origin should project to translate point
    assert!((projected[0].0 - 500.0).abs() < 1e-6);
    assert!((projected[0].1 - 300.0).abs() < 1e-6);
}

#[test]
fn test_antimeridian_line_string_crossing() {
    // Line crossing from Russia (170°E) to Alaska (-170°W)
    // This should create two separate path segments
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::LineString(vec![
        (170.0, 60.0),  // Eastern Russia
        (-170.0, 60.0), // Alaska
    ]);
    let svg = path.render(&geometry);

    // Should have two M commands (one for start, one after crossing)
    let m_count = svg.matches('M').count();
    assert_eq!(
        m_count, 2,
        "Should have 2 move commands for antimeridian crossing"
    );

    // Each clipped piece has two endpoints, so there is one L command per
    // piece. No L connects the two sides across the antimeridian.
    let l_count = svg.matches('L').count();
    assert_eq!(l_count, 2, "Should have one line command per clipped piece");
}

#[test]
fn test_antimeridian_line_string_no_crossing() {
    // Line NOT crossing antimeridian (normal case)
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::LineString(vec![(10.0, 60.0), (20.0, 60.0), (30.0, 60.0)]);
    let svg = path.render(&geometry);

    // Should have only 1 M command at start
    let m_count = svg.matches('M').count();
    assert_eq!(m_count, 1, "Should have 1 move command for normal line");

    // Should have L commands connecting points
    let l_count = svg.matches('L').count();
    assert_eq!(l_count, 2, "Should have 2 line commands for 3-point line");
}

#[test]
fn test_antimeridian_polygon_crossing() {
    // Polygon crossing antimeridian (like part of Russia)
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::Polygon(vec![vec![
        (170.0, 65.0),
        (175.0, 60.0),
        (-175.0, 60.0), // Crosses antimeridian here
        (-170.0, 65.0),
        (170.0, 65.0), // Close the ring
    ]]);
    let svg = path.render(&geometry);

    // The antimeridian clip cuts the ring into pieces and then rejoins them
    // along the antimeridian edge, so the result is a single closed path.
    let m_count = svg.matches('M').count();
    assert_eq!(
        m_count, 1,
        "Should have 1 rejoined move command for crossing polygon"
    );

    // Should have one close command for the rejoined ring.
    let z_count = svg.matches('Z').count();
    assert_eq!(
        z_count, 1,
        "Should have 1 close command for crossing polygon"
    );
}

#[test]
fn test_antimeridian_polygon_no_crossing() {
    // Normal polygon not crossing antimeridian.
    // D3's spherical polygon convention requires exterior rings smaller than
    // a hemisphere to be clockwise, so this ring is ordered clockwise.
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::Polygon(vec![vec![
        (10.0, 50.0),
        (10.0, 60.0),
        (20.0, 60.0),
        (20.0, 50.0),
        (10.0, 50.0),
    ]]);
    let svg = path.render(&geometry);

    // Should have only 1 M command
    let m_count = svg.matches('M').count();
    assert_eq!(m_count, 1, "Should have 1 move command for normal polygon");

    // Should have exactly 1 Z command (closed ring)
    let z_count = svg.matches('Z').count();
    assert_eq!(z_count, 1, "Should have 1 close command for normal polygon");
}

#[test]
fn test_antimeridian_multipolygon_with_crossing() {
    // MultiPolygon with one polygon crossing antimeridian
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::MultiPolygon(vec![
        // First polygon: normal (Europe)
        vec![vec![
            (0.0, 50.0),
            (10.0, 50.0),
            (10.0, 55.0),
            (0.0, 55.0),
            (0.0, 50.0),
        ]],
        // Second polygon: crosses antimeridian (Russia/Alaska)
        vec![vec![
            (170.0, 60.0),
            (175.0, 60.0),
            (-175.0, 60.0), // Crossing
            (-170.0, 60.0),
            (170.0, 60.0),
        ]],
    ]);
    let svg = path.render(&geometry);

    // Should have M commands for both polygons plus breaks
    let m_count = svg.matches('M').count();
    assert!(
        m_count >= 3,
        "Should have at least 3 move commands (2 polygons + crossing)"
    );

    // Should have multiple Z commands
    let z_count = svg.matches('Z').count();
    assert!(z_count >= 3, "Should have at least 3 close commands");
}

#[test]
fn test_invalid_coordinates_handling() {
    // Test that infinite/NaN coordinates are handled gracefully
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    // LineString with valid and invalid coordinates
    let geometry = GeoJsonGeometry::LineString(vec![
        (0.0, 0.0),
        (10.0, 10.0),
        (f64::NAN, f64::NAN), // Invalid
        (20.0, 20.0),
        (30.0, 30.0),
    ]);
    let svg = path.render(&geometry);

    // Should successfully render (not panic)
    assert!(!svg.is_empty(), "Should render despite invalid coordinates");

    // Should have M commands before and after invalid point
    let m_count = svg.matches('M').count();
    assert!(m_count >= 1, "Should have at least 1 move command");
}

#[test]
fn test_antimeridian_with_orthographic_projection() {
    // Test antimeridian handling with non-Equirectangular projection.
    // Use points on the visible hemisphere (within 90° of center at 0°,0°).
    use crate::geo::projection::Orthographic;

    let proj = Orthographic::new().scale(100.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    // Points at ±45° longitude are on the visible hemisphere
    let geometry = GeoJsonGeometry::LineString(vec![(45.0, 0.0), (-45.0, 0.0)]);
    let svg = path.render(&geometry);

    let m_count = svg.matches('M').count();
    assert!(
        m_count >= 1,
        "Should render visible-hemisphere line with Orthographic projection"
    );
}

#[test]
fn test_antimeridian_multiple_crossings() {
    // Line with multiple antimeridian crossings
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    let geometry = GeoJsonGeometry::LineString(vec![
        (170.0, 0.0),
        (-170.0, 0.0), // First crossing
        (-160.0, 0.0),
        (160.0, 0.0), // Second crossing (going back)
    ]);
    let svg = path.render(&geometry);

    // Should have multiple M commands for multiple crossings
    let m_count = svg.matches('M').count();
    assert!(
        m_count >= 3,
        "Should have at least 3 move commands for 2 crossings"
    );
}

#[test]
fn test_antimeridian_edge_cases() {
    let proj = Equirectangular::new().scale(1.0).translate(0.0, 0.0);
    let path = GeoPath::new(proj);

    // Test exactly at +180
    let geometry1 = GeoJsonGeometry::LineString(vec![(179.0, 0.0), (180.0, 0.0), (-179.0, 0.0)]);
    let svg1 = path.render(&geometry1);
    assert!(!svg1.is_empty(), "Should handle +180 boundary");

    // Test exactly at -180
    let geometry2 = GeoJsonGeometry::LineString(vec![(-179.0, 0.0), (-180.0, 0.0), (179.0, 0.0)]);
    let svg2 = path.render(&geometry2);
    assert!(!svg2.is_empty(), "Should handle -180 boundary");
}

#[test]
fn test_mercator_pole_clip() {
    let proj = Mercator::new().scale(100.0).translate(300.0, 200.0);
    let path = GeoPath::new(proj).digits(2);

    // A polygon that touches the south pole and spans the antimeridian.
    // This is a simplified Antarctica-like shape.
    let geometry = GeoJsonGeometry::Polygon(vec![vec![
        (-180.0, -90.0),
        (180.0, -90.0),
        (180.0, -60.0),
        (90.0, -65.0),
        (0.0, -70.0),
        (-90.0, -65.0),
        (-180.0, -60.0),
        (-180.0, -90.0),
    ]]);
    let svg = path.render(&geometry);
    eprintln!("Mercator pole clip SVG: {}", svg);
    assert!(svg.starts_with('M'));
    assert!(svg.ends_with('Z'));

    // Regression: without clipping, the polar points produced a degenerate
    // horizontal closing chord that filled the whole map as a green streak.
    // After clipping the ring to the projection's valid extent, the polygon
    // must span a real vertical range.
    let ys: Vec<f64> = svg
        .split(['M', 'L', 'Z'])
        .filter_map(|token| {
            let (_, y) = token.split_once(',')?;
            y.parse().ok()
        })
        .collect();
    assert!(
        ys.len() >= 4,
        "clipped polygon should have several vertices"
    );
    let span = ys.iter().copied().fold(f64::NEG_INFINITY, f64::max)
        - ys.iter().copied().fold(f64::INFINITY, f64::min);
    assert!(
        span > 10.0,
        "clipped Antarctica should span vertically; got span={span}, ys={ys:?}"
    );
}
