// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::percentile;

/// Statistics for a single box in a box plot
#[derive(Debug, Clone)]
pub struct BoxStats {
    /// X position (bin center)
    pub x: f64,
    /// First quartile (25th percentile)
    pub q1: f64,
    /// Median (50th percentile)
    pub q2: f64,
    /// Third quartile (75th percentile)
    pub q3: f64,
    /// Lower whisker extent
    pub whisker_low: f64,
    /// Upper whisker extent
    pub whisker_high: f64,
    /// Outliers below the lower whisker
    pub outliers_low: Vec<f64>,
    /// Outliers above the upper whisker
    pub outliers_high: Vec<f64>,
}

impl BoxStats {
    /// Calculate box statistics from a sorted slice of values.
    pub(super) fn from_values(x: f64, values: &[f64]) -> Option<Self> {
        if values.is_empty() {
            return None;
        }

        // Calculate quartiles using linear interpolation on the sorted slice.
        let q1 = percentile(values, 0.25);
        let q2 = percentile(values, 0.50);
        let q3 = percentile(values, 0.75);

        let iqr = q3 - q1;
        let whisker_low_limit = q1 - 1.5 * iqr;
        let whisker_high_limit = q3 + 1.5 * iqr;

        // Find actual whisker positions (closest data points within limits)
        // by scanning the unsorted values once.
        let mut whisker_low = f64::INFINITY;
        let mut whisker_high = f64::NEG_INFINITY;
        for &v in values {
            if v >= whisker_low_limit && v < whisker_low {
                whisker_low = v;
            }
            if v <= whisker_high_limit && v > whisker_high {
                whisker_high = v;
            }
        }
        if whisker_low.is_infinite() {
            whisker_low = values.iter().copied().fold(f64::INFINITY, f64::min);
        }
        if whisker_high.is_infinite() {
            whisker_high = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        }

        // Collect outliers
        let outliers_low: Vec<f64> = values
            .iter()
            .copied()
            .filter(|&v| v < whisker_low)
            .collect();

        let outliers_high: Vec<f64> = values
            .iter()
            .copied()
            .filter(|&v| v > whisker_high)
            .collect();

        Some(BoxStats {
            x,
            q1,
            q2,
            q3,
            whisker_low,
            whisker_high,
            outliers_low,
            outliers_high,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_box_stats_empty() {
        assert!(BoxStats::from_values(0.0, &[]).is_none());
    }

    #[test]
    fn test_box_stats_single_value() {
        let stats = BoxStats::from_values(1.0, &[42.0]).unwrap();
        assert_eq!(stats.x, 1.0);
        assert_eq!(stats.q1, 42.0);
        assert_eq!(stats.q2, 42.0);
        assert_eq!(stats.q3, 42.0);
        assert_eq!(stats.whisker_low, 42.0);
        assert_eq!(stats.whisker_high, 42.0);
        assert!(stats.outliers_low.is_empty());
        assert!(stats.outliers_high.is_empty());
    }

    #[test]
    fn test_box_stats_no_outliers() {
        let values = vec![1.0, 2.0, 3.0, 4.0, 5.0];
        let stats = BoxStats::from_values(0.0, &values).unwrap();
        assert!(stats.outliers_low.is_empty());
        assert!(stats.outliers_high.is_empty());
        assert!(stats.q1 < stats.q2);
        assert!(stats.q2 < stats.q3);
    }

    #[test]
    fn test_box_stats_with_outliers() {
        let values = vec![1.0, 2.0, 3.0, 4.0, 5.0, 100.0];
        let stats = BoxStats::from_values(0.0, &values).unwrap();
        assert!(stats.outliers_high.contains(&100.0));
        assert!(!stats.outliers_high.contains(&5.0));
    }

    #[test]
    fn test_box_stats_all_same() {
        let values = vec![5.0, 5.0, 5.0, 5.0];
        let stats = BoxStats::from_values(0.0, &values).unwrap();
        assert_eq!(stats.q1, 5.0);
        assert_eq!(stats.q2, 5.0);
        assert_eq!(stats.q3, 5.0);
        assert_eq!(stats.whisker_low, 5.0);
        assert_eq!(stats.whisker_high, 5.0);
    }

    #[test]
    fn test_box_stats_negative_values() {
        let values = vec![-10.0, -5.0, 0.0, 5.0, 10.0];
        let stats = BoxStats::from_values(0.0, &values).unwrap();
        assert!(stats.q2.abs() < 1e-10);
        assert!(stats.whisker_low >= -10.0);
        assert!(stats.whisker_high <= 10.0);
    }
}
