// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::percentile_unsorted;

/// Statistics for a single box in a box plot
#[derive(Debug, Clone)]
pub struct BoxStats {
    /// X position (bin center)
    pub x: f64,
    /// First quartile (25th percentile)
    pub q1: f64,
    /// Median (50th percentile)
    pub q2: f64,
    /// Third quartile (75th percentile)
    pub q3: f64,
    /// Lower whisker extent
    pub whisker_low: f64,
    /// Upper whisker extent
    pub whisker_high: f64,
    /// Outliers below the lower whisker
    pub outliers_low: Vec<f64>,
    /// Outliers above the upper whisker
    pub outliers_high: Vec<f64>,
}

impl BoxStats {
    /// Calculate box statistics from a slice of values. The input does not need
    /// to be sorted; quartiles are computed with `select_nth_unstable` for
    /// expected O(n) time.
    pub(super) fn from_values(x: f64, values: &[f64]) -> Option<Self> {
        if values.is_empty() {
            return None;
        }

        // Calculate quartiles using linear interpolation without full sort.
        let q1 = percentile_unsorted(values, 0.25);
        let q2 = percentile_unsorted(values, 0.50);
        let q3 = percentile_unsorted(values, 0.75);

        let iqr = q3 - q1;
        let whisker_low_limit = q1 - 1.5 * iqr;
        let whisker_high_limit = q3 + 1.5 * iqr;

        // Find actual whisker positions (closest data points within limits)
        // by scanning the unsorted values once.
        let mut whisker_low = f64::INFINITY;
        let mut whisker_high = f64::NEG_INFINITY;
        for &v in values {
            if v >= whisker_low_limit && v < whisker_low {
                whisker_low = v;
            }
            if v <= whisker_high_limit && v > whisker_high {
                whisker_high = v;
            }
        }
        if whisker_low.is_infinite() {
            whisker_low = values.iter().copied().fold(f64::INFINITY, f64::min);
        }
        if whisker_high.is_infinite() {
            whisker_high = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        }

        // Collect outliers
        let outliers_low: Vec<f64> = values
            .iter()
            .copied()
            .filter(|&v| v < whisker_low)
            .collect();

        let outliers_high: Vec<f64> = values
            .iter()
            .copied()
            .filter(|&v| v > whisker_high)
            .collect();

        Some(BoxStats {
            x,
            q1,
            q2,
            q3,
            whisker_low,
            whisker_high,
            outliers_low,
            outliers_high,
        })
    }
}
