// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::data::SurfaceData;
use super::super::data::SurfacePoint3D;
use super::super::mesh::SurfaceMesh;
use super::super::projection::{
    IsometricProjection, ObliqueProjection, OrthographicProjection, PerspectiveProjection, Point2D,
    ProjectionType,
};
use super::misc::format_tick_value;
use super::projection_impl::ProjectionImpl;
use super::surface_config::SurfaceConfig;
use crate::text::{GlyphTextConfig, HorizontalTextAnchor, VerticalTextAnchor, paint_chart_text_at};
use gpui::prelude::*;
use gpui::*;
use std::collections::hash_map::DefaultHasher;
use std::f32::consts::PI;
use std::hash::{Hash, Hasher};
use std::panic;

/// A projected triangle ready for painting.
#[derive(Clone, Debug)]
pub(super) struct ProjectedTriangle {
    /// Projected 2D vertices.
    pub points: [Point2D; 3],
    /// Fill color after color scale / lighting.
    pub color: crate::color::D3Color,
}

/// Which axis a cached tick belongs to.
#[derive(Clone, Copy, Debug)]
enum Axis {
    X,
    Y,
    Z,
}

/// Cached axis tick geometry and label text.
#[derive(Clone, Debug)]
struct CachedAxisTick {
    axis: Axis,
    start: Point2D,
    end: Point2D,
    label: Option<String>,
}

/// Cached paint-time axis geometry so projections and tick labels are not
/// recomputed every `paint` call.
#[derive(Clone, Debug)]
struct PaintCache {
    generation: u64,
    origin: Point2D,
    x_end: Point2D,
    y_end: Point2D,
    z_end: Point2D,
    ticks: Vec<CachedAxisTick>,
    axis_labels: Option<[(Point2D, String); 3]>,
}

/// A custom GPUI element for rendering 3D surfaces
pub struct SurfaceElement {
    /// The surface mesh
    pub(super) mesh: SurfaceMesh,
    /// The surface data (for range info)
    pub(super) data: SurfaceData,
    /// Configuration
    pub(super) config: SurfaceConfig,
    /// Element width
    pub(super) width: Pixels,
    /// Element height
    pub(super) height: Pixels,
    /// Cached geometry generation key (camera + data + bounds + visual params).
    pub(super) cache_generation: u64,
    /// Cached projected triangles, reused across `paint` calls.
    pub(super) cached_projected: Vec<ProjectedTriangle>,
    /// Whether `cached_projected` is populated for the current generation.
    pub(super) has_cached_projected: bool,
    /// Cached axis endpoints, tick geometry, and pre-formatted tick labels.
    paint_cache: Option<PaintCache>,
}

impl SurfaceElement {
    /// Create a new surface element
    pub fn new(data: &SurfaceData, config: SurfaceConfig, width: f32, height: f32) -> Self {
        // Normalize data to unit cube for consistent rendering
        let normalized = data.normalize();

        // Create mesh from normalized data
        let mut mesh = SurfaceMesh::from_surface_data(&normalized);

        // Apply color scale
        mesh.apply_color_scale(normalized.t_range, |t| config.get_color(t));

        Self {
            mesh,
            data: normalized,
            config,
            width: px(width),
            height: px(height),
            cache_generation: u64::MAX,
            cached_projected: Vec::new(),
            has_cached_projected: false,
            paint_cache: None,
        }
    }

    /// Set element dimensions
    pub fn size(mut self, width: f32, height: f32) -> Self {
        self.width = px(width);
        self.height = px(height);
        self
    }

    /// Create the projection based on config
    pub(super) fn create_projection(&self, bounds: &Bounds<Pixels>) -> ProjectionImpl {
        let width: f32 = bounds.size.width.into();
        let height: f32 = bounds.size.height.into();
        let origin_x: f32 = bounds.origin.x.into();
        let origin_y: f32 = bounds.origin.y.into();

        // Center the projection in the bounds
        let center_x = origin_x + width / 2.0;
        let center_y = origin_y + height / 2.0;

        // Scale based on the smaller dimension to fit
        let base_scale = width.min(height) as f64 * 0.35 * self.config.scale;

        match self.config.projection_type {
            ProjectionType::Isometric => ProjectionImpl::Isometric(
                IsometricProjection::new()
                    .scale(base_scale)
                    .origin(center_x as f64, center_y as f64)
                    .camera(self.config.camera.clone()),
            ),
            ProjectionType::Oblique => ProjectionImpl::Oblique(
                ObliqueProjection::cabinet()
                    .scale(base_scale)
                    .origin(center_x as f64, center_y as f64),
            ),
            ProjectionType::Orthographic => ProjectionImpl::Orthographic(
                OrthographicProjection::new()
                    .scale(base_scale)
                    .rotation(
                        self.config.camera.rotation_x,
                        0.0,
                        self.config.camera.rotation_z,
                    )
                    .origin(center_x as f64, center_y as f64),
            ),
            ProjectionType::Perspective => ProjectionImpl::Perspective(
                PerspectiveProjection::new()
                    .scale(base_scale)
                    .distance(3.0)
                    .rotation(
                        self.config.camera.rotation_x,
                        0.0,
                        self.config.camera.rotation_z,
                    )
                    .origin(center_x as f64, center_y as f64),
            ),
        }
    }

    /// Compute a generation key for the geometry cache.
    ///
    /// The key covers camera, bounds, projection settings, lighting, and the data points.
    /// Changes that only affect opacity / wireframe styling do not invalidate the projected
    /// geometry, so `paint` can reuse the buffer.
    pub(super) fn compute_generation(&self, bounds: &Bounds<Pixels>) -> u64 {
        let mut hasher = DefaultHasher::new();

        // Camera
        self.config.camera.rotation_x.to_bits().hash(&mut hasher);
        self.config.camera.rotation_z.to_bits().hash(&mut hasher);
        self.config.camera.zoom.to_bits().hash(&mut hasher);
        self.config.camera.pan.0.to_bits().hash(&mut hasher);
        self.config.camera.pan.1.to_bits().hash(&mut hasher);

        // Projection / scale
        (self.config.projection_type as i32).hash(&mut hasher);
        self.config.scale.to_bits().hash(&mut hasher);

        // Bounds (projection center depends on origin, projected vertices depend on size)
        let width: f32 = bounds.size.width.into();
        let height: f32 = bounds.size.height.into();
        let origin_x: f32 = bounds.origin.x.into();
        let origin_y: f32 = bounds.origin.y.into();
        width.to_bits().hash(&mut hasher);
        height.to_bits().hash(&mut hasher);
        origin_x.to_bits().hash(&mut hasher);
        origin_y.to_bits().hash(&mut hasher);

        // Lighting / color settings affect triangle colors
        self.config.lighting.hash(&mut hasher);
        self.config.ambient.to_bits().hash(&mut hasher);
        self.config.diffuse.to_bits().hash(&mut hasher);
        self.config.light_direction.0.to_bits().hash(&mut hasher);
        self.config.light_direction.1.to_bits().hash(&mut hasher);
        self.config.light_direction.2.to_bits().hash(&mut hasher);
        // Color scale (manual hash to avoid requiring Hash on D3Color)
        match self.config.color_scale {
            super::color_scale_type::ColorScaleType::Viridis => 0u8.hash(&mut hasher),
            super::color_scale_type::ColorScaleType::Heat => 1u8.hash(&mut hasher),
            super::color_scale_type::ColorScaleType::Cool => 2u8.hash(&mut hasher),
            super::color_scale_type::ColorScaleType::Spectral => 3u8.hash(&mut hasher),
            super::color_scale_type::ColorScaleType::Grayscale => 4u8.hash(&mut hasher),
            super::color_scale_type::ColorScaleType::Monochrome(c) => {
                5u8.hash(&mut hasher);
                c.r.to_bits().hash(&mut hasher);
                c.g.to_bits().hash(&mut hasher);
                c.b.to_bits().hash(&mut hasher);
                c.a.to_bits().hash(&mut hasher);
            }
        }

        // Data points
        for row in self.data.points() {
            for p in row {
                hash_point3d(p, &mut hasher);
            }
        }

        hasher.finish()
    }

    /// Compute a generation key for the paint-time axis/tick cache.
    ///
    /// Extends the geometry cache key with label-related state so that changes
    /// to axis ranges or labels invalidate the formatted tick strings.
    pub(super) fn compute_paint_generation(&self, bounds: &Bounds<Pixels>) -> u64 {
        let mut hasher = DefaultHasher::new();
        self.compute_generation(bounds).hash(&mut hasher);

        if let Some(((x_min, x_max), (y_min, y_max), (z_min, z_max))) = self.config.axis_ranges {
            x_min.to_bits().hash(&mut hasher);
            x_max.to_bits().hash(&mut hasher);
            y_min.to_bits().hash(&mut hasher);
            y_max.to_bits().hash(&mut hasher);
            z_min.to_bits().hash(&mut hasher);
            z_max.to_bits().hash(&mut hasher);
        }

        if let Some((x_label, y_label, z_label)) = &self.config.axis_labels {
            x_label.hash(&mut hasher);
            y_label.hash(&mut hasher);
            z_label.hash(&mut hasher);
        }

        hasher.finish()
    }

    /// Prepare geometry for rendering: depth-sort, apply lighting, and project vertices.
    ///
    /// This is split out from the GPUI `prepaint` callback so it can be unit-tested without a
    /// window/app context.
    pub(super) fn prepare_geometry(&mut self, bounds: Bounds<Pixels>) {
        let generation = self.compute_generation(&bounds);
        if self.has_cached_projected && self.cache_generation == generation {
            return;
        }

        let projection = self.create_projection(&bounds);

        // Apply depth sorting using painter's algorithm
        self.mesh.triangles.sort_by(|a, b| {
            let centroid_a = a.centroid();
            let centroid_b = b.centroid();

            let depth_a = projection.point_depth(&centroid_a);
            let depth_b = projection.point_depth(&centroid_b);

            // Sort by depth: larger depth (further) should come first
            depth_b
                .partial_cmp(&depth_a)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        // Apply lighting if enabled
        if self.config.lighting {
            // Re-apply color scale first (lighting modifies colors)
            self.mesh
                .apply_color_scale(self.data.t_range, |t| self.config.get_color(t));
            self.mesh.apply_lighting(
                self.config.light_direction,
                self.config.ambient,
                self.config.diffuse,
            );
        }

        // Pre-project all vertices once, centered at origin
        let offset = -0.5;
        self.cached_projected.clear();
        self.cached_projected.reserve(self.mesh.triangles.len());
        for triangle in &self.mesh.triangles {
            let p0 = projection.project(
                triangle.vertices[0].x + offset,
                triangle.vertices[0].y + offset,
                triangle.vertices[0].z + offset,
            );
            let p1 = projection.project(
                triangle.vertices[1].x + offset,
                triangle.vertices[1].y + offset,
                triangle.vertices[1].z + offset,
            );
            let p2 = projection.project(
                triangle.vertices[2].x + offset,
                triangle.vertices[2].y + offset,
                triangle.vertices[2].z + offset,
            );
            self.cached_projected.push(ProjectedTriangle {
                points: [p0, p1, p2],
                color: triangle.color,
            });
        }

        self.cache_generation = generation;
        self.has_cached_projected = true;
    }

    /// Return the cached projected triangles for inspection (tests).
    #[cfg(test)]
    pub(super) fn projected_triangles(&self) -> &[ProjectedTriangle] {
        &self.cached_projected
    }

    /// Return whether the projected triangle buffer is currently cached.
    #[cfg(test)]
    pub(super) fn has_projected_cache(&self) -> bool {
        self.has_cached_projected
    }
}

fn hash_point3d(p: &SurfacePoint3D, hasher: &mut DefaultHasher) {
    p.x.to_bits().hash(hasher);
    p.y.to_bits().hash(hasher);
    p.z.to_bits().hash(hasher);
    p.t.to_bits().hash(hasher);
}

impl IntoElement for SurfaceElement {
    type Element = Self;

    fn into_element(self) -> Self::Element {
        self
    }
}

impl Element for SurfaceElement {
    type RequestLayoutState = ();
    type PrepaintState = ();

    fn id(&self) -> Option<ElementId> {
        None
    }

    fn source_location(&self) -> Option<&'static panic::Location<'static>> {
        None
    }

    fn request_layout(
        &mut self,
        _id: Option<&GlobalElementId>,
        _inspector_id: Option<&InspectorElementId>,
        window: &mut Window,
        cx: &mut App,
    ) -> (LayoutId, Self::RequestLayoutState) {
        let layout_id = window.request_layout(
            Style {
                size: size(self.width.into(), self.height.into()),
                min_size: size(px(100.0).into(), px(100.0).into()),
                ..Default::default()
            },
            [],
            cx,
        );
        (layout_id, ())
    }

    fn prepaint(
        &mut self,
        _id: Option<&GlobalElementId>,
        _inspector_id: Option<&InspectorElementId>,
        bounds: Bounds<Pixels>,
        _request_layout: &mut Self::RequestLayoutState,
        _window: &mut Window,
        _cx: &mut App,
    ) -> Self::PrepaintState {
        self.prepare_geometry(bounds);
    }

    fn paint(
        &mut self,
        _id: Option<&GlobalElementId>,
        _inspector_id: Option<&InspectorElementId>,
        bounds: Bounds<Pixels>,
        _request_layout: &mut Self::RequestLayoutState,
        _prepaint: &mut Self::PrepaintState,
        window: &mut Window,
        cx: &mut App,
    ) {
        // `prepaint` already prepares the geometry; only fall back if it was
        // skipped (e.g. direct unit-test paint calls).
        if !self.has_cached_projected {
            self.prepare_geometry(bounds);
        }

        // Paint each triangle using the cached projected buffer
        for tri in &self.cached_projected {
            let [p0, p1, p2] = tri.points;
            let mut builder = PathBuilder::fill();
            builder.move_to(point(px(p0.x as f32), px(p0.y as f32)));
            builder.line_to(point(px(p1.x as f32), px(p1.y as f32)));
            builder.line_to(point(px(p2.x as f32), px(p2.y as f32)));

            if let Ok(path) = builder.build() {
                let mut fill_color = tri.color.to_rgba();
                fill_color.a *= self.config.opacity;
                window.paint_path(path, fill_color);
            }

            // Draw wireframe if enabled
            if self.config.wireframe {
                let mut stroke_builder = PathBuilder::stroke(px(self.config.wireframe_width));
                stroke_builder.move_to(point(px(p0.x as f32), px(p0.y as f32)));
                stroke_builder.line_to(point(px(p1.x as f32), px(p1.y as f32)));
                stroke_builder.line_to(point(px(p2.x as f32), px(p2.y as f32)));
                stroke_builder.line_to(point(px(p0.x as f32), px(p0.y as f32)));

                if let Ok(stroke_path) = stroke_builder.build() {
                    let mut wireframe_rgba = self.config.wireframe_color.to_rgba();
                    wireframe_rgba.a *= self.config.wireframe_opacity;
                    window.paint_path(stroke_path, wireframe_rgba);
                }
            }
        }

        // Draw 3D axes if enabled
        if self.config.show_axes {
            let generation = self.compute_paint_generation(&bounds);
            if self.paint_cache.as_ref().map_or(true, |c| c.generation != generation) {
                let projection = self.create_projection(&bounds);

                let origin = (-0.5, -0.5, -0.5);
                let x_end = (0.6, -0.5, -0.5);
                let y_end = (-0.5, 0.6, -0.5);
                let z_end = (-0.5, -0.5, 0.6);

                let p_origin = projection.project(origin.0, origin.1, origin.2);
                let p_x = projection.project(x_end.0, x_end.1, x_end.2);
                let p_y = projection.project(y_end.0, y_end.1, y_end.2);
                let p_z = projection.project(z_end.0, z_end.1, z_end.2);

                let tick_size = 0.03;
                let num_ticks = 5;
                let mut ticks = Vec::with_capacity((num_ticks + 1) * 3);

                for i in 0..=num_ticks {
                    let t = i as f64 / num_ticks as f64;

                    // X axis tick
                    let x_tick_pos = (-0.5 + t * 1.0, -0.5, -0.5);
                    let x_tick_end = (-0.5 + t * 1.0, -0.5 - tick_size, -0.5);
                    let x_label =
                        if let Some(((x_min, x_max), _, _)) = self.config.axis_ranges {
                            Some(format_tick_value(x_min + t * (x_max - x_min), x_min, x_max))
                        } else {
                            None
                        };
                    ticks.push(CachedAxisTick {
                        axis: Axis::X,
                        start: projection.project(x_tick_pos.0, x_tick_pos.1, x_tick_pos.2),
                        end: projection.project(x_tick_end.0, x_tick_end.1, x_tick_end.2),
                        label: x_label,
                    });

                    // Y axis tick
                    let y_tick_pos = (-0.5, -0.5 + t * 1.0, -0.5);
                    let y_tick_end = (-0.5 - tick_size, -0.5 + t * 1.0, -0.5);
                    let y_label =
                        if let Some((_, (y_min, y_max), _)) = self.config.axis_ranges {
                            Some(format_tick_value(y_min + t * (y_max - y_min), y_min, y_max))
                        } else {
                            None
                        };
                    ticks.push(CachedAxisTick {
                        axis: Axis::Y,
                        start: projection.project(y_tick_pos.0, y_tick_pos.1, y_tick_pos.2),
                        end: projection.project(y_tick_end.0, y_tick_end.1, y_tick_end.2),
                        label: y_label,
                    });

                    // Z axis tick
                    let z_tick_pos = (-0.5, -0.5, -0.5 + t * 1.0);
                    let z_tick_end = (-0.5 - tick_size, -0.5, -0.5 + t * 1.0);
                    let z_label =
                        if let Some((_, _, (z_min, z_max))) = self.config.axis_ranges {
                            Some(format_tick_value(z_min + t * (z_max - z_min), z_min, z_max))
                        } else {
                            None
                        };
                    ticks.push(CachedAxisTick {
                        axis: Axis::Z,
                        start: projection.project(z_tick_pos.0, z_tick_pos.1, z_tick_pos.2),
                        end: projection.project(z_tick_end.0, z_tick_end.1, z_tick_end.2),
                        label: z_label,
                    });
                }

                let axis_labels = self.config.axis_labels.as_ref().map(|(x, y, z)| {
                    [
                        (projection.project(0.7, -0.5, -0.5), x.clone()),
                        (projection.project(-0.5, 0.7, -0.5), y.clone()),
                        (projection.project(-0.5, -0.5, 0.7), z.clone()),
                    ]
                });

                self.paint_cache = Some(PaintCache {
                    generation,
                    origin: p_origin,
                    x_end: p_x,
                    y_end: p_y,
                    z_end: p_z,
                    ticks,
                    axis_labels,
                });
            }

            let cache = self.paint_cache.as_ref().expect("paint cache just set");
            let axis_color = self.config.axis_color.to_rgba();
            let tick_font_size = self.config.axis_font_size;

            // Draw X axis
            let mut x_builder = PathBuilder::stroke(px(self.config.axis_width));
            x_builder.move_to(point(px(cache.origin.x as f32), px(cache.origin.y as f32)));
            x_builder.line_to(point(px(cache.x_end.x as f32), px(cache.x_end.y as f32)));
            if let Ok(path) = x_builder.build() {
                window.paint_path(path, axis_color);
            }

            // Draw Y axis
            let mut y_builder = PathBuilder::stroke(px(self.config.axis_width));
            y_builder.move_to(point(px(cache.origin.x as f32), px(cache.origin.y as f32)));
            y_builder.line_to(point(px(cache.y_end.x as f32), px(cache.y_end.y as f32)));
            if let Ok(path) = y_builder.build() {
                window.paint_path(path, axis_color);
            }

            // Draw Z axis
            let mut z_builder = PathBuilder::stroke(px(self.config.axis_width));
            z_builder.move_to(point(px(cache.origin.x as f32), px(cache.origin.y as f32)));
            z_builder.line_to(point(px(cache.z_end.x as f32), px(cache.z_end.y as f32)));
            if let Ok(path) = z_builder.build() {
                window.paint_path(path, axis_color);
            }

            // Draw tick marks and labels from the cache.
            for tick in &cache.ticks {
                let p1 = tick.start;
                let p2 = tick.end;
                let mut tick_builder = PathBuilder::stroke(px(1.0));
                tick_builder.move_to(point(px(p1.x as f32), px(p1.y as f32)));
                tick_builder.line_to(point(px(p2.x as f32), px(p2.y as f32)));
                if let Ok(path) = tick_builder.build() {
                    window.paint_path(path, axis_color);
                }

                if let Some(label) = tick.label.as_deref() {
                    let text_config = GlyphTextConfig::horizontal(tick_font_size, axis_color);
                    let (x, y, h_anchor, v_anchor) = match tick.axis {
                        Axis::X => (p2.x as f32, p2.y as f32 + 12.0, HorizontalTextAnchor::Middle, VerticalTextAnchor::Top),
                        Axis::Y | Axis::Z => (p2.x as f32 - 4.0, p2.y as f32, HorizontalTextAnchor::End, VerticalTextAnchor::Middle),
                    };
                    paint_chart_text_at(
                        window,
                        cx,
                        label,
                        x,
                        y,
                        &text_config,
                        h_anchor,
                        v_anchor,
                    );
                }
            }

            // Draw axis labels if configured
            if let Some(labels) = &cache.axis_labels {
                let font_size = 11.0;
                let horizontal_text = GlyphTextConfig::horizontal(font_size, axis_color);
                let vertical_text = GlyphTextConfig::rotated(font_size, axis_color, -PI / 2.0);

                let (x_label_pos, x_label) = &labels[0];
                paint_chart_text_at(
                    window,
                    cx,
                    x_label,
                    x_label_pos.x as f32,
                    x_label_pos.y as f32 + 15.0,
                    &horizontal_text,
                    HorizontalTextAnchor::Middle,
                    VerticalTextAnchor::Top,
                );

                let (y_label_pos, y_label) = &labels[1];
                paint_chart_text_at(
                    window,
                    cx,
                    y_label,
                    y_label_pos.x as f32 - 15.0,
                    y_label_pos.y as f32,
                    &vertical_text,
                    HorizontalTextAnchor::Middle,
                    VerticalTextAnchor::Middle,
                );

                let (z_label_pos, z_label) = &labels[2];
                paint_chart_text_at(
                    window,
                    cx,
                    z_label,
                    z_label_pos.x as f32 - 15.0,
                    z_label_pos.y as f32,
                    &vertical_text,
                    HorizontalTextAnchor::Middle,
                    VerticalTextAnchor::Middle,
                );
            }
        }
    }
}
