// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::camera_spec::CameraSpec;
use super::color_rgba::ColorRgba;
use super::line_segment_spec::LineSegmentSpec;
use super::line_strip_spec::LineStripSpec;
use super::lines_spec::LinesSpec;
use super::material_spec::MaterialSpec;
use super::mesh_spec::MeshSpec;
use super::orbit_camera_spec::OrbitCameraSpec;
use super::point3::Point3;
use super::scene_node::SceneNode;
use super::scene_spec::SceneSpec;
use super::surface_spec::SurfaceSpec;
use crate::error::Scene3DError;
use std::borrow::Cow;

#[test]
fn surface_x_values_returns_borrowed_for_explicit_axis() {
    let mut spec = SurfaceSpec::from_flat("surface", vec![1.0, 2.0, 3.0, 4.0], 2, 2);
    spec.x = Some(vec![10.0, 20.0]);
    match spec.x_values() {
        Cow::Borrowed(values) => assert_eq!(values, &[10.0, 20.0]),
        Cow::Owned(_) => panic!("expected borrowed explicit x values"),
    }
}

#[test]
fn surface_default_axis_values_are_cached() {
    let spec_a = SurfaceSpec::from_flat("surface", vec![1.0, 2.0, 3.0, 4.0], 2, 2);
    let spec_b = SurfaceSpec::from_flat("other", vec![5.0, 6.0, 7.0, 8.0], 2, 2);

    let x_a: Vec<f64> = spec_a.x_values().into();
    let x_b: Vec<f64> = spec_b.x_values().into();
    assert_eq!(x_a, x_b);
    assert_eq!(x_a, vec![0.0, 1.0]);

    let y_a: Vec<f64> = spec_a.y_values().into();
    let y_b: Vec<f64> = spec_b.y_values().into();
    assert_eq!(y_a, y_b);
    assert_eq!(y_a, vec![0.0, 1.0]);
}

#[test]
fn surface_validates_grid_dimensions() {
    let spec = SurfaceSpec::from_flat("surface", vec![1.0, 2.0, 3.0], 2, 2);
    assert!(matches!(
        spec.validate(),
        Err(Scene3DError::GridDimensionMismatch {
            z_len: 3,
            width: 2,
            height: 2,
            expected: 4
        })
    ));
}

#[test]
fn surface_validates_log_axis_positivity() {
    let mut spec = SurfaceSpec::from_flat("surface", vec![1.0, 2.0, 3.0, 4.0], 2, 2);
    spec.x = Some(vec![0.0, 10.0]);
    spec.x_log = true;

    assert!(matches!(
        spec.validate(),
        Err(Scene3DError::InvalidData {
            field: "x",
            reason: "contains non-positive values for log scale"
        })
    ));
}

#[test]
fn surface_requires_monotonic_axes() {
    let mut spec = SurfaceSpec::from_flat("surface", vec![1.0, 2.0, 3.0, 4.0], 2, 2);
    spec.y = Some(vec![2.0, 1.0]);

    assert!(matches!(
        spec.validate(),
        Err(Scene3DError::InvalidData {
            field: "y",
            reason: "must be strictly monotonically increasing"
        })
    ));
}

#[test]
fn surface_from_rows_flattens_row_major_data() {
    let spec = SurfaceSpec::from_rows("surface", vec![vec![1.0, 2.0], vec![3.0, 4.0]])
        .expect("valid surface");

    assert_eq!(spec.z.width, 2);
    assert_eq!(spec.z.height, 2);
    assert_eq!(spec.z.values, vec![1.0, 2.0, 3.0, 4.0]);
    assert_eq!(
        spec.z.rows().collect::<Vec<_>>(),
        vec![&[1.0, 2.0], &[3.0, 4.0]]
    );
}

#[test]
fn mesh_rejects_invalid_indices() {
    let spec = MeshSpec {
        id: "mesh".to_string(),
        vertices: vec![
            Point3::new(0.0, 0.0, 0.0),
            Point3::new(1.0, 0.0, 0.0),
            Point3::new(0.0, 1.0, 0.0),
        ],
        indices: vec![0, 1, 3],
        material: MaterialSpec::default(),
    };

    assert!(matches!(
        spec.validate(),
        Err(Scene3DError::InvalidMeshIndex {
            position: 2,
            index: 3,
            vertex_count: 3
        })
    ));
}

#[test]
fn line_strip_expands_to_segments() {
    let strip = LineStripSpec {
        id: "path".to_string(),
        points: vec![
            Point3::new(0.0, 0.0, 0.0),
            Point3::new(1.0, 0.0, 0.0),
            Point3::new(1.0, 1.0, 0.0),
        ],
        color: ColorRgba::from_rgb_u8(255, 255, 255),
        width: 2.0,
    };

    let segments: Vec<_> = strip.to_segments().collect();
    assert_eq!(segments.len(), 2);
    assert_eq!(segments[0].from, strip.points[0]);
    assert_eq!(segments[1].to, strip.points[2]);
}

#[test]
fn serde_uses_snake_case_tags() {
    let camera = CameraSpec::Orbit(OrbitCameraSpec::new(3.5, 60.0, 25.0));
    let value = serde_json::to_value(camera).expect("camera json");

    assert_eq!(value["kind"], "orbit");
    assert_eq!(value["distance"], 3.5);
}

#[test]
fn color_hex_parses_alpha() {
    let color = ColorRgba::from_hex("#33669980").expect("color");

    assert!((color.r - 0x33 as f32 / 255.0).abs() < f32::EPSILON);
    assert!((color.a - 0x80 as f32 / 255.0).abs() < f32::EPSILON);
}

#[test]
fn lines_flatten_mixed_segments_and_strips() {
    let lines = LinesSpec {
        id: "lines".to_string(),
        segments: vec![LineSegmentSpec {
            from: Point3::new(0.0, 0.0, 0.0),
            to: Point3::new(1.0, 0.0, 0.0),
            color: ColorRgba::from_rgb_u8(255, 0, 0),
            width: 1.0,
        }],
        strips: vec![LineStripSpec {
            id: "strip".to_string(),
            points: vec![
                Point3::new(2.0, 0.0, 0.0),
                Point3::new(3.0, 0.0, 0.0),
                Point3::new(4.0, 0.0, 0.0),
            ],
            color: ColorRgba::from_rgb_u8(0, 255, 0),
            width: 2.0,
        }],
        ..LinesSpec::default()
    };

    let flattened = lines.flattened_segments();
    assert_eq!(flattened.len(), 3);
    assert_eq!(flattened[0].from, Point3::new(0.0, 0.0, 0.0));
    assert_eq!(flattened[1].from, Point3::new(2.0, 0.0, 0.0));
    assert_eq!(flattened[2].from, Point3::new(3.0, 0.0, 0.0));
}

#[test]
fn scene_fingerprints_are_stable_for_unchanged_spec() {
    let scene = SceneSpec {
        id: "scene".to_string(),
        camera: CameraSpec::Orbit(OrbitCameraSpec::new(3.5, 60.0, 25.0)),
        children: vec![SceneNode::Surface(SurfaceSpec::from_flat(
            "surface",
            vec![1.0, 2.0, 3.0, 4.0],
            2,
            2,
        ))],
        interactions: vec![],
        background: None,
        size: None,
    };

    let first = scene.fingerprints();
    let second = scene.fingerprints();

    assert_eq!(first.geometry, second.geometry);
    assert_eq!(first.material, second.material);
    assert_eq!(first.camera, second.camera);
}

#[test]
fn scene_fingerprints_differ_when_child_changes() {
    let mut scene = SceneSpec {
        id: "scene".to_string(),
        camera: CameraSpec::default(),
        children: vec![SceneNode::Surface(SurfaceSpec::from_flat(
            "surface",
            vec![1.0, 2.0, 3.0, 4.0],
            2,
            2,
        ))],
        interactions: vec![],
        background: None,
        size: None,
    };

    let original = scene.fingerprints();
    if let SceneNode::Surface(surface) = &mut scene.children[0] {
        surface.colormap = super::colormap_spec::ColormapSpec::Turbo;
    }
    let changed = scene.fingerprints();

    assert_ne!(original.material, changed.material);
}
