// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::EPSILON;
use super::misc::degrees;
use super::misc::radians;

/// Rotation transform for spherical coordinates.
///
/// Rotates coordinates by the specified angles (in degrees).
#[derive(Clone, Debug)]
pub struct Rotation {
    /// Rotation around the z-axis (longitude rotation)
    pub lambda: f64,
    /// Rotation around the y-axis (latitude rotation)
    pub phi: f64,
    /// Rotation around the x-axis (gamma rotation)
    pub gamma: f64,
}

impl Default for Rotation {
    fn default() -> Self {
        Self::new()
    }
}

impl Rotation {
    /// Create a new rotation with zero angles.
    pub fn new() -> Self {
        Self {
            lambda: 0.0,
            phi: 0.0,
            gamma: 0.0,
        }
    }

    /// Set the rotation angles in degrees.
    pub fn angles(mut self, lambda: f64, phi: f64, gamma: f64) -> Self {
        self.lambda = lambda;
        self.phi = phi;
        self.gamma = gamma;
        self
    }

    /// Apply the rotation to a point (longitude, latitude in degrees).
    pub fn rotate(&self, lon: f64, lat: f64) -> (f64, f64) {
        let mut lambda = radians(lon);
        let mut phi = radians(lat);

        // Apply rotations
        lambda += radians(self.lambda);

        if self.phi.abs() > EPSILON || self.gamma.abs() > EPSILON {
            let cos_phi = phi.cos();
            let sin_phi = phi.sin();
            let cos_lambda = lambda.cos();
            let sin_lambda = lambda.sin();

            // Rotation around y-axis
            let phi_rad = radians(self.phi);
            let cos_phi_rot = phi_rad.cos();
            let sin_phi_rot = phi_rad.sin();

            let x = cos_phi * cos_lambda;
            let y = cos_phi * sin_lambda;
            let z = sin_phi;

            let x2 = x * cos_phi_rot - z * sin_phi_rot;
            let z2 = x * sin_phi_rot + z * cos_phi_rot;

            lambda = y.atan2(x2);
            phi = z2.asin();

            // Rotation around x-axis (gamma)
            if self.gamma.abs() > EPSILON {
                let gamma_rad = radians(self.gamma);
                let cos_gamma = gamma_rad.cos();
                let sin_gamma = gamma_rad.sin();

                let cos_phi = phi.cos();
                let sin_phi = phi.sin();
                let sin_lambda = lambda.sin();
                let cos_lambda = lambda.cos();

                let y = cos_phi * sin_lambda;
                let z = sin_phi;

                let y2 = y * cos_gamma - z * sin_gamma;
                let z2 = y * sin_gamma + z * cos_gamma;

                lambda = y2.atan2(cos_phi * cos_lambda);
                phi = z2.asin();
            }
        }

        (degrees(lambda), degrees(phi))
    }

    /// Apply the inverse rotation to a point.
    pub fn invert(&self, lon: f64, lat: f64) -> (f64, f64) {
        // Inverse rotation is rotation with negated angles in reverse order
        let inv = Rotation::new().angles(-self.gamma, -self.phi, -self.lambda);

        let mut lambda = radians(lon);
        let mut phi = radians(lat);

        // Apply inverse gamma
        if self.gamma.abs() > EPSILON {
            let gamma_rad = radians(-self.gamma);
            let cos_gamma = gamma_rad.cos();
            let sin_gamma = gamma_rad.sin();

            let cos_phi = phi.cos();
            let sin_phi = phi.sin();
            let sin_lambda = lambda.sin();
            let cos_lambda = lambda.cos();

            let y = cos_phi * sin_lambda;
            let z = sin_phi;

            let y2 = y * cos_gamma - z * sin_gamma;
            let z2 = y * sin_gamma + z * cos_gamma;

            lambda = y2.atan2(cos_phi * cos_lambda);
            phi = z2.asin();
        }

        // Apply inverse phi rotation
        if self.phi.abs() > EPSILON {
            let phi_rad = radians(-self.phi);
            let cos_phi_rot = phi_rad.cos();
            let sin_phi_rot = phi_rad.sin();

            let cos_phi = phi.cos();
            let sin_phi = phi.sin();
            let cos_lambda = lambda.cos();
            let sin_lambda = lambda.sin();

            let x = cos_phi * cos_lambda;
            let z = sin_phi;

            let x2 = x * cos_phi_rot - z * sin_phi_rot;
            let z2 = x * sin_phi_rot + z * cos_phi_rot;

            lambda = (cos_phi * sin_lambda).atan2(x2);
            phi = z2.asin();
        }

        // Apply inverse lambda rotation
        lambda -= radians(self.lambda);

        let _ = inv;
        (degrees(lambda), degrees(phi))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rotation_new_and_default() {
        let r = Rotation::new();
        assert_eq!(r.lambda, 0.0);
        assert_eq!(r.phi, 0.0);
        assert_eq!(r.gamma, 0.0);

        let d = Rotation::default();
        assert_eq!(d.lambda, 0.0);
    }

    #[test]
    fn test_rotation_identity() {
        let r = Rotation::new();
        assert!((r.rotate(10.0, 20.0).0 - 10.0).abs() < 1e-9);
        assert!((r.rotate(10.0, 20.0).1 - 20.0).abs() < 1e-9);
    }

    #[test]
    fn test_rotation_lambda_only() {
        let r = Rotation::new().angles(10.0, 0.0, 0.0);
        let (lon, lat) = r.rotate(0.0, 0.0);
        assert!((lon - 10.0).abs() < 1e-9);
        assert!(lat.abs() < 1e-9);
    }

    #[test]
    fn test_rotation_phi_and_gamma() {
        let r = Rotation::new().angles(0.0, 90.0, 0.0);
        let (lon, lat) = r.rotate(0.0, 0.0);
        assert!(lon.abs() < 1e-9);
        assert!((lat - 90.0).abs() < 1e-9);

        let r2 = Rotation::new().angles(0.0, 0.0, 90.0);
        let (lon2, lat2) = r2.rotate(0.0, 0.0);
        assert!(lon2.abs() < 1e-9);
        assert!(lat2.abs() < 1e-9);
    }

    #[test]
    fn test_rotation_invert_roundtrip() {
        let r = Rotation::new().angles(12.0, 34.0, 56.0);
        let (lon, lat) = (10.0, 20.0);
        let (lon2, lat2) = r.invert(r.rotate(lon, lat).0, r.rotate(lon, lat).1);
        assert!((lon - lon2).abs() < 1e-9);
        assert!((lat - lat2).abs() < 1e-9);
    }
}
