//! NumberInput component for numeric value entry
//!
//! A numeric input field with:
//! - Increment/decrement buttons (+ and -)
//! - Direct text editing of the value (click on value to edit)
//! - Keyboard navigation:
//!   - Arrow Up/Right: increase value
//!   - Arrow Down/Left: decrease value
//!   - Enter: confirm edit
//!   - Escape: cancel edit
//! - Scroll wheel adjustment
//! - Configurable step size, min/max bounds
//! - Value formatting (decimals, units)
//!
//! The component handles its own editing state internally - just provide
//! an `on_change` callback to receive value updates.
//!
//! # Thread-Local State Pattern
//!
//! This component uses `thread_local!` storage to persist focus handles and
//! edit state across renders. This is necessary because GPUI's `RenderOnce`
//! components are recreated on each render, but we need state to persist:
//!
//! - **Focus handles**: Must be the same instance across renders or focus is lost
//! - **Edit state**: Cursor position, text, and selection must persist during editing
//!
//! ## Memory Considerations
//!
//! The thread-local `HashMap` entries grow as new element IDs are used and are
//! never automatically cleaned up. For most applications this is fine because:
//! - Element IDs are typically static or part of a bounded set
//! - The stored data is small (FocusHandle, EditState)
//!
//! If you have dynamic element IDs (e.g., from a virtualized list), consider:
//! 1. Using a stable ID scheme that reuses IDs
//! 2. Calling `cleanup_number_input_state(id)` when components are removed
//!
//! ## Cleanup Function
//!
//! To manually clean up state for a removed element:
//! ```rust,ignore
//! cleanup_number_input_state(&element_id);
//! ```

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::accessibility::{AccessibilityExt, AccessibilityNode, AriaProps, AriaRole, AriaState};
use crate::theme::ThemeExt;
use gpui::prelude::{
    InteractiveElement, IntoElement, ParentElement, RenderOnce, StatefulInteractiveElement, Styled,
};
use gpui::{
    AnyElement, App, AppContext, ClipboardItem, Context, ElementId, Entity, FocusHandle,
    FontWeight, MouseButton, Render, SharedString, Subscription, WeakEntity, Window, div, px, rgba,
};
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

thread_local! {
    static NUMBER_INPUT_FOCUS_HANDLES: RefCell<HashMap<ElementId, FocusHandle>> = RefCell::new(HashMap::new());
}
thread_local! {
    static NUMBER_INPUT_EDIT_STATES: RefCell<HashMap<ElementId, Rc<RefCell<NumberEditState>>>> = RefCell::new(HashMap::new());
}
thread_local! {
    static NUMBER_INPUT_FOCUS_SUBS: RefCell<HashMap<ElementId, Subscription>> = RefCell::new(HashMap::new());
}
thread_local! {
    /// Stored blur handlers keyed by element id. The focus-out subscription is
    /// registered once per id and reads the latest handler from this map when
    /// fired, so we do not create a new subscription on every render.
    static NUMBER_INPUT_BLUR_HANDLERS: RefCell<
        HashMap<ElementId, Option<Rc<dyn Fn(f64, &mut Window, &mut App) + 'static>>>,
    > = RefCell::new(HashMap::new());
}
thread_local! {
    // Cached render entities so repeated renders reuse the same GPUI entity.
    // Stored as weak references so the entities can be dropped when no longer
    // referenced by the element tree, avoiding leaked-handle panics in tests.
    static NUMBER_INPUT_ENTITIES: RefCell<HashMap<ElementId, WeakEntity<NumberInputEntity>>> =
        RefCell::new(HashMap::new());
}

mod misc;
mod number_edit_state;
mod number_input_size;
mod types;

use misc::keystroke_to_char;
pub use misc::{cleanup_number_input_state, is_number_input_editing};
use number_edit_state::NumberEditState;
pub use number_input_size::NumberInputSize;
pub use types::NumberInputTheme;

/// A numeric input component with increment/decrement buttons
///
/// The component handles its own editing state internally. Just provide
/// an `on_change` callback to receive value updates.
#[derive(IntoElement)]
pub struct NumberInput {
    id: ElementId,
    value: f64,
    min: f64,
    max: f64,
    step: f64,
    decimals: usize,
    unit: Option<SharedString>,
    label: Option<SharedString>,
    size: NumberInputSize,
    width: Option<f32>,
    disabled: bool,
    theme: Option<NumberInputTheme>,
    on_change: Option<Rc<dyn Fn(f64, &mut Window, &mut App) + 'static>>,
    focus_handle: Option<FocusHandle>,
    aria_label: Option<SharedString>,
    aria_role: Option<AriaRole>,
}

impl NumberInput {
    /// Create a new number input with the given ID
    pub fn new(id: impl Into<ElementId>) -> Self {
        Self {
            id: id.into(),
            value: 0.0,
            min: f64::NEG_INFINITY,
            max: f64::INFINITY,
            step: 1.0,
            decimals: 0,
            unit: None,
            label: None,
            size: NumberInputSize::default(),
            width: None,
            disabled: false,
            theme: None,
            on_change: None,
            focus_handle: None,
            aria_label: None,
            aria_role: None,
        }
    }

    /// Set the focus handle (optional - one is created internally if not provided)
    pub fn focus_handle(mut self, handle: FocusHandle) -> Self {
        self.focus_handle = Some(handle);
        self
    }

    /// Set the current value
    ///
    /// NaN values are clamped to the minimum bound.
    pub fn value(mut self, value: f64) -> Self {
        // Handle NaN by falling back to min (or 0 if min is infinite)
        let value = if value.is_nan() {
            if self.min.is_finite() {
                self.min
            } else if self.max.is_finite() {
                self.max
            } else {
                0.0
            }
        } else {
            value
        };
        self.value = value.clamp(self.min, self.max);
        self
    }

    /// Set the minimum value
    ///
    /// # Panics
    /// Panics if min is NaN
    pub fn min(mut self, min: f64) -> Self {
        assert!(!min.is_nan(), "NumberInput min cannot be NaN");
        self.min = min;
        self
    }

    /// Set the maximum value
    ///
    /// # Panics
    /// Panics if max is NaN
    pub fn max(mut self, max: f64) -> Self {
        assert!(!max.is_nan(), "NumberInput max cannot be NaN");
        self.max = max;
        self
    }

    /// Set both min and max values at once
    ///
    /// # Panics
    /// Panics if min > max or if either value is NaN
    pub fn range(mut self, min: f64, max: f64) -> Self {
        assert!(!min.is_nan(), "NumberInput min cannot be NaN");
        assert!(!max.is_nan(), "NumberInput max cannot be NaN");
        assert!(
            min <= max,
            "NumberInput range invalid: min ({}) > max ({})",
            min,
            max
        );
        self.min = min;
        self.max = max;
        self
    }

    /// Set the step size for increment/decrement
    ///
    /// # Panics
    /// Panics if step is not positive or is NaN
    pub fn step(mut self, step: f64) -> Self {
        assert!(
            step > 0.0 && !step.is_nan(),
            "NumberInput step must be positive, got: {}",
            step
        );
        self.step = step;
        self
    }

    /// Set the number of decimal places to display
    pub fn decimals(mut self, decimals: usize) -> Self {
        self.decimals = decimals;
        self
    }

    /// Set the unit suffix (e.g., "Hz", "dB", "%")
    pub fn unit(mut self, unit: impl Into<SharedString>) -> Self {
        self.unit = Some(unit.into());
        self
    }

    /// Set the label
    pub fn label(mut self, label: impl Into<SharedString>) -> Self {
        self.label = Some(label.into());
        self
    }

    /// Set the size variant
    pub fn size(mut self, size: NumberInputSize) -> Self {
        self.size = size;
        self
    }

    /// Set fixed width (optional)
    pub fn width(mut self, width: f32) -> Self {
        self.width = Some(width);
        self
    }

    /// Set disabled state
    pub fn disabled(mut self, disabled: bool) -> Self {
        self.disabled = disabled;
        self
    }

    /// Set the theme
    pub fn theme(mut self, theme: NumberInputTheme) -> Self {
        self.theme = Some(theme);
        self
    }

    /// Set value change handler (called on button click, scroll, keyboard, or text edit confirm)
    pub fn on_change(mut self, handler: impl Fn(f64, &mut Window, &mut App) + 'static) -> Self {
        self.on_change = Some(Rc::new(handler));
        self
    }

    /// Set an explicit ARIA label
    pub fn aria_label(mut self, label: impl Into<SharedString>) -> Self {
        self.aria_label = Some(label.into());
        self
    }

    /// Override the default ARIA role (Spinbutton)
    pub fn aria_role(mut self, role: AriaRole) -> Self {
        self.aria_role = Some(role);
        self
    }

    /// Format value for display (test helper).
    #[cfg(test)]
    fn format_value_str(value: f64, decimals: usize, unit: Option<&SharedString>) -> String {
        let formatted = format!("{:.prec$}", value, prec = decimals);
        if let Some(unit) = unit {
            format!("{} {}", formatted, unit)
        } else {
            formatted
        }
    }

    /// Parse a string to a value, removing unit suffix.
    fn parse_value_str(text: &str, unit: Option<&SharedString>, min: f64, max: f64) -> Option<f64> {
        let text = if let Some(unit) = unit {
            text.trim().trim_end_matches(unit.as_ref()).trim()
        } else {
            text.trim()
        };

        text.parse::<f64>().ok().map(|v| v.clamp(min, max))
    }
}

fn render_number_input(
    props: &NumberInput,
    window: &mut Window,
    cx: &mut App,
) -> impl IntoElement {
    // Register in accessibility tree
    let effective_label = props
        .aria_label
        .clone()
        .or_else(|| props.label.clone())
        .unwrap_or_default();
    cx.register_accessible(AccessibilityNode {
        element_id: props.id.clone(),
        label: effective_label,
        props: AriaProps::with_role(props.aria_role.unwrap_or(AriaRole::Spinbutton))
            .maybe_state(props.disabled, AriaState::Disabled)
            .value_range(props.value, props.min, props.max),
    });

    let global_theme = cx.theme();
    let default_theme = NumberInputTheme::from(global_theme);
    let theme = props.theme.clone().unwrap_or(default_theme);

    let height = props.size.height();
    let button_width = props.size.button_width();
    let padding = props.size.padding();
    let disabled = props.disabled;
    let current_value = props.value;
    let min = props.min;
    let max = props.max;
    let step = props.step;
    let decimals = props.decimals;
    let unit = props.unit.clone();
    let label = props.label.clone();

    // Use provided focus handle, or get/create one from the registry.
    let focus_handle = props.focus_handle.clone().unwrap_or_else(|| {
        NUMBER_INPUT_FOCUS_HANDLES.with(|handles| {
            let mut handles = handles.borrow_mut();
            handles
                .entry(props.id.clone())
                .or_insert_with(|| cx.focus_handle())
                .clone()
        })
    });

    // Get or create edit state for this element
    let edit_state = NUMBER_INPUT_EDIT_STATES.with(|states| {
        let mut states = states.borrow_mut();
        states
            .entry(props.id.clone())
            .or_insert_with(|| Rc::new(RefCell::new(NumberEditState::default())))
            .clone()
    });

    // Clone callback Rc for sharing (needed by focus-out and key handler)
    let on_change_rc = props.on_change.clone();

    // Register a focus-out subscription to commit the edited value when focus
    // is lost. The subscription is created once per element id; the latest
    // change handler is stored in a thread-local map so the subscription can
    // invoke the most recent callback without being re-registered every render.
    {
        let id = props.id.clone();
        NUMBER_INPUT_BLUR_HANDLERS.with(|handlers| {
            handlers.borrow_mut().insert(id.clone(), on_change_rc.clone());
        });

        NUMBER_INPUT_FOCUS_SUBS.with(|subs| {
            let mut subs = subs.borrow_mut();
            if !subs.contains_key(&id) {
                let edit_state_for_blur = edit_state.clone();
                let unit_for_blur = unit.clone();
                let id_for_closure = id.clone();
                let sub = window.on_focus_out(&focus_handle, cx, move |_event, window, cx| {
                    let handler = NUMBER_INPUT_BLUR_HANDLERS.with(|h| {
                        h.borrow().get(&id_for_closure).cloned().flatten()
                    });
                    let mut state = edit_state_for_blur.borrow_mut();
                    if state.editing {
                        let parsed = NumberInput::parse_value_str(
                            &state.text,
                            unit_for_blur.as_ref(),
                            min,
                            max,
                        );
                        state.editing = false;
                        state.text.clear();
                        state.text_selected = false;
                        drop(state);

                        if let Some(ref handler) = handler
                            && let Some(value) = parsed
                        {
                            handler(value, window, cx);
                        }
                        window.refresh();
                    }
                });
                subs.insert(id, sub);
            }
        });
    }

    // Read current edit state — trust the thread-local state directly.
    // Focus loss is handled by on_focus_out (registered above), not during render,
    // because is_focused() returns false during re-render before the element
    // is re-associated with the focus handle via track_focus().
    // Format the value once and reuse it for display and click-to-edit state.
    let formatted_value = edit_state
        .borrow_mut()
        .format_value_str(current_value, decimals, unit.as_ref());

    let state = edit_state.borrow();
    let editing = state.editing;
    let text_selected = state.text_selected;
    let edit_text: SharedString = if editing {
        state.text.clone().into()
    } else {
        formatted_value.clone()
    };
    let cursor_pos = state.cursor;
    drop(state);

    // Create unique child IDs based on parent ID.
    // Use stable (id, suffix) tuples to avoid format! allocations on every render.
    let dec_id = ElementId::from((props.id.clone(), "dec"));
    let value_id = ElementId::from((props.id.clone(), "value"));
    let inc_id = ElementId::from((props.id.clone(), "inc"));

    let mut container = div().flex().flex_col().gap_1();

    // Label
    if let Some(label) = label {
        container = container.child(
            div()
                .text_sm()
                .text_color(theme.label)
                .font_weight(FontWeight::MEDIUM)
                .child(label),
        );
    }

    // Input row: [−] [value] [+]
    let mut input_row = div()
        .id(props.id.clone())
        .flex()
        .items_center()
        .h(px(height))
        .rounded_md()
        .border_1()
        .border_color(if editing {
            theme.border_focus
        } else {
            theme.border
        })
        .bg(theme.background)
        .overflow_hidden();

    if let Some(width) = props.width {
        input_row = input_row.w(px(width));
    }

    if disabled {
        input_row = input_row.opacity(theme.disabled_opacity);
    }

    // Decrement button (−)
    let button_bg = theme.button_bg;
    let button_hover = theme.button_hover;
    let button_active = theme.button_active;
    let button_text = theme.button_text;
    let text_color = theme.text;

    let mut dec_button = div()
        .id(dec_id)
        .flex()
        .items_center()
        .justify_center()
        .w(px(button_width))
        .h_full()
        .bg(button_bg)
        .text_color(button_text)
        .font_weight(FontWeight::BOLD)
        .child("−");

    if !disabled {
        dec_button = dec_button
            .cursor_pointer()
            .hover(move |s| s.bg(button_hover))
            .active(move |s| s.bg(button_active));

        if let Some(ref handler_rc) = on_change_rc {
            let handler = handler_rc.clone();
            dec_button = dec_button.on_mouse_down(MouseButton::Left, move |_, window, cx| {
                window.blur();
                let new_value = (current_value - step).clamp(min, max);
                handler(new_value, window, cx);
            });
        }
    } else {
        dec_button = dec_button.cursor_not_allowed();
    }

    input_row = input_row.child(dec_button);

    // Value display / edit field
    // Visual selection highlight: when text_selected is true, show accent background
    let (value_bg, value_text_color) = if editing && text_selected {
        (Some(theme.button_active), rgba(0xffffffff))
    } else {
        (None, text_color)
    };

    // Build display with cursor if editing and not all selected
    let display_element: AnyElement = if editing && !text_selected {
        // Render the full text as a single element and overlay an absolute
        // cursor div to avoid allocating before/after strings every frame.
        let char_width = 8.0_f32;
        let cursor_left = char_width * cursor_pos as f32;

        div()
            .relative()
            .flex()
            .items_center()
            .child(edit_text.clone())
            .child(
                div()
                    .absolute()
                    .left(px(cursor_left))
                    .top_0()
                    .bottom_0()
                    .w(px(1.0))
                    .bg(text_color),
            )
            .into_any_element()
    } else {
        div().child(edit_text.clone()).into_any_element()
    };

    let mut value_field = div()
        .id(value_id)
        .flex_1()
        .flex()
        .items_center()
        .justify_center()
        .h_full()
        .px(px(padding))
        .text_color(value_text_color)
        .track_focus(&focus_handle)
        .focusable()
        .child(display_element);

    // Apply selection background if selected
    if let Some(bg) = value_bg {
        value_field = value_field.bg(bg);
    }

    // Apply font size
    value_field = value_field.text_size(px(props.size.font_size()));

    if !disabled {
        // Click to start editing / focus
        let edit_state_for_click = edit_state.clone();
        let focus_handle_for_click = focus_handle.clone();
        let formatted_value_for_click = formatted_value.clone();

        value_field = value_field.cursor_text().on_mouse_down(
            MouseButton::Left,
            move |event, window, cx| {
                cx.stop_propagation();

                // Focus the input
                window.focus(&focus_handle_for_click, cx);

                let mut state = edit_state_for_click.borrow_mut();

                // Double-click: select all
                if event.click_count == 2 {
                    if state.editing {
                        state.select_all();
                    } else {
                        *state = NumberEditState::new(&formatted_value_for_click);
                    }
                    drop(state);
                    window.refresh();
                    return;
                }

                // Single click: start editing if not already
                if !state.editing {
                    *state = NumberEditState::new(&formatted_value_for_click);
                } else {
                    // Clear selection on single click while editing
                    state.text_selected = false;
                }
                drop(state);
                window.refresh();
            },
        );

        // Keyboard handling
        let edit_state_for_key = edit_state.clone();
        let on_change_key = on_change_rc.clone();
        let unit_for_key = unit.clone();

        value_field = value_field.on_key_down(move |event, window, cx| {
            cx.stop_propagation();

            let key = event.keystroke.key.as_str();
            let ctrl = event.keystroke.modifiers.control;
            let cmd = event.keystroke.modifiers.platform;
            let alt = event.keystroke.modifiers.alt;

            let mut state = edit_state_for_key.borrow_mut();

            if state.editing {
                // cmd/ctrl clipboard + select-all
                if cmd || (ctrl && matches!(key, "c" | "x" | "v" | "a")) {
                    match key {
                        "a" => {
                            state.select_all();
                            drop(state);
                            window.refresh();
                            return;
                        }
                        "c" => {
                            if let Some(selected) = state.get_selected_text() {
                                drop(state);
                                cx.write_to_clipboard(ClipboardItem::new_string(selected));
                            }
                            return;
                        }
                        "x" => {
                            if let Some(selected) = state.get_selected_text() {
                                cx.write_to_clipboard(ClipboardItem::new_string(selected));
                                state.delete_selected();
                                drop(state);
                                window.refresh();
                            }
                            return;
                        }
                        "v" => {
                            if let Some(clipboard) = cx.read_from_clipboard()
                                && let Some(paste_text) = clipboard.text()
                            {
                                state.insert_str(&paste_text);
                                drop(state);
                                window.refresh();
                            }
                            return;
                        }
                        _ => {}
                    }
                }

                // alt+backspace — kill word backward; alt+d — kill word forward
                if alt {
                    match key {
                        "backspace" => {
                            state.kill_word_backward();
                            drop(state);
                            window.refresh();
                            return;
                        }
                        "d" => {
                            state.kill_word_forward();
                            drop(state);
                            window.refresh();
                            return;
                        }
                        _ => {}
                    }
                }

                // Emacs ctrl bindings
                if ctrl {
                    match key {
                        "a" => state.move_to_start(),
                        "e" => state.move_to_end(),
                        "k" => state.kill_to_end(),
                        "u" => state.kill_to_start(),
                        "w" => state.kill_word_backward(),
                        "h" => state.do_backspace(),
                        "d" => state.do_delete(),
                        "f" => state.move_right(),
                        "b" => state.move_left(),
                        "y" => {
                            if let Some(clipboard) = cx.read_from_clipboard()
                                && let Some(paste_text) = clipboard.text()
                            {
                                state.insert_str(&paste_text);
                            }
                        }
                        _ => {}
                    }
                    drop(state);
                    window.refresh();
                    return;
                }

                match key {
                    "enter" => {
                        // Confirm edit - parse and call on_change
                        let parsed =
                            NumberInput::parse_value_str(&state.text, unit_for_key.as_ref(), min, max);
                        state.editing = false;
                        state.text.clear();
                        state.text_selected = false;
                        drop(state);

                        window.blur();

                        if let Some(ref handler) = on_change_key
                            && let Some(value) = parsed
                        {
                            handler(value, window, cx);
                        }
                        window.refresh();
                    }
                    "escape" => {
                        // Cancel edit - restore original value
                        state.editing = false;
                        state.text.clear();
                        state.text_selected = false;
                        drop(state);
                        window.blur();
                        window.refresh();
                    }
                    "backspace" => {
                        state.do_backspace();
                        drop(state);
                        window.refresh();
                    }
                    "delete" => {
                        state.do_delete();
                        drop(state);
                        window.refresh();
                    }
                    "left" => {
                        state.move_left();
                        drop(state);
                        window.refresh();
                    }
                    "right" => {
                        state.move_right();
                        drop(state);
                        window.refresh();
                    }
                    "home" => {
                        state.move_to_start();
                        drop(state);
                        window.refresh();
                    }
                    "end" => {
                        state.move_to_end();
                        drop(state);
                        window.refresh();
                    }
                    _ => {
                        // Character input - use key_char for actual text characters
                        if let Some(ch) = keystroke_to_char(&event.keystroke) {
                            state.insert_char(ch);
                            drop(state);
                            window.refresh();
                        }
                    }
                }
            } else {
                // Non-editing mode - arrow keys adjust value
                let new_value = match key {
                    "up" | "right" => Some((current_value + step).clamp(min, max)),
                    "down" | "left" => Some((current_value - step).clamp(min, max)),
                    _ => None,
                };
                drop(state);

                if let Some(v) = new_value
                    && let Some(ref handler) = on_change_key
                {
                    handler(v, window, cx);
                }
            }
        });
    }

    input_row = input_row.child(value_field);

    // Increment button (+)
    let mut inc_button = div()
        .id(inc_id)
        .flex()
        .items_center()
        .justify_center()
        .w(px(button_width))
        .h_full()
        .bg(button_bg)
        .text_color(button_text)
        .font_weight(FontWeight::BOLD)
        .child("+");

    if !disabled {
        inc_button = inc_button
            .cursor_pointer()
            .hover(move |s| s.bg(button_hover))
            .active(move |s| s.bg(button_active));

        if let Some(ref handler_rc) = on_change_rc {
            let handler = handler_rc.clone();
            inc_button = inc_button.on_mouse_down(MouseButton::Left, move |_, window, cx| {
                window.blur();
                let new_value = (current_value + step).clamp(min, max);
                handler(new_value, window, cx);
            });
        }
    } else {
        inc_button = inc_button.cursor_not_allowed();
    }

    input_row = input_row.child(inc_button);

    // Note: Scroll wheel handling removed to allow page scrolling.
    // Use +/- buttons or keyboard to adjust value.

    container.child(input_row)
}

/// Internal entity that renders a [`NumberInput`] with stable identity across frames.
pub struct NumberInputEntity {
    props: NumberInput,
}

impl Render for NumberInputEntity {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        render_number_input(&self.props, window, &mut **cx)
    }
}

impl RenderOnce for NumberInput {
    fn render(self, _window: &mut Window, cx: &mut App) -> impl IntoElement {
        let id = self.id.clone();
        let entity: Entity<NumberInputEntity> = NUMBER_INPUT_ENTITIES.with(|map| {
            let mut map = map.borrow_mut();
            if let Some(weak) = map.get(&id) {
                if let Some(entity) = weak.upgrade() {
                    return entity;
                }
            }
            let entity = cx.new(|_cx| NumberInputEntity {
                props: NumberInput::new(id.clone()),
            });
            map.insert(id.clone(), entity.downgrade());
            entity
        });
        entity.update(cx, |model, _cx| {
            model.props = self;
        });
        entity
    }
}

#[cfg(test)]
mod tests;
