//! Slider component for selecting numeric values within a range
//!
//! Features:
//! - Drag support: click and drag the thumb or anywhere on the track
//! - Scroll wheel: scroll up/down to adjust value (shift for fine control)
//! - Double-click to reset to default
//! - Keyboard navigation (when focused):
//!   - Arrow Up/Right: increase value (5%)
//!   - Arrow Down/Left: decrease value (5%)
//!   - Page Up: increase value (10%)
//!   - Page Down: decrease value (10%)
//!   - Home: set to minimum
//!   - End: set to maximum
//! - Value snapping with step parameter

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::accessibility::AriaRole;
use crate::interaction::{
    InteractionConfig, clear_drag_state, get_drag_state, handle_drag, handle_keyboard,
    handle_scroll, store_drag_state,
};
use crate::scale::Scale;
use crate::theme::ThemeExt;
use gpui::{
    App, ElementId, InteractiveElement, IntoElement, MouseButton, MouseMoveEvent, RenderOnce, Rgba,
    SharedString, StatefulInteractiveElement, Styled, Window, div, px,
};

use gpui::prelude::ParentElement;
use gpui_design::DesignSystem;
use std::rc::Rc;
use std::sync::Arc;

mod slider_size;
mod types;

pub use slider_size::SliderSize;
pub use types::SliderTheme;
/// A slider component for selecting numeric values
///
/// Supports:
/// - Mouse drag on track or thumb
/// - Scroll wheel adjustment (shift for fine-grained control)
/// - Double-click to reset to default
/// - Keyboard arrow keys (when focused)
#[derive(IntoElement)]
pub struct Slider {
    id: ElementId,
    value: f32,
    min: f32,
    max: f32,
    step: Option<f32>,
    size: SliderSize,
    disabled: bool,
    show_value: bool,
    label: Option<SharedString>,
    width: f32,
    on_change: Option<Rc<dyn Fn(f32, &mut Window, &mut App) + 'static>>,
    on_drag_start: Option<Rc<dyn Fn(f32, f32, &mut Window, &mut App) + 'static>>,
    on_reset: Option<Rc<dyn Fn(&mut Window, &mut App) + 'static>>,
    track_color: Option<Rgba>,
    fill_color: Option<Rgba>,
    thumb_color: Option<Rgba>,
    theme: Option<SliderTheme>,
    design: Option<Arc<DesignSystem>>,
    aria_label: Option<SharedString>,
    aria_role: Option<AriaRole>,
}

impl Slider {
    /// Create a new slider with the given ID
    pub fn new(id: impl Into<ElementId>) -> Self {
        Self {
            id: id.into(),
            value: 0.0,
            min: 0.0,
            max: 100.0,
            step: None,
            size: SliderSize::default(),
            disabled: false,
            show_value: false,
            label: None,
            width: 200.0,
            on_change: None,
            on_drag_start: None,
            on_reset: None,
            track_color: None,
            fill_color: None,
            thumb_color: None,
            theme: None,
            design: None,
            aria_label: None,
            aria_role: None,
        }
    }

    /// Set an explicit ARIA label
    pub fn aria_label(mut self, label: impl Into<SharedString>) -> Self {
        self.aria_label = Some(label.into());
        self
    }

    /// Override the default ARIA role (Slider)
    pub fn aria_role(mut self, role: AriaRole) -> Self {
        self.aria_role = Some(role);
        self
    }

    /// Set the current value
    pub fn value(mut self, value: f32) -> Self {
        self.value = value;
        self
    }

    /// Set the minimum value
    ///
    /// # Panics
    /// Panics if min > max after this call
    pub fn min(mut self, min: f32) -> Self {
        self.min = min;
        self
    }

    /// Set the maximum value
    ///
    /// # Panics
    /// Panics if min > max after this call
    pub fn max(mut self, max: f32) -> Self {
        self.max = max;
        self
    }

    /// Set both min and max values at once
    ///
    /// # Panics
    /// Panics if min > max
    pub fn range(mut self, min: f32, max: f32) -> Self {
        assert!(
            min <= max,
            "Slider range invalid: min ({}) > max ({})",
            min,
            max
        );
        self.min = min;
        self.max = max;
        self
    }

    /// Set the step size for snapping
    pub fn step(mut self, step: f32) -> Self {
        self.step = Some(step);
        self
    }

    /// Set the slider size
    pub fn size(mut self, size: SliderSize) -> Self {
        self.size = size;
        self
    }

    /// Set disabled state
    pub fn disabled(mut self, disabled: bool) -> Self {
        self.disabled = disabled;
        self
    }

    /// Show the current value as text
    pub fn show_value(mut self, show: bool) -> Self {
        self.show_value = show;
        self
    }

    /// Set a label for the slider
    pub fn label(mut self, label: impl Into<SharedString>) -> Self {
        self.label = Some(label.into());
        self
    }

    /// Set the width of the slider in pixels
    pub fn width(mut self, width: f32) -> Self {
        self.width = width;
        self
    }

    /// Set the change handler
    ///
    /// The handler receives the new value by value.
    pub fn on_change(mut self, handler: impl Fn(f32, &mut Window, &mut App) + 'static) -> Self {
        self.on_change = Some(Rc::new(handler));
        self
    }

    /// Set the change handler with a reference argument
    ///
    /// This variant is useful when using `cx.listener()` which passes a reference.
    pub fn on_change_ref(
        mut self,
        handler: impl Fn(&f32, &mut Window, &mut App) + 'static,
    ) -> Self {
        self.on_change = Some(Rc::new(move |value, window, app| {
            handler(&value, window, app);
        }));
        self
    }

    /// Set drag start handler (called on mouse down with x position and current value)
    ///
    /// Use this to track dragging state in your app. When dragging, you should
    /// calculate the new value based on mouse position and call the on_change handler.
    pub fn on_drag_start(
        mut self,
        handler: impl Fn(f32, f32, &mut Window, &mut App) + 'static,
    ) -> Self {
        self.on_drag_start = Some(Rc::new(handler));
        self
    }

    /// Set reset handler (called on double-click)
    pub fn on_reset(mut self, handler: impl Fn(&mut Window, &mut App) + 'static) -> Self {
        self.on_reset = Some(Rc::new(handler));
        self
    }

    /// Helper to snap a value to the step size
    /// Note: Currently unused, kept for potential future use
    #[allow(dead_code)]
    fn snap_value(&self, value: f32) -> f32 {
        if let Some(step) = self.step {
            let steps = ((value - self.min) / step).round();
            (self.min + steps * step).clamp(self.min, self.max)
        } else {
            value.clamp(self.min, self.max)
        }
    }

    fn clamped_value(&self) -> f32 {
        self.value.clamp(self.min, self.max)
    }

    fn interaction_config(&self) -> InteractionConfig {
        InteractionConfig::horizontal(self.min as f64, self.max as f64, Scale::Linear, self.width)
    }

    fn clone_for_calculation(&self) -> Self {
        Self {
            id: self.id.clone(),
            value: self.value,
            min: self.min,
            max: self.max,
            step: self.step,
            size: self.size,
            disabled: self.disabled,
            show_value: self.show_value,
            label: self.label.clone(),
            width: self.width,
            on_change: None,
            on_drag_start: None,
            on_reset: None,
            track_color: self.track_color,
            fill_color: self.fill_color,
            thumb_color: self.thumb_color,
            theme: self.theme.clone(),
            design: self.design.clone(),
            aria_label: self.aria_label.clone(),
            aria_role: self.aria_role,
        }
    }

    /// Set the track color
    pub fn track_color(mut self, color: impl Into<Rgba>) -> Self {
        self.track_color = Some(color.into());
        self
    }

    /// Set the fill color
    pub fn fill_color(mut self, color: impl Into<Rgba>) -> Self {
        self.fill_color = Some(color.into());
        self
    }

    /// Set the thumb color
    pub fn thumb_color(mut self, color: impl Into<Rgba>) -> Self {
        self.thumb_color = Some(color.into());
        self
    }

    /// Set the slider theme (applies all colors at once)
    pub fn theme(mut self, theme: SliderTheme) -> Self {
        self.theme = Some(theme);
        self
    }

    /// Override the design system used for track and thumb sizing.
    pub fn design(mut self, design: impl Into<Arc<DesignSystem>>) -> Self {
        self.design = Some(design.into());
        self
    }
}

impl RenderOnce for Slider {
    fn render(mut self, _window: &mut Window, cx: &mut App) -> impl IntoElement {
        self.value = self.clamped_value();

        let design = crate::design::resolve_design(self.design.clone(), cx);
        let track_height = self.size.track_height_with_design(&design);
        let thumb_size = self.size.thumb_size_with_design(&design);
        let width = self.width;

        let global_theme = cx.theme();
        let global_slider_theme = SliderTheme::from(global_theme.as_ref());
        let theme = self.theme.as_ref().unwrap_or(&global_slider_theme);
        let track_color = self.track_color.unwrap_or(theme.track);
        let fill_color = self.fill_color.unwrap_or(theme.fill);
        let thumb_color = self.thumb_color.unwrap_or(theme.thumb);
        let thumb_hover = theme.thumb_hover;
        let label_color = theme.label;
        let value_color = theme.value;
        let disabled_label = theme.disabled_label;
        let disabled_fill = theme.disabled_fill;

        let range = self.max - self.min;
        let progress = if range > 0.0 {
            (self.value - self.min) / range
        } else {
            0.0
        };

        let fill_width = (width * progress).max(0.0);
        let thumb_left = (width * progress) - (thumb_size / 2.0);
        let thumb_id = ElementId::from((self.id.clone(), "thumb"));
        let value_label = format!("{:.1}", self.value);

        let focus_handle = cx.focus_handle();
        let mut container = div().flex().flex_col().gap_1();

        if self.label.is_some() || self.show_value {
            let mut label_row = div().flex().justify_between().w(px(width)).text_sm();

            if let Some(label) = &self.label {
                label_row = label_row.child(
                    div()
                        .text_color(if self.disabled {
                            disabled_label
                        } else {
                            label_color
                        })
                        .child(label.clone()),
                );
            }

            if self.show_value {
                label_row = label_row.child(div().text_color(value_color).child(value_label));
            }

            container = container.child(label_row);
        }

        let mut track = div()
            .id(self.id.clone())
            .track_focus(&focus_handle)
            .focusable()
            .w(px(width))
            .h(px(thumb_size))
            .flex()
            .items_center()
            .relative()
            .child(
                div()
                    .absolute()
                    .left_0()
                    .w_full()
                    .h(px(track_height))
                    .rounded(px(track_height / 2.0))
                    .bg(track_color),
            )
            .child(
                div()
                    .absolute()
                    .left_0()
                    .w(px(fill_width))
                    .h(px(track_height))
                    .rounded(px(track_height / 2.0))
                    .bg(if self.disabled {
                        disabled_fill
                    } else {
                        fill_color
                    }),
            )
            .child({
                let mut thumb = div()
                    .id(thumb_id)
                    .absolute()
                    .left(px(thumb_left.max(0.0)))
                    .w(px(thumb_size))
                    .h(px(thumb_size))
                    .rounded_full()
                    .bg(thumb_color)
                    .border_2()
                    .border_color(if self.disabled {
                        disabled_fill
                    } else {
                        fill_color
                    })
                    .shadow_sm();
                if !self.disabled {
                    thumb = thumb.hover(|s| s.bg(thumb_hover));
                }
                thumb
            });

        if self.disabled {
            track = track.cursor_not_allowed();
        } else {
            track = track.cursor_ew_resize();
        }

        if !self.disabled {
            let id_down = self.id.clone();
            let id_move = self.id.clone();
            let id_up = self.id.clone();
            let value_at_press = self.value;
            let config_drag = self.interaction_config();
            let config_scroll = self.interaction_config();
            let config_key = self.interaction_config();
            let on_change_down = self.on_change.clone();
            let on_change_drag = self.on_change.clone();
            let on_change_scroll = self.on_change.clone();
            let on_change_key = self.on_change.clone();
            let on_drag_start = self.on_drag_start.clone();
            let on_reset = self.on_reset.clone();
            let snap_slider = Slider {
                on_change: None,
                on_drag_start: None,
                on_reset: None,
                ..self.clone_for_calculation()
            };
            let snap_drag = snap_slider.clone_for_calculation();
            let snap_scroll = snap_slider.clone_for_calculation();
            let snap_key = snap_slider.clone_for_calculation();
            let focus_down = focus_handle.clone();
            let focus_hover = focus_handle.clone();

            track = track
                .on_mouse_down(MouseButton::Left, move |event, window, cx| {
                    cx.stop_propagation();
                    focus_down.focus(window, cx);
                    let click_x: f32 = event.position.x.into();

                    if let Some(ref handler) = on_drag_start {
                        handler(click_x, value_at_press, window, cx);
                    }

                    if on_change_down.is_some() {
                        store_drag_state(id_down.clone(), click_x, value_at_press as f64);
                    }
                })
                .on_mouse_move(move |event: &MouseMoveEvent, window: &mut Window, cx| {
                    if !focus_hover.is_focused(window) && event.pressed_button.is_none() {
                        focus_hover.focus(window, cx);
                    }

                    if event.pressed_button != Some(MouseButton::Left) {
                        return;
                    }

                    let Some(state) = get_drag_state(&id_move) else {
                        return;
                    };
                    let current_x: f32 = event.position.x.into();
                    if let Some(value) = handle_drag(current_x, &state, &config_drag)
                        && let Some(ref handler) = on_change_drag
                    {
                        cx.stop_propagation();
                        handler(snap_drag.snap_value(value as f32), window, cx);
                    }
                })
                .on_mouse_up(MouseButton::Left, move |_event, _window, cx| {
                    clear_drag_state(id_up.clone());
                    cx.stop_propagation();
                })
                .on_scroll_wheel(move |event, window, cx| {
                    cx.stop_propagation();
                    if let Some(value) = handle_scroll(
                        &event.delta,
                        &event.modifiers,
                        value_at_press as f64,
                        &config_scroll,
                    ) && let Some(ref handler) = on_change_scroll
                    {
                        handler(snap_scroll.snap_value(value as f32), window, cx);
                    }
                })
                .on_key_down(move |event, window, cx| {
                    if let Some(value) = handle_keyboard(
                        event.keystroke.key.as_str(),
                        &event.keystroke.modifiers,
                        value_at_press as f64,
                        &config_key,
                    ) && let Some(ref handler) = on_change_key
                    {
                        cx.stop_propagation();
                        handler(snap_key.snap_value(value as f32), window, cx);
                    }
                });

            if let Some(reset_handler) = on_reset {
                track = track.on_click(move |event, window, cx| {
                    if event.click_count() == 2 {
                        reset_handler(window, cx);
                    }
                });
            }
        }

        container.child(track)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn value_before_range_uses_the_configured_range() {
        let slider = Slider::new("frequency").value(1000.0).range(20.0, 20_000.0);

        assert_eq!(slider.clamped_value(), 1000.0);
    }

    #[test]
    fn value_is_clamped_after_all_builder_options_are_applied() {
        let slider = Slider::new("frequency").value(10.0).range(20.0, 20_000.0);

        assert_eq!(slider.clamped_value(), 20.0);
    }
}
