//! Theme system for gpui-ui-kit
//!
//! Provides a unified theming system with light and dark themes.
//!
//! # Color Token Integration
//!
//! The theme system integrates with [`ColorToken`]
//! for automatic generation of hover, active, muted, and subtle color variants:
//!
//! ```ignore
//! let theme = cx.theme();
//!
//! // Get a ColorToken for the accent color with auto-generated variants
//! let accent = theme.accent_token();
//!
//! div()
//!     .bg(accent.base)
//!     .hover(|s| s.bg(accent.hover))
//!     .active(|s| s.bg(accent.active))
//! ```

use crate::color_tokens::{
    BackgroundColors, BorderColors, ColorPalette, ColorToken, SemanticColors, TextColors,
};
use gpui::{Rgba, SharedString, rgb, rgba};

mod misc;
mod theme_ext;
mod theme_state;
mod theme_variant;

pub use misc::glow_shadow;
pub use theme_ext::ThemeExt;
pub use theme_state::ThemeState;
pub use theme_variant::ThemeVariant;
/// Global theme colors
#[derive(Debug, Clone)]
pub struct Theme {
    /// Theme variant
    pub variant: ThemeVariant,

    // Background colors
    /// Main background color
    pub background: Rgba,
    /// Elevated surface background (cards, dialogs)
    pub surface: Rgba,
    /// Surface on hover
    pub surface_hover: Rgba,
    /// Muted background for secondary elements
    pub muted: Rgba,
    /// Transparent color (for invisible backgrounds)
    pub transparent: Rgba,
    /// Overlay/backdrop color (semi-transparent for modals/dialogs)
    pub overlay_bg: Rgba,

    // Text colors
    /// Primary text color
    pub text_primary: Rgba,
    /// Secondary/muted text color
    pub text_secondary: Rgba,
    /// Disabled text color
    pub text_muted: Rgba,
    /// Text color for content on accent-colored backgrounds
    pub text_on_accent: Rgba,
    /// Icon color for content on accent-colored backgrounds
    pub icon_on_accent: Rgba,

    // Accent colors
    /// Primary accent color
    pub accent: Rgba,
    /// Accent on hover
    pub accent_hover: Rgba,
    /// Muted accent for backgrounds
    pub accent_muted: Rgba,

    // Semantic colors
    /// Success color
    pub success: Rgba,
    /// Warning color
    pub warning: Rgba,
    /// Error color
    pub error: Rgba,
    /// Info color
    pub info: Rgba,

    // Border colors
    /// Default border
    pub border: Rgba,
    /// Border on hover/focus
    pub border_hover: Rgba,

    // Typography
    /// Default font family
    pub font_family: SharedString,

    // Badge colors
    /// Badge primary background
    pub badge_primary_bg: Rgba,
    /// Badge primary text
    pub badge_primary_text: Rgba,
    /// Badge success background
    pub badge_success_bg: Rgba,
    /// Badge success text
    pub badge_success_text: Rgba,
    /// Badge warning background
    pub badge_warning_bg: Rgba,
    /// Badge warning text
    pub badge_warning_text: Rgba,
    /// Badge error background
    pub badge_error_bg: Rgba,
    /// Badge error text
    pub badge_error_text: Rgba,
    /// Badge info background
    pub badge_info_bg: Rgba,
    /// Badge info text
    pub badge_info_text: Rgba,

    // Alert/Toast variant background colors
    /// Alert info background
    pub alert_info_bg: Rgba,
    /// Alert success background
    pub alert_success_bg: Rgba,
    /// Alert warning background
    pub alert_warning_bg: Rgba,
    /// Alert error background
    pub alert_error_bg: Rgba,

    // Code text color
    /// Code/monospace text color
    pub code_text: Rgba,
}

impl Theme {
    /// Names of every color field on [`Theme`].
    ///
    /// Single source of truth for the theme-coverage gate
    /// (`tests/theme_coverage.rs`): every entry must appear in at least one
    /// component theme's `THEME_SOURCES` (generated by `ComponentTheme`) or
    /// in the test's documented exception list. `variant` and `font_family`
    /// are intentionally excluded — they are not colors and cannot be
    /// consumed via `from = ...`.
    ///
    /// When adding a color field, add its name here; the exhaustive struct
    /// literal in the coverage test will fail to compile until the field is
    /// triaged there too.
    pub const FIELD_NAMES: &'static [&'static str] = &[
        "background",
        "surface",
        "surface_hover",
        "muted",
        "transparent",
        "overlay_bg",
        "text_primary",
        "text_secondary",
        "text_muted",
        "text_on_accent",
        "icon_on_accent",
        "accent",
        "accent_hover",
        "accent_muted",
        "success",
        "warning",
        "error",
        "info",
        "border",
        "border_hover",
        "badge_primary_bg",
        "badge_primary_text",
        "badge_success_bg",
        "badge_success_text",
        "badge_warning_bg",
        "badge_warning_text",
        "badge_error_bg",
        "badge_error_text",
        "badge_info_bg",
        "badge_info_text",
        "alert_info_bg",
        "alert_success_bg",
        "alert_warning_bg",
        "alert_error_bg",
        "code_text",
    ];

    /// Create a dark theme
    pub fn dark() -> Self {
        Self {
            variant: ThemeVariant::Dark,
            // Backgrounds
            background: rgb(0x1e1e1e),
            surface: rgb(0x2a2a2a),
            surface_hover: rgb(0x3a3a3a),
            muted: rgb(0x252525),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000088),
            // Text
            text_primary: rgb(0xffffff),
            text_secondary: rgb(0xcccccc),
            text_muted: rgb(0x9c9c9c),
            text_on_accent: rgb(0xffffff),
            icon_on_accent: rgb(0x1e1e1e),
            // Accent
            accent: rgb(0x007acc),
            accent_hover: rgb(0x0098ff),
            accent_muted: rgba(0x007acc33),
            // Semantic
            success: rgb(0x22c55e),
            warning: rgb(0xf59e0b),
            error: rgb(0xf87171),
            info: rgb(0x3b82f6),
            // Border
            border: rgb(0x3a3a3a),
            border_hover: rgb(0x555555),
            // Typography
            font_family: ".SystemUI".into(),
            // Badge colors (dark theme)
            badge_primary_bg: rgb(0x1a4a7a),
            badge_primary_text: rgb(0x7cc4ff),
            badge_success_bg: rgb(0x1a3a1a),
            badge_success_text: rgb(0x7ccc7c),
            badge_warning_bg: rgb(0x3a3a1a),
            badge_warning_text: rgb(0xcccc7c),
            badge_error_bg: rgb(0x3a1a1a),
            badge_error_text: rgb(0xcc7c7c),
            badge_info_bg: rgb(0x1a3a3a),
            badge_info_text: rgb(0x7ccccc),
            // Alert backgrounds
            alert_info_bg: rgb(0x1a2a3a),
            alert_success_bg: rgb(0x1a3a1a),
            alert_warning_bg: rgb(0x3a3a1a),
            alert_error_bg: rgb(0x3a1a1a),
            // Code text
            code_text: rgb(0xe06c75),
        }
    }

    /// Create a light theme
    pub fn light() -> Self {
        Self {
            variant: ThemeVariant::Light,
            // Backgrounds
            background: rgb(0xf5f5f5),
            surface: rgb(0xffffff),
            surface_hover: rgb(0xf0f0f0),
            muted: rgb(0xeeeeee),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000088),
            // Text
            text_primary: rgb(0x1a1a1a),
            text_secondary: rgb(0x4a4a4a),
            text_muted: rgb(0x666666),
            text_on_accent: rgb(0xffffff),
            icon_on_accent: rgb(0x1a1a1a),
            // Accent
            accent: rgb(0x0066cc),
            accent_hover: rgb(0x0055aa),
            accent_muted: rgba(0x0066cc22),
            // Semantic
            success: rgb(0x15803d),
            warning: rgb(0xb45309),
            error: rgb(0xb91c1c),
            info: rgb(0x1d4ed8),
            // Border
            border: rgb(0xd4d4d4),
            border_hover: rgb(0xaaaaaa),
            // Typography
            font_family: ".SystemUI".into(),
            // Badge colors (light theme)
            badge_primary_bg: rgb(0xdbeafe),
            badge_primary_text: rgb(0x1d4ed8),
            badge_success_bg: rgb(0xdcfce7),
            badge_success_text: rgb(0x16a34a),
            badge_warning_bg: rgb(0xfef3c7),
            badge_warning_text: rgb(0xd97706),
            badge_error_bg: rgb(0xfee2e2),
            badge_error_text: rgb(0xdc2626),
            badge_info_bg: rgb(0xe0f2fe),
            badge_info_text: rgb(0x0284c7),
            // Alert backgrounds
            alert_info_bg: rgb(0xe0f2fe),
            alert_success_bg: rgb(0xdcfce7),
            alert_warning_bg: rgb(0xfef3c7),
            alert_error_bg: rgb(0xfee2e2),
            // Code text
            code_text: rgb(0xc7254e),
        }
    }

    /// Create a midnight theme (deep blue)
    pub fn midnight() -> Self {
        Self {
            variant: ThemeVariant::Midnight,
            // Backgrounds
            background: rgb(0x0d1117),
            surface: rgb(0x21262d),
            surface_hover: rgb(0x30363d),
            muted: rgb(0x161b22),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000088),
            // Text
            text_primary: rgb(0xc9d1d9),
            text_secondary: rgb(0x8b949e),
            text_muted: rgb(0x8b949e),
            text_on_accent: rgb(0x0d1117),
            icon_on_accent: rgb(0x0d1117),
            // Accent
            accent: rgb(0x58a6ff),
            accent_hover: rgb(0x79b8ff),
            accent_muted: rgba(0x1f6feb33),
            // Semantic
            success: rgb(0x3fb950),
            warning: rgb(0xd29922),
            error: rgb(0xf85149),
            info: rgb(0x58a6ff),
            // Border
            border: rgb(0x30363d),
            border_hover: rgb(0x484f58),
            // Typography
            font_family: ".SystemUI".into(),
            // Badge colors (dark variant)
            badge_primary_bg: rgb(0x1a4a7a),
            badge_primary_text: rgb(0x7cc4ff),
            badge_success_bg: rgb(0x1a3a1a),
            badge_success_text: rgb(0x7ccc7c),
            badge_warning_bg: rgb(0x3a3a1a),
            badge_warning_text: rgb(0xcccc7c),
            badge_error_bg: rgb(0x3a1a1a),
            badge_error_text: rgb(0xcc7c7c),
            badge_info_bg: rgb(0x1a3a3a),
            badge_info_text: rgb(0x7ccccc),
            alert_info_bg: rgb(0x1a2a3a),
            alert_success_bg: rgb(0x1a3a1a),
            alert_warning_bg: rgb(0x3a3a1a),
            alert_error_bg: rgb(0x3a1a1a),
            code_text: rgb(0xe06c75),
        }
    }

    /// Create a forest theme (green tones)
    pub fn forest() -> Self {
        Self {
            variant: ThemeVariant::Forest,
            // Backgrounds
            background: rgb(0x1a2418),
            surface: rgb(0x2a3627),
            surface_hover: rgb(0x3a4a35),
            muted: rgb(0x222d1f),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000088),
            // Text
            text_primary: rgb(0xd4e4d1),
            text_secondary: rgb(0xa8c4a2),
            text_muted: rgb(0x91ad8a),
            text_on_accent: rgb(0x1a2418),
            icon_on_accent: rgb(0x1a2418),
            // Accent
            accent: rgb(0x6abf69),
            accent_hover: rgb(0x7dd07c),
            accent_muted: rgba(0x3d5a3a33),
            // Semantic
            success: rgb(0x6abf69),
            warning: rgb(0xe0c062),
            error: rgb(0xf08585),
            info: rgb(0x6cb2d9),
            // Border
            border: rgb(0x3a4a35),
            border_hover: rgb(0x556b50),
            // Typography
            font_family: ".SystemUI".into(),
            // Badge colors (dark variant)
            badge_primary_bg: rgb(0x1a4a7a),
            badge_primary_text: rgb(0x7cc4ff),
            badge_success_bg: rgb(0x1a3a1a),
            badge_success_text: rgb(0x7ccc7c),
            badge_warning_bg: rgb(0x3a3a1a),
            badge_warning_text: rgb(0xcccc7c),
            badge_error_bg: rgb(0x3a1a1a),
            badge_error_text: rgb(0xcc7c7c),
            badge_info_bg: rgb(0x1a3a3a),
            badge_info_text: rgb(0x7ccccc),
            alert_info_bg: rgb(0x1a2a3a),
            alert_success_bg: rgb(0x1a3a1a),
            alert_warning_bg: rgb(0x3a3a1a),
            alert_error_bg: rgb(0x3a1a1a),
            code_text: rgb(0xe06c75),
        }
    }

    /// Create a black & white theme (monochrome high contrast)
    pub fn black_and_white() -> Self {
        Self {
            variant: ThemeVariant::BlackAndWhite,
            // Backgrounds
            background: rgb(0x000000),
            surface: rgb(0x141414),
            surface_hover: rgb(0x222222),
            muted: rgb(0x0a0a0a),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000088),
            // Text
            text_primary: rgb(0xffffff),
            text_secondary: rgb(0xbbbbbb),
            text_muted: rgb(0x999999),
            text_on_accent: rgb(0x000000),
            icon_on_accent: rgb(0x000000),
            // Accent (white for high contrast on black background)
            accent: rgb(0xffffff),
            accent_hover: rgb(0xcccccc),
            accent_muted: rgba(0xffffff33),
            // Semantic (grayscale for B&W theme)
            success: rgb(0xaaaaaa),
            warning: rgb(0x888888),
            error: rgb(0x666666),
            info: rgb(0x999999),
            // Border (white for high contrast)
            border: rgb(0xffffff),
            border_hover: rgb(0xcccccc),
            // Typography
            font_family: "B612".into(),
            // Badge colors (dark variant)
            badge_primary_bg: rgb(0x1a4a7a),
            badge_primary_text: rgb(0x7cc4ff),
            badge_success_bg: rgb(0x1a3a1a),
            badge_success_text: rgb(0x7ccc7c),
            badge_warning_bg: rgb(0x3a3a1a),
            badge_warning_text: rgb(0xcccc7c),
            badge_error_bg: rgb(0x3a1a1a),
            badge_error_text: rgb(0xcc7c7c),
            badge_info_bg: rgb(0x1a3a3a),
            badge_info_text: rgb(0x7ccccc),
            alert_info_bg: rgb(0x1a2a3a),
            alert_success_bg: rgb(0x1a3a1a),
            alert_warning_bg: rgb(0x3a3a1a),
            alert_error_bg: rgb(0x3a1a1a),
            code_text: rgb(0xe06c75),
        }
    }

    /// Onyx theme (near-black with warm amber/gold accent)
    pub fn onyx() -> Self {
        Self {
            variant: ThemeVariant::Onyx,
            // Backgrounds
            background: rgb(0x0c0c0e),
            surface: rgb(0x1a1a1e),
            surface_hover: rgb(0x242428),
            muted: rgb(0x111114),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x000000a6),
            // Text
            text_primary: rgb(0xfafaf9),
            text_secondary: rgb(0xd6d3d1),
            text_muted: rgb(0xa8a29e),
            text_on_accent: rgb(0x0c0c0e),
            icon_on_accent: rgb(0x0c0c0e),
            // Accent (amber/gold)
            accent: rgb(0xf59e0b),
            accent_hover: rgb(0xfbbf24),
            accent_muted: rgba(0x78350f33),
            // Semantic
            success: rgb(0x4ade80),
            warning: rgb(0xfb923c),
            error: rgb(0xef4444),
            info: rgb(0x38bdf8),
            // Border
            border: rgb(0x2a2a2e),
            border_hover: rgb(0xf59e0b),
            // Typography
            font_family: "B612".into(),
            // Badge colors
            badge_primary_bg: rgb(0x451a03),
            badge_primary_text: rgb(0xfbbf24),
            badge_success_bg: rgb(0x14532d),
            badge_success_text: rgb(0x4ade80),
            badge_warning_bg: rgb(0x451a03),
            badge_warning_text: rgb(0xfb923c),
            badge_error_bg: rgb(0x450a0a),
            badge_error_text: rgb(0xef4444),
            badge_info_bg: rgb(0x0c2d48),
            badge_info_text: rgb(0x38bdf8),
            alert_info_bg: rgb(0x1a1a2a),
            alert_success_bg: rgb(0x14532d),
            alert_warning_bg: rgb(0x451a03),
            alert_error_bg: rgb(0x450a0a),
            code_text: rgb(0xe06c75),
        }
    }

    /// Carbon White theme.
    pub fn carbon_white() -> Self {
        Self {
            variant: ThemeVariant::CarbonWhite,
            background: rgb(0xffffff),
            surface: rgb(0xf4f4f4),
            surface_hover: rgb(0xe8e8e8),
            muted: rgb(0xe0e0e0),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000066),
            text_primary: rgb(0x161616),
            text_secondary: rgb(0x525252),
            text_muted: rgb(0xa8a8a8),
            text_on_accent: rgb(0xffffff),
            icon_on_accent: rgb(0xffffff),
            accent: rgb(0x0f62fe),
            accent_hover: rgb(0x0353e9),
            accent_muted: rgb(0xd0e2ff),
            success: rgb(0x24a148),
            warning: rgb(0xf1c21b),
            error: rgb(0xda1e28),
            info: rgb(0x0043ce),
            border: rgb(0xe0e0e0),
            border_hover: rgb(0x8d8d8d),
            font_family: "IBM Plex Sans".into(),
            badge_primary_bg: rgb(0xd0e2ff),
            badge_primary_text: rgb(0x0043ce),
            badge_success_bg: rgb(0xdefbe6),
            badge_success_text: rgb(0x0e6027),
            badge_warning_bg: rgb(0xfcf4d6),
            badge_warning_text: rgb(0x684e00),
            badge_error_bg: rgb(0xffd7d9),
            badge_error_text: rgb(0xa2191f),
            badge_info_bg: rgb(0xd0e2ff),
            badge_info_text: rgb(0x0043ce),
            alert_info_bg: rgb(0xedf5ff),
            alert_success_bg: rgb(0xdefbe6),
            alert_warning_bg: rgb(0xfcf4d6),
            alert_error_bg: rgb(0xffd7d9),
            code_text: rgb(0xa56eff),
        }
    }

    /// Carbon Gray 10 theme.
    pub fn carbon_gray10() -> Self {
        Self {
            variant: ThemeVariant::CarbonGray10,
            background: rgb(0xf4f4f4),
            surface: rgb(0xffffff),
            surface_hover: rgb(0xe8e8e8),
            muted: rgb(0xe0e0e0),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000066),
            text_primary: rgb(0x161616),
            text_secondary: rgb(0x525252),
            text_muted: rgb(0xa8a8a8),
            text_on_accent: rgb(0xffffff),
            icon_on_accent: rgb(0xffffff),
            accent: rgb(0x0f62fe),
            accent_hover: rgb(0x0353e9),
            accent_muted: rgb(0xd0e2ff),
            success: rgb(0x24a148),
            warning: rgb(0xf1c21b),
            error: rgb(0xda1e28),
            info: rgb(0x0043ce),
            border: rgb(0xe0e0e0),
            border_hover: rgb(0x8d8d8d),
            font_family: "IBM Plex Sans".into(),
            badge_primary_bg: rgb(0xd0e2ff),
            badge_primary_text: rgb(0x0043ce),
            badge_success_bg: rgb(0xdefbe6),
            badge_success_text: rgb(0x0e6027),
            badge_warning_bg: rgb(0xfcf4d6),
            badge_warning_text: rgb(0x684e00),
            badge_error_bg: rgb(0xffd7d9),
            badge_error_text: rgb(0xa2191f),
            badge_info_bg: rgb(0xd0e2ff),
            badge_info_text: rgb(0x0043ce),
            alert_info_bg: rgb(0xedf5ff),
            alert_success_bg: rgb(0xdefbe6),
            alert_warning_bg: rgb(0xfcf4d6),
            alert_error_bg: rgb(0xffd7d9),
            code_text: rgb(0xa56eff),
        }
    }

    /// Carbon Gray 90 theme.
    pub fn carbon_gray90() -> Self {
        Self {
            variant: ThemeVariant::CarbonGray90,
            background: rgb(0x262626),
            surface: rgb(0x393939),
            surface_hover: rgb(0x474747),
            muted: rgb(0x525252),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000099),
            text_primary: rgb(0xf4f4f4),
            text_secondary: rgb(0xc6c6c6),
            text_muted: rgb(0x6f6f6f),
            text_on_accent: rgb(0xffffff),
            icon_on_accent: rgb(0xffffff),
            accent: rgb(0x4589ff),
            accent_hover: rgb(0x78a9ff),
            accent_muted: rgba(0x4589ff33),
            success: rgb(0x42be65),
            warning: rgb(0xf1c21b),
            error: rgb(0xff8389),
            info: rgb(0x4589ff),
            border: rgb(0x525252),
            border_hover: rgb(0xa8a8a8),
            font_family: "IBM Plex Sans".into(),
            badge_primary_bg: rgb(0x002d9c),
            badge_primary_text: rgb(0xa6c8ff),
            badge_success_bg: rgb(0x044317),
            badge_success_text: rgb(0x6fdc8c),
            badge_warning_bg: rgb(0x4d3800),
            badge_warning_text: rgb(0xfddc69),
            badge_error_bg: rgb(0x750e13),
            badge_error_text: rgb(0xffb3b8),
            badge_info_bg: rgb(0x002d9c),
            badge_info_text: rgb(0xa6c8ff),
            alert_info_bg: rgb(0x001d6c),
            alert_success_bg: rgb(0x044317),
            alert_warning_bg: rgb(0x4d3800),
            alert_error_bg: rgb(0x750e13),
            code_text: rgb(0xbe95ff),
        }
    }

    /// Carbon Gray 100 theme.
    pub fn carbon_gray100() -> Self {
        Self {
            variant: ThemeVariant::CarbonGray100,
            background: rgb(0x161616),
            surface: rgb(0x262626),
            surface_hover: rgb(0x333333),
            muted: rgb(0x393939),
            transparent: rgba(0x00000000),
            overlay_bg: rgba(0x00000099),
            text_primary: rgb(0xf4f4f4),
            text_secondary: rgb(0xc6c6c6),
            text_muted: rgb(0x6f6f6f),
            text_on_accent: rgb(0xffffff),
            icon_on_accent: rgb(0xffffff),
            accent: rgb(0x4589ff),
            accent_hover: rgb(0x78a9ff),
            accent_muted: rgba(0x4589ff33),
            success: rgb(0x42be65),
            warning: rgb(0xf1c21b),
            error: rgb(0xff8389),
            info: rgb(0x4589ff),
            border: rgb(0x393939),
            border_hover: rgb(0xa8a8a8),
            font_family: "IBM Plex Sans".into(),
            badge_primary_bg: rgb(0x002d9c),
            badge_primary_text: rgb(0xa6c8ff),
            badge_success_bg: rgb(0x044317),
            badge_success_text: rgb(0x6fdc8c),
            badge_warning_bg: rgb(0x4d3800),
            badge_warning_text: rgb(0xfddc69),
            badge_error_bg: rgb(0x750e13),
            badge_error_text: rgb(0xffb3b8),
            badge_info_bg: rgb(0x002d9c),
            badge_info_text: rgb(0xa6c8ff),
            alert_info_bg: rgb(0x001d6c),
            alert_success_bg: rgb(0x044317),
            alert_warning_bg: rgb(0x4d3800),
            alert_error_bg: rgb(0x750e13),
            code_text: rgb(0xbe95ff),
        }
    }

    /// Get theme for variant
    pub fn for_variant(variant: ThemeVariant) -> Self {
        match variant {
            ThemeVariant::Dark => Self::dark(),
            ThemeVariant::Light => Self::light(),
            ThemeVariant::Midnight => Self::midnight(),
            ThemeVariant::Forest => Self::forest(),
            ThemeVariant::BlackAndWhite => Self::black_and_white(),
            ThemeVariant::Onyx => Self::onyx(),
            ThemeVariant::CarbonWhite => Self::carbon_white(),
            ThemeVariant::CarbonGray10 => Self::carbon_gray10(),
            ThemeVariant::CarbonGray90 => Self::carbon_gray90(),
            ThemeVariant::CarbonGray100 => Self::carbon_gray100(),
        }
    }

    // =========================================================================
    // Color Token Accessors
    // =========================================================================

    /// Get a ColorToken for the accent color with auto-generated variants
    ///
    /// Returns a token with base, hover, active, muted, and subtle variants.
    pub fn accent_token(&self) -> ColorToken {
        ColorToken::from_base(self.accent)
    }

    /// Get a ColorToken for the success color
    pub fn success_token(&self) -> ColorToken {
        ColorToken::from_base(self.success)
    }

    /// Get a ColorToken for the warning color
    pub fn warning_token(&self) -> ColorToken {
        ColorToken::from_base(self.warning)
    }

    /// Get a ColorToken for the error color
    pub fn error_token(&self) -> ColorToken {
        ColorToken::from_base(self.error)
    }

    /// Get a ColorToken for the info color
    pub fn info_token(&self) -> ColorToken {
        ColorToken::from_base(self.info)
    }

    /// Get a ColorToken for the surface color
    pub fn surface_token(&self) -> ColorToken {
        ColorToken::from_base(self.surface)
    }

    /// Get a ColorToken for the primary text color
    pub fn text_primary_token(&self) -> ColorToken {
        ColorToken::from_base(self.text_primary)
    }

    /// Get a ColorToken for the border color
    pub fn border_token(&self) -> ColorToken {
        ColorToken::from_base(self.border)
    }

    /// Convert the theme to a full ColorPalette
    ///
    /// This is useful when you need structured access to all color tokens.
    pub fn to_palette(&self) -> ColorPalette {
        ColorPalette {
            semantic: SemanticColors {
                primary: self.accent_token(),
                secondary: ColorToken::from_base(self.text_secondary),
                success: self.success_token(),
                warning: self.warning_token(),
                error: self.error_token(),
                info: self.info_token(),
            },
            backgrounds: BackgroundColors {
                page: ColorToken::from_base(self.background),
                surface: self.surface_token(),
                overlay: ColorToken::from_base(self.overlay_bg),
            },
            text: TextColors {
                primary: self.text_primary_token(),
                secondary: ColorToken::from_base(self.text_secondary),
                muted: ColorToken::from_base(self.text_muted),
                inverted: ColorToken::from_base(
                    if matches!(
                        self.variant,
                        ThemeVariant::Light
                            | ThemeVariant::CarbonWhite
                            | ThemeVariant::CarbonGray10
                    ) {
                        rgb(0xffffff)
                    } else {
                        rgb(0x1a1a1a)
                    },
                ),
            },
            borders: BorderColors {
                default: self.border_token(),
                focus: self.accent_token(),
                error: self.error_token(),
            },
        }
    }
}

impl Default for Theme {
    fn default() -> Self {
        Self::dark()
    }
}

#[cfg(test)]
mod tests;
