//! Release-note readiness metadata for toolkit crate publication.

/// Schema version for [`ReleaseNotesReport`].
pub const RELEASE_NOTES_SCHEMA_VERSION: u32 = 1;

/// Stable report type identifier for [`ReleaseNotesReport`].
pub const RELEASE_NOTES_REPORT_TYPE: &str = "gpui-toolkit-release-notes";

/// Stable report type identifier for [`ReleaseNotesArtifactReport`].
pub const RELEASE_NOTES_ARTIFACT_REPORT_TYPE: &str = "gpui-toolkit-release-note-artifacts";

/// Current release-note readiness for a crate or release lane.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReleaseNotesStatus {
    /// Release notes are sufficient for the current release decision.
    Ready,
    /// The crate still needs an artifact, changelog, screenshot, benchmark, or note.
    PendingArtifact,
    /// Release notes depend on a gate that has not passed yet.
    BlockedByReleaseGate,
    /// The crate/lane is intentionally excluded from this public release.
    Excluded,
}

impl ReleaseNotesStatus {
    /// Stable status label for generated reports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ready => "ready",
            Self::PendingArtifact => "pending-artifact",
            Self::BlockedByReleaseGate => "blocked-by-release-gate",
            Self::Excluded => "excluded",
        }
    }

    /// Whether this status is enough for an external release note claim.
    pub const fn is_release_ready(self) -> bool {
        matches!(self, Self::Ready | Self::Excluded)
    }
}

/// One release-note entry for a crate or release lane.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReleaseNotesEntry {
    /// Cargo package name or release lane id.
    pub crate_name: &'static str,
    /// Release lane.
    pub lane: &'static str,
    /// Current release-note readiness.
    pub status: ReleaseNotesStatus,
    /// Stability label that should appear in release notes.
    pub stability: &'static str,
    /// Platform support statement that should appear in release notes.
    pub platform_support: &'static str,
    /// Required sections/artifacts for this release note.
    pub required_sections: &'static str,
    /// Evidence recorded in this report.
    pub evidence: &'static str,
    /// Remaining requirement before release.
    pub release_requirement: &'static str,
}

/// Current availability for one release-note attachment or evidence artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReleaseNotesArtifactStatus {
    /// The artifact is generated by stable in-repo metadata APIs.
    Available,
    /// The artifact depends on running a local release command such as a dry-run.
    PendingCommand,
    /// The artifact requires external hardware, OS, or manual QA evidence.
    ExternalGate,
    /// The artifact is intentionally excluded from the public release.
    Excluded,
}

impl ReleaseNotesArtifactStatus {
    /// Stable status label for generated reports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Available => "available",
            Self::PendingCommand => "pending-command",
            Self::ExternalGate => "external-gate",
            Self::Excluded => "excluded",
        }
    }

    /// Whether this artifact still blocks final public release-note assembly.
    pub const fn is_blocking(self) -> bool {
        matches!(self, Self::PendingCommand | Self::ExternalGate)
    }
}

/// One release-note artifact or attachment source.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReleaseNotesArtifact {
    /// Stable artifact id.
    pub id: &'static str,
    /// Cargo package name or release lane id.
    pub crate_name: &'static str,
    /// Human-readable artifact name for release notes.
    pub artifact: &'static str,
    /// API, command, or path that produces the artifact.
    pub source: &'static str,
    /// Current artifact availability.
    pub status: ReleaseNotesArtifactStatus,
    /// Evidence recorded in this inventory.
    pub evidence: &'static str,
    /// Remaining requirement before final notes.
    pub release_requirement: &'static str,
}

/// Versioned release-note artifact inventory for changelog assembly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReleaseNotesArtifactReport {
    pub schema_version: u32,
    pub report_type: &'static str,
    pub reviewed_on: &'static str,
    pub artifacts: &'static [ReleaseNotesArtifact],
}

impl ReleaseNotesArtifactReport {
    /// Return artifacts for one crate or lane.
    pub fn artifacts_for(
        self,
        crate_name: &'static str,
    ) -> impl Iterator<Item = &'static ReleaseNotesArtifact> {
        self.artifacts
            .iter()
            .filter(move |artifact| artifact.crate_name == crate_name)
    }

    /// Return artifacts that still block final public release-note assembly.
    pub fn blocking_artifacts(self) -> impl Iterator<Item = &'static ReleaseNotesArtifact> {
        self.artifacts
            .iter()
            .filter(|artifact| artifact.status.is_blocking())
    }

    /// Render the artifact inventory as Markdown for release assembly.
    pub fn to_markdown_table(self) -> String {
        let mut markdown = format!(
            "# GPUI Toolkit Release Note Artifacts\n\n\
             - schema_version: {}\n\
             - report_type: `{}`\n\
             - reviewed_on: {}\n\n\
             | Crate or lane | Artifact | Source | Status | Evidence | Release requirement |\n\
             | --- | --- | --- | --- | --- | --- |\n",
            self.schema_version, self.report_type, self.reviewed_on
        );

        for artifact in self.artifacts {
            markdown.push_str(&format!(
                "| {} | {} | {} | {} | {} | {} |\n",
                artifact.crate_name,
                artifact.artifact,
                artifact.source,
                artifact.status.as_str(),
                artifact.evidence,
                artifact.release_requirement
            ));
        }

        markdown
    }
}

/// Versioned release-note readiness report.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReleaseNotesReport {
    pub schema_version: u32,
    pub report_type: &'static str,
    pub reviewed_on: &'static str,
    pub entries: &'static [ReleaseNotesEntry],
}

impl ReleaseNotesReport {
    /// Return true only when every release-note entry is release-ready.
    pub fn all_release_ready(self) -> bool {
        self.entries
            .iter()
            .all(|entry| entry.status.is_release_ready())
    }

    /// Return entries that still block release notes.
    pub fn blocking_entries(self) -> impl Iterator<Item = &'static ReleaseNotesEntry> {
        self.entries
            .iter()
            .filter(|entry| !entry.status.is_release_ready())
    }

    /// Render the report as Markdown for release artifacts.
    pub fn to_markdown_table(self) -> String {
        let mut markdown = format!(
            "# GPUI Toolkit Release Notes Readiness\n\n\
             - schema_version: {}\n\
             - report_type: `{}`\n\
             - reviewed_on: {}\n\n\
             | Crate or lane | Lane | Status | Stability | Platform support | Required sections | Evidence | Release requirement |\n\
             | --- | --- | --- | --- | --- | --- | --- | --- |\n",
            self.schema_version, self.report_type, self.reviewed_on
        );

        for entry in self.entries {
            markdown.push_str(&format!(
                "| {} | {} | {} | {} | {} | {} | {} | {} |\n",
                entry.crate_name,
                entry.lane,
                entry.status.as_str(),
                entry.stability,
                entry.platform_support,
                entry.required_sections,
                entry.evidence,
                entry.release_requirement
            ));
        }

        markdown
    }
}

const RELEASE_NOTES_ENTRIES: &[ReleaseNotesEntry] = &[
    ReleaseNotesEntry {
        crate_name: "gpui-design",
        lane: "public-core",
        status: ReleaseNotesStatus::Ready,
        stability: "release-candidate",
        platform_support: "all Rust targets; optional GPUI integration behind the gpui feature",
        required_sections: "stability, generated conformance artifact, known limitations, publish dry-run",
        evidence: "Design documentation report exists and crates.io publish dry-run passed cleanly.",
        release_requirement: "Attach generated conformance Markdown/screenshots to the final release notes.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-builder",
        lane: "public-core",
        status: ReleaseNotesStatus::BlockedByReleaseGate,
        stability: "release-candidate",
        platform_support: "all Rust targets supported by the layout solver",
        required_sections: "stability, diagnostics, benchmark policy, publish dry-run",
        evidence: "Diagnostics and benchmark coverage reports exist, but publish dry-run is blocked until predecessor crates are published.",
        release_requirement: "Re-run publish dry-run after gpui-design/gpui-pretext are available and attach benchmark estimates.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-ui-kit",
        lane: "public-core",
        status: ReleaseNotesStatus::PendingArtifact,
        stability: "release-candidate with keyboard/accessibility caveats",
        platform_support: "desktop GPUI first; mobile surfaces require simulator/device QA",
        required_sections: "stability, focus integration report, accessibility limitations, publish dry-run",
        evidence: "Focus integration report exists and records compound-widget/native-accessibility blockers.",
        release_requirement: "Resolve or explicitly release-note pending focus integration entries before publication.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-audio-kit",
        lane: "public-core",
        status: ReleaseNotesStatus::PendingArtifact,
        stability: "release-candidate",
        platform_support: "desktop GPUI controls; native accessibility bridge remains app-level",
        required_sections: "stability, audio-control accessibility summaries, visual QA, publish dry-run",
        evidence: "Audio accessibility summaries exist; visual QA and publish dry-run are not recorded.",
        release_requirement: "Attach dense-panel visual QA and run publish dry-run.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-pretext",
        lane: "public-core",
        status: ReleaseNotesStatus::PendingArtifact,
        stability: "release-candidate",
        platform_support: "all Rust targets; shaping/rendering remains caller/backend dependent",
        required_sections: "stability, language/script support report, locale limits, publish dry-run",
        evidence: "Language support, locale golden case, and benchmark-baseline reports exist; publish dry-run and platform comparator artifacts are not recorded.",
        release_requirement: "Attach language/locale/benchmark reports, record remaining platform text-rendering gaps, and run publish dry-run.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-keybinding",
        lane: "public-core",
        status: ReleaseNotesStatus::PendingArtifact,
        stability: "release-candidate",
        platform_support: "desktop keybinding presets for macOS, Windows, and Linux labels",
        required_sections: "stability, shortcut policy, conflict checks, publish dry-run",
        evidence: "Shortcut policy and conflict examples are documented; publish dry-run is not recorded.",
        release_requirement: "Run publish dry-run and include conflict-resolution policy in release notes.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-themes",
        lane: "public-core",
        status: ReleaseNotesStatus::PendingArtifact,
        stability: "release-candidate",
        platform_support: "theme JSON import/export across supported GPUI app targets",
        required_sections: "stability, schema version policy, compatibility test, publish dry-run",
        evidence: "Community theme schema/version policy is documented and v1 import compatibility is tested.",
        release_requirement: "Run publish dry-run and include schema compatibility policy in release notes.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-d3rs",
        lane: "beta-visualization",
        status: ReleaseNotesStatus::PendingArtifact,
        stability: "beta",
        platform_support: "algorithm modules are portable; GPUI/GPU rendering requires feature and runtime QA",
        required_sections: "beta limitations, feature/option parity reports, benchmark coverage, checked API notes, visual QA, publish dry-run",
        evidence: "Feature parity, D3 option parity, and benchmark coverage reports exist; checked input APIs and d3-time-format coverage are recorded, while visual/GPU QA and publish dry-run are not recorded.",
        release_requirement: "Attach parity and benchmark reports, record visual/GPU QA or keep the beta caveat explicit, and run publish dry-run if included.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-px",
        lane: "beta-visualization",
        status: ReleaseNotesStatus::PendingArtifact,
        stability: "beta",
        platform_support: "high-level chart specs; native screen-reader and interaction bridges remain app-level",
        required_sections: "beta limitations, chart capability report, accessibility summaries, interaction/static-export notes, visual QA, publish dry-run",
        evidence: "Chart capability, interaction QA, static SVG export, visual-regression inventory, and accessibility summary metadata exist; native accessibility bridge consumption, executed visual captures, and publish dry-run are not recorded.",
        release_requirement: "Attach chart capability/visual manifest artifacts, document native accessibility and non-SVG export limitations, and run visual/publish gates if included.",
    },
    ReleaseNotesEntry {
        crate_name: "gpui-toolkit",
        lane: "aggregate",
        status: ReleaseNotesStatus::Excluded,
        stability: "internal-only",
        platform_support: "aggregate feature surface only; constituent crates define actual support",
        required_sections: "exclusion rationale, aggregate feature boundary, future publish decision",
        evidence: "Aggregate crate remains publish-disabled with stability, QA, publish, dependency, and vendored reports.",
        release_requirement: "Keep unpublished until constituent crates pass gates and an explicit aggregate publish decision is made.",
    },
    ReleaseNotesEntry {
        crate_name: "platform/mobile/showcase lanes",
        lane: "internal-or-manual-qa",
        status: ReleaseNotesStatus::BlockedByReleaseGate,
        stability: "experimental/manual-qa",
        platform_support: "AU, iOS, Android, tvOS, Windows, and showcases require target/runtime validation",
        required_sections: "platform support matrix, manual QA evidence, known unsafe/native bridge risks",
        evidence: "Release QA matrix records pending/manual/blocked platform gates.",
        release_requirement: "Attach platform QA artifacts or keep these lanes out of the public release.",
    },
];

const RELEASE_NOTES_ARTIFACTS: &[ReleaseNotesArtifact] = &[
    ReleaseNotesArtifact {
        id: "gpui-design-documentation",
        crate_name: "gpui-design",
        artifact: "Design documentation and conformance report",
        source: "gpui_design::DesignDocumentationReport::for_all_presets()",
        status: ReleaseNotesArtifactStatus::Available,
        evidence: "Generated preset summaries and conformance matrix are available for release notes.",
        release_requirement: "Attach generated Markdown/JSON and screenshots when assembling final notes.",
    },
    ReleaseNotesArtifact {
        id: "gpui-builder-diagnostics-benchmarks",
        crate_name: "gpui-builder",
        artifact: "Layout diagnostics and benchmark coverage",
        source: "gpui_builder::{LayoutDebugReport, benchmark_report()}",
        status: ReleaseNotesArtifactStatus::Available,
        evidence: "Structured diagnostics and benchmark coverage reports are implemented.",
        release_requirement: "Attach benchmark run artifacts before claiming measured performance.",
    },
    ReleaseNotesArtifact {
        id: "gpui-ui-kit-focus-accessibility-visual",
        crate_name: "gpui-ui-kit",
        artifact: "Focus, accessibility, security, and visual manifests",
        source: "gpui_ui_kit::{focus_integration_report, accessibility_readiness_report, security_surface_report, ui_kit_visual_regression_manifest}",
        status: ReleaseNotesArtifactStatus::Available,
        evidence: "Stable metadata reports exist for component readiness and release screenshot inventory.",
        release_requirement: "Attach reports and keep native screen-reader adapter limitations explicit.",
    },
    ReleaseNotesArtifact {
        id: "gpui-audio-kit-control-artifacts",
        crate_name: "gpui-audio-kit",
        artifact: "Audio control accessibility, automation, and visual manifests",
        source: "gpui_audio_kit::{AudioAccessibilitySummary, audio_automation_pattern_report, audio_visual_regression_manifest}",
        status: ReleaseNotesArtifactStatus::Available,
        evidence: "Audio-control metadata and visual capture inventory are implemented.",
        release_requirement: "Attach reports and execute screenshot captures for final visual evidence.",
    },
    ReleaseNotesArtifact {
        id: "gpui-pretext-i18n-benchmarks",
        crate_name: "gpui-pretext",
        artifact: "Language support, locale golden cases, and benchmark baselines",
        source: "gpui_pretext::{language_support_report, locale_golden_report, benchmark_baseline_report}",
        status: ReleaseNotesArtifactStatus::Available,
        evidence: "Text i18n and benchmark-baseline metadata are implemented.",
        release_requirement: "Attach reports and keep platform text-renderer comparator artifacts as release-runner gates.",
    },
    ReleaseNotesArtifact {
        id: "gpui-d3rs-parity-benchmarks",
        crate_name: "gpui-d3rs",
        artifact: "D3 feature/option parity and large-dataset benchmark coverage",
        source: "d3rs::{feature_parity_report, d3_option_parity_report, d3_benchmark_coverage_report}",
        status: ReleaseNotesArtifactStatus::Available,
        evidence: "D3 feature parity, option parity, benchmark coverage, and time-format readiness are tracked in code.",
        release_requirement: "Attach reports and keep unexecuted visual/GPU QA as a beta limitation.",
    },
    ReleaseNotesArtifact {
        id: "gpui-px-chart-artifacts",
        crate_name: "gpui-px",
        artifact: "Chart capabilities, interaction QA, static SVG export, and visual manifest",
        source: "gpui_px::{chart_capability_report, interaction_qa_report, chart_visual_regression_manifest}",
        status: ReleaseNotesArtifactStatus::Available,
        evidence: "Chart metadata, interaction, static export, and visual inventory reports are implemented.",
        release_requirement: "Attach reports and keep native accessibility bridge and non-SVG export limitations explicit.",
    },
    ReleaseNotesArtifact {
        id: "public-core-dry-runs",
        crate_name: "public-core crates",
        artifact: "Crates.io publish dry-run outputs",
        source: "gpui_toolkit::publish_plan()",
        status: ReleaseNotesArtifactStatus::PendingCommand,
        evidence: "Publish plan records command order and predecessor blockers.",
        release_requirement: "Run and attach dry-run output in dependency order before publishing.",
    },
    ReleaseNotesArtifact {
        id: "platform-qa-artifacts",
        crate_name: "platform/mobile/showcase lanes",
        artifact: "Platform runtime, simulator/device, and showcase visual QA evidence",
        source: "gpui_toolkit::release_qa_matrix()",
        status: ReleaseNotesArtifactStatus::ExternalGate,
        evidence: "Release QA matrix records macOS, AU, iOS, Android, tvOS, Windows, and visual gates.",
        release_requirement: "Attach platform/device/manual QA artifacts or keep these lanes internal.",
    },
    ReleaseNotesArtifact {
        id: "aggregate-exclusion",
        crate_name: "gpui-toolkit",
        artifact: "Aggregate crate exclusion rationale",
        source: "gpui_toolkit::{crate_stability_manifest, release_packaging_report}",
        status: ReleaseNotesArtifactStatus::Excluded,
        evidence: "Aggregate crate is publish-disabled and documents feature/lane boundaries.",
        release_requirement: "Keep excluded until constituent crates pass release gates.",
    },
];

/// Return the current release-note readiness report.
pub const fn release_notes_report() -> ReleaseNotesReport {
    ReleaseNotesReport {
        schema_version: RELEASE_NOTES_SCHEMA_VERSION,
        report_type: RELEASE_NOTES_REPORT_TYPE,
        reviewed_on: "2026-07-08",
        entries: RELEASE_NOTES_ENTRIES,
    }
}

/// Return release-note readiness entries without allocating.
pub const fn release_notes_entries() -> &'static [ReleaseNotesEntry] {
    RELEASE_NOTES_ENTRIES
}

/// Return the release-note artifact inventory.
pub const fn release_notes_artifact_report() -> ReleaseNotesArtifactReport {
    ReleaseNotesArtifactReport {
        schema_version: RELEASE_NOTES_SCHEMA_VERSION,
        report_type: RELEASE_NOTES_ARTIFACT_REPORT_TYPE,
        reviewed_on: "2026-07-08",
        artifacts: RELEASE_NOTES_ARTIFACTS,
    }
}

/// Return release-note artifact rows without allocating.
pub const fn release_notes_artifacts() -> &'static [ReleaseNotesArtifact] {
    RELEASE_NOTES_ARTIFACTS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn release_notes_report_has_stable_contract() {
        let report = release_notes_report();

        assert_eq!(report.schema_version, RELEASE_NOTES_SCHEMA_VERSION);
        assert_eq!(report.report_type, RELEASE_NOTES_REPORT_TYPE);
        assert_eq!(report.reviewed_on, "2026-07-08");
        assert!(!report.entries.is_empty());
        assert!(!report.all_release_ready());
    }

    #[test]
    fn release_notes_report_has_unique_entry_names() {
        let mut names = std::collections::BTreeSet::new();

        for entry in release_notes_entries() {
            assert!(
                names.insert(entry.crate_name),
                "duplicate release notes entry {}",
                entry.crate_name
            );
            assert!(!entry.lane.is_empty());
            assert!(!entry.status.as_str().is_empty());
            assert!(!entry.stability.is_empty());
            assert!(!entry.platform_support.is_empty());
            assert!(!entry.required_sections.is_empty());
            assert!(!entry.evidence.is_empty());
            assert!(!entry.release_requirement.is_empty());
        }
    }

    #[test]
    fn release_notes_report_covers_selected_public_lanes() {
        let names = release_notes_entries()
            .iter()
            .map(|entry| entry.crate_name)
            .collect::<Vec<_>>();

        for expected in [
            "gpui-design",
            "gpui-builder",
            "gpui-ui-kit",
            "gpui-audio-kit",
            "gpui-pretext",
            "gpui-keybinding",
            "gpui-themes",
            "gpui-d3rs",
            "gpui-px",
            "gpui-toolkit",
        ] {
            assert!(
                names.contains(&expected),
                "missing release notes entry {expected}"
            );
        }
    }

    #[test]
    fn release_notes_report_blocks_until_required_artifacts_exist() {
        let blocking = release_notes_report()
            .blocking_entries()
            .map(|entry| entry.crate_name)
            .collect::<Vec<_>>();

        assert!(blocking.contains(&"gpui-builder"));
        assert!(blocking.contains(&"gpui-ui-kit"));
        assert!(blocking.contains(&"gpui-d3rs"));
        assert!(blocking.contains(&"platform/mobile/showcase lanes"));
    }

    #[test]
    fn release_notes_artifact_report_has_stable_contract() {
        let report = release_notes_artifact_report();

        assert_eq!(report.schema_version, RELEASE_NOTES_SCHEMA_VERSION);
        assert_eq!(report.report_type, RELEASE_NOTES_ARTIFACT_REPORT_TYPE);
        assert_eq!(report.reviewed_on, "2026-07-08");
        assert!(!report.artifacts.is_empty());
    }

    #[test]
    fn release_notes_artifact_report_has_unique_artifact_ids() {
        let mut ids = std::collections::BTreeSet::new();

        for artifact in release_notes_artifacts() {
            assert!(
                ids.insert(artifact.id),
                "duplicate release-note artifact {}",
                artifact.id
            );
            assert!(!artifact.crate_name.is_empty());
            assert!(!artifact.artifact.is_empty());
            assert!(!artifact.source.is_empty());
            assert!(!artifact.status.as_str().is_empty());
            assert!(!artifact.evidence.is_empty());
            assert!(!artifact.release_requirement.is_empty());
        }
    }

    #[test]
    fn release_notes_artifact_report_covers_visualization_artifacts() {
        let report = release_notes_artifact_report();
        let d3rs = report
            .artifacts_for("gpui-d3rs")
            .map(|artifact| artifact.source)
            .collect::<Vec<_>>();
        let px = report
            .artifacts_for("gpui-px")
            .map(|artifact| artifact.source)
            .collect::<Vec<_>>();

        assert!(d3rs
            .iter()
            .any(|source| source.contains("feature_parity_report")));
        assert!(d3rs
            .iter()
            .any(|source| source.contains("d3_benchmark_coverage_report")));
        assert!(px
            .iter()
            .any(|source| source.contains("chart_capability_report")));
        assert!(px
            .iter()
            .any(|source| source.contains("chart_visual_regression_manifest")));
    }

    #[test]
    fn release_notes_artifact_report_keeps_external_gates_blocking() {
        let blocking = release_notes_artifact_report()
            .blocking_artifacts()
            .map(|artifact| artifact.id)
            .collect::<Vec<_>>();

        assert!(blocking.contains(&"public-core-dry-runs"));
        assert!(blocking.contains(&"platform-qa-artifacts"));
        assert!(!blocking.contains(&"gpui-d3rs-parity-benchmarks"));
        assert!(!blocking.contains(&"gpui-px-chart-artifacts"));
    }

    #[test]
    fn release_notes_markdown_names_required_sections() {
        let markdown = release_notes_report().to_markdown_table();

        assert!(markdown.contains(RELEASE_NOTES_REPORT_TYPE));
        assert!(markdown.contains("focus integration report"));
        assert!(markdown.contains("feature/option parity reports"));
        assert!(markdown.contains("platform support matrix"));
        assert!(markdown.contains("publish dry-run"));
    }

    #[test]
    fn release_notes_artifact_markdown_names_sources() {
        let markdown = release_notes_artifact_report().to_markdown_table();

        assert!(markdown.contains(RELEASE_NOTES_ARTIFACT_REPORT_TYPE));
        assert!(markdown.contains("d3_benchmark_coverage_report"));
        assert!(markdown.contains("chart_visual_regression_manifest"));
        assert!(markdown.contains("release_qa_matrix"));
        assert!(markdown.contains("pending-command"));
    }
}
