// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use d3rs::shape::ScatterPoint;
use std::sync::Arc;

pub(super) type ScatterDataCache = Option<(Arc<[f64]>, Arc<[f64]>, Arc<[ScatterPoint]>)>;

/// A single series in a scatter chart
#[derive(Debug, Clone)]
pub(super) struct ScatterSeries {
    pub(super) x: Arc<[f64]>,
    pub(super) y: Arc<[f64]>,
    pub(super) label: Option<String>,
    pub(super) color: u32,
    pub(super) point_radius: f32,
    pub(super) opacity: f32,
    /// Cache of mapped points keyed by source `(x, y)` `Arc` pointer equality.
    pub(super) data_cache: ScatterDataCache,
}
