// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::types::IconFactory;
use gpui::prelude::IntoElement;
use gpui::{AnyElement, ElementId, Rgba, SharedString};

/// A single tab item
pub struct TabItem {
    pub(super) id: SharedString,
    pub(super) label: SharedString,
    pub(super) icon: Option<SharedString>,
    pub(super) custom_icon: Option<AnyElement>,
    /// Icon factory that creates the icon with the given color at render time
    pub(super) icon_factory: Option<IconFactory>,
    pub(super) badge: Option<SharedString>,
    pub(super) disabled: bool,
    pub(super) closeable: bool,
    /// Pre-computed stable element IDs so `render` does not format strings every frame.
    pub(super) tab_element_id: ElementId,
    pub(super) close_element_id: ElementId,
    pub(super) wrapper_element_id: ElementId,
}

impl TabItem {
    /// Create a new tab item
    pub fn new(id: impl Into<SharedString>, label: impl Into<SharedString>) -> Self {
        let id: SharedString = id.into();
        let tab_element_id = ElementId::Name(SharedString::from(format!("tab-{id}")));
        let close_element_id = ElementId::Name(SharedString::from(format!("tab-close-{id}")));
        let wrapper_element_id = ElementId::Name(SharedString::from(format!("tab-wrapper-{id}")));
        Self {
            id,
            label: label.into(),
            icon: None,
            custom_icon: None,
            icon_factory: None,
            badge: None,
            disabled: false,
            closeable: false,
            tab_element_id,
            close_element_id,
            wrapper_element_id,
        }
    }

    /// Add a text/emoji icon
    pub fn icon(mut self, icon: impl Into<SharedString>) -> Self {
        self.icon = Some(icon.into());
        self
    }

    /// Add a custom icon element (e.g., SVG)
    /// Note: If the icon needs to change color based on selection state,
    /// use `icon_with_color` instead.
    pub fn custom_icon(mut self, icon: impl IntoElement) -> Self {
        self.custom_icon = Some(icon.into_any_element());
        self
    }

    /// Add an icon that will be created with the correct color at render time.
    /// The factory function receives the icon color (based on selection state)
    /// and should return the icon element with that color applied.
    pub fn icon_with_color<F>(mut self, factory: F) -> Self
    where
        F: Fn(Rgba) -> AnyElement + 'static,
    {
        self.icon_factory = Some(Box::new(factory));
        self
    }

    /// Add a badge
    pub fn badge(mut self, badge: impl Into<SharedString>) -> Self {
        self.badge = Some(badge.into());
        self
    }

    /// Disable the tab
    pub fn disabled(mut self, disabled: bool) -> Self {
        self.disabled = disabled;
        self
    }

    /// Make the tab closeable
    pub fn closeable(mut self, closeable: bool) -> Self {
        self.closeable = closeable;
        self
    }

    /// Get the tab ID
    pub fn id(&self) -> &SharedString {
        &self.id
    }
}
