// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// Number input size variants
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum NumberInputSize {
    /// Extra small size
    Xs,
    /// Small size
    Sm,
    /// Medium size (default)
    #[default]
    Md,
    /// Large size
    Lg,
}

impl From<crate::ComponentSize> for NumberInputSize {
    fn from(size: crate::ComponentSize) -> Self {
        match size {
            crate::ComponentSize::Xs => Self::Xs,
            crate::ComponentSize::Sm => Self::Sm,
            crate::ComponentSize::Md => Self::Md,
            crate::ComponentSize::Lg | crate::ComponentSize::Xl => Self::Lg,
        }
    }
}

impl NumberInputSize {
    pub(super) fn height(&self) -> f32 {
        match self {
            Self::Xs => 20.0,
            Self::Sm => 24.0,
            Self::Md => 32.0,
            Self::Lg => 40.0,
        }
    }

    pub(super) fn button_width(&self) -> f32 {
        match self {
            Self::Xs => 16.0,
            Self::Sm => 20.0,
            Self::Md => 28.0,
            Self::Lg => 36.0,
        }
    }

    pub(super) fn font_size(&self) -> f32 {
        match self {
            Self::Xs => 10.0,
            Self::Sm => 11.0,
            Self::Md => 13.0,
            Self::Lg => 15.0,
        }
    }

    pub(super) fn padding(&self) -> f32 {
        match self {
            Self::Xs => 2.0,
            Self::Sm => 4.0,
            Self::Md => 8.0,
            Self::Lg => 12.0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::NumberInputSize;
    use crate::ComponentSize;

    #[test]
    fn number_input_size_from_component_size() {
        assert_eq!(
            NumberInputSize::from(ComponentSize::Xs),
            NumberInputSize::Xs
        );
        assert_eq!(
            NumberInputSize::from(ComponentSize::Sm),
            NumberInputSize::Sm
        );
        assert_eq!(
            NumberInputSize::from(ComponentSize::Md),
            NumberInputSize::Md
        );
        assert_eq!(
            NumberInputSize::from(ComponentSize::Lg),
            NumberInputSize::Lg
        );
        assert_eq!(
            NumberInputSize::from(ComponentSize::Xl),
            NumberInputSize::Lg
        );
    }

    #[test]
    fn number_input_size_measurements() {
        assert_eq!(NumberInputSize::Xs.height(), 20.0);
        assert_eq!(NumberInputSize::Md.button_width(), 28.0);
        assert_eq!(NumberInputSize::Lg.font_size(), 15.0);
        assert_eq!(NumberInputSize::Sm.padding(), 4.0);
    }
}
