// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use gpui::SharedString;

/// Internal editing state for the number input
#[derive(Clone, Default)]
pub(super) struct NumberEditState {
    /// Whether currently editing
    pub(super) editing: bool,
    /// Current edit text
    pub(super) text: String,
    /// Cursor position (character index)
    pub(super) cursor: usize,
    /// Whether all text is selected
    pub(super) text_selected: bool,
    /// Cache key for the last formatted value.
    last_format_key: Option<(f64, usize, Option<SharedString>)>,
    /// Cached formatted display value.
    last_format_value: SharedString,
}

impl NumberEditState {
    pub(super) fn new(value: &str) -> Self {
        Self {
            editing: true,
            text: value.to_string(),
            cursor: value.chars().count(),
            text_selected: true,
            last_format_key: None,
            last_format_value: SharedString::default(),
        }
    }

    /// Returns the unit stored in the cached format key, if any.
    pub(super) fn last_unit(&self) -> Option<&SharedString> {
        self.last_format_key
            .as_ref()
            .and_then(|(_, _, unit)| unit.as_ref())
    }

    /// Format a numeric value as a display string, caching the result keyed by
    /// `(value, decimals, unit)`.
    pub(super) fn format_value_str(
        &mut self,
        value: f64,
        decimals: usize,
        unit: Option<&SharedString>,
    ) -> SharedString {
        // Fast path: compare the incoming unit by reference against the stored
        // key so we do not clone the SharedString on every cache hit.
        let cache_hit = self
            .last_format_key
            .as_ref()
            .map(|(last_value, last_decimals, last_unit)| {
                *last_value == value && *last_decimals == decimals && last_unit.as_ref() == unit
            })
            .unwrap_or(false);

        if cache_hit {
            return self.last_format_value.clone();
        }

        let formatted = format!("{:.prec$}", value, prec = decimals);
        let result: SharedString = if let Some(unit) = unit {
            format!("{} {}", formatted, unit).into()
        } else {
            formatted.into()
        };

        self.last_format_key = Some((value, decimals, unit.cloned()));
        self.last_format_value = result.clone();
        result
    }

    pub(super) fn select_all(&mut self) {
        self.text_selected = true;
        self.cursor = self.text.chars().count();
    }

    pub(super) fn do_backspace(&mut self) {
        if self.text_selected {
            self.text.clear();
            self.cursor = 0;
            self.text_selected = false;
        } else if self.cursor > 0 {
            // Find byte position of character before cursor
            // Since we only allow ASCII input, cursor == byte position
            // but we handle it correctly for safety
            let byte_pos = self
                .text
                .char_indices()
                .nth(self.cursor - 1)
                .map(|(i, _)| i)
                .unwrap_or(0);
            let next_byte = self
                .text
                .char_indices()
                .nth(self.cursor)
                .map(|(i, _)| i)
                .unwrap_or(self.text.len());
            self.text.replace_range(byte_pos..next_byte, "");
            self.cursor -= 1;
        }
    }

    pub(super) fn do_delete(&mut self) {
        if self.text_selected {
            self.text.clear();
            self.cursor = 0;
            self.text_selected = false;
        } else {
            let len = self.text.chars().count();
            if self.cursor < len {
                // Find byte positions for character at cursor
                let byte_pos = self
                    .text
                    .char_indices()
                    .nth(self.cursor)
                    .map(|(i, _)| i)
                    .unwrap_or(self.text.len());
                let next_byte = self
                    .text
                    .char_indices()
                    .nth(self.cursor + 1)
                    .map(|(i, _)| i)
                    .unwrap_or(self.text.len());
                self.text.replace_range(byte_pos..next_byte, "");
            }
        }
    }

    pub(super) fn insert_char(&mut self, ch: char) {
        // Only allow valid numeric characters (all ASCII, so 1 byte each)
        if !ch.is_ascii_digit() && ch != '.' && ch != '-' && ch != '+' {
            return;
        }

        if self.text_selected {
            self.text.clear();
            self.cursor = 0;
            self.text_selected = false;
        }

        // Find byte position for insertion
        let byte_pos = self
            .text
            .char_indices()
            .nth(self.cursor)
            .map(|(i, _)| i)
            .unwrap_or(self.text.len());
        self.text.insert(byte_pos, ch);
        self.cursor += 1;
    }

    pub(super) fn move_left(&mut self) {
        if self.cursor > 0 {
            self.cursor -= 1;
        }
        self.text_selected = false;
    }

    pub(super) fn move_right(&mut self) {
        let len = self.text.chars().count();
        if self.cursor < len {
            self.cursor += 1;
        }
        self.text_selected = false;
    }

    pub(super) fn move_to_start(&mut self) {
        self.cursor = 0;
        self.text_selected = false;
    }

    pub(super) fn move_to_end(&mut self) {
        self.cursor = self.text.chars().count();
        self.text_selected = false;
    }

    pub(super) fn kill_to_end(&mut self) {
        let chars: Vec<char> = self.text.chars().collect();
        self.text = chars[..self.cursor].iter().collect();
        self.text_selected = false;
    }

    pub(super) fn kill_to_start(&mut self) {
        let chars: Vec<char> = self.text.chars().collect();
        self.text = chars[self.cursor..].iter().collect();
        self.cursor = 0;
        self.text_selected = false;
    }

    pub(super) fn kill_word_backward(&mut self) {
        if self.cursor == 0 {
            return;
        }
        let chars: Vec<char> = self.text.chars().collect();
        let mut new_pos = self.cursor.min(chars.len());
        while new_pos > 0 && chars[new_pos - 1].is_whitespace() {
            new_pos -= 1;
        }
        while new_pos > 0 && !chars[new_pos - 1].is_whitespace() {
            new_pos -= 1;
        }
        let mut new_chars = chars[..new_pos].to_vec();
        new_chars.extend_from_slice(&chars[self.cursor..]);
        self.text = new_chars.into_iter().collect();
        self.cursor = new_pos;
        self.text_selected = false;
    }

    pub(super) fn kill_word_forward(&mut self) {
        let chars: Vec<char> = self.text.chars().collect();
        let len = chars.len();
        let mut new_pos = self.cursor.min(len);
        while new_pos < len && chars[new_pos].is_whitespace() {
            new_pos += 1;
        }
        while new_pos < len && !chars[new_pos].is_whitespace() {
            new_pos += 1;
        }
        let mut new_chars = chars[..self.cursor].to_vec();
        new_chars.extend_from_slice(&chars[new_pos..]);
        self.text = new_chars.into_iter().collect();
        self.text_selected = false;
    }

    pub(super) fn get_selected_text(&self) -> Option<String> {
        if self.text_selected && !self.text.is_empty() {
            Some(self.text.clone())
        } else {
            None
        }
    }

    pub(super) fn delete_selected(&mut self) -> bool {
        if self.text_selected {
            self.text.clear();
            self.cursor = 0;
            self.text_selected = false;
            true
        } else {
            false
        }
    }

    pub(super) fn insert_str(&mut self, s: &str) {
        self.delete_selected();
        // Filter to only valid numeric characters
        let filtered: String = s
            .chars()
            .filter(|&c| c.is_ascii_digit() || c == '.' || c == '-' || c == '+')
            .collect();
        if filtered.is_empty() {
            return;
        }
        let byte_pos = self
            .text
            .char_indices()
            .nth(self.cursor)
            .map(|(i, _)| i)
            .unwrap_or(self.text.len());
        self.text.insert_str(byte_pos, &filtered);
        self.cursor += filtered.chars().count();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gpui::SharedString;

    #[test]
    fn new_selects_all_text() {
        let state = NumberEditState::new("12.34");
        assert!(state.editing);
        assert_eq!(state.text, "12.34");
        assert_eq!(state.cursor, 5);
        assert!(state.text_selected);
    }

    #[test]
    fn format_value_caches_and_includes_unit() {
        let mut state = NumberEditState::default();
        let unit: SharedString = "Hz".into();

        let first = state.format_value_str(440.0, 1, Some(&unit));
        assert_eq!(first, "440.0 Hz");
        assert_eq!(state.last_unit(), Some(&unit));

        let second = state.format_value_str(440.0, 1, Some(&unit));
        assert!(std::ptr::eq(first.as_ref(), second.as_ref()));

        let third = state.format_value_str(440.0, 1, None);
        assert_ne!(first.as_ref(), third.as_ref());
    }

    #[test]
    fn insert_char_allows_only_numeric_input() {
        let mut state = NumberEditState::new("");
        state.insert_char('a');
        assert!(state.text.is_empty());

        state.insert_char('1');
        state.insert_char('.');
        state.insert_char('-');
        state.insert_char('+');
        assert_eq!(state.text, "1.-+");
    }

    #[test]
    fn backspace_and_delete_with_selection() {
        let mut state = NumberEditState::new("12345");
        state.do_backspace();
        assert!(state.text.is_empty());
        assert_eq!(state.cursor, 0);

        let mut state = NumberEditState::new("12345");
        state.delete_selected();
        assert!(state.text.is_empty());

        let mut state = NumberEditState::default();
        state.text = "ab".into();
        state.cursor = 0;
        state.do_delete();
        assert_eq!(state.text, "b");
    }

    #[test]
    fn move_and_kill_operations() {
        let mut state = NumberEditState::new("12 34");
        state.select_all();
        assert_eq!(state.cursor, 5);

        state.move_to_start();
        assert_eq!(state.cursor, 0);

        state.move_right();
        state.move_right();
        state.kill_to_end();
        assert_eq!(state.text, "12");

        let mut state = NumberEditState::new("12 34");
        state.cursor = 3;
        state.kill_to_start();
        assert_eq!(state.text, "34");
        assert_eq!(state.cursor, 0);
    }

    #[test]
    fn word_kill_and_navigation() {
        let mut state = NumberEditState::new("hello world");
        state.cursor = 11;
        state.kill_word_backward();
        assert_eq!(state.text, "hello ");
        assert_eq!(state.cursor, 6);

        let mut state = NumberEditState::new("hello world");
        state.cursor = 0;
        state.kill_word_forward();
        assert_eq!(state.text, " world");
        assert_eq!(state.cursor, 0);

        let mut state = NumberEditState::new("hello world");
        state.cursor = 0;
        state.kill_word_forward();
        assert_eq!(state.text, " world");
        state.cursor = 6;
        state.kill_word_backward();
        assert_eq!(state.text, " ");
    }

    #[test]
    fn insert_str_filters_and_replaces_selection() {
        let mut state = NumberEditState::new("abc");
        state.insert_str("1x2y3");
        assert_eq!(state.text, "123");
        assert_eq!(state.cursor, 3);
    }

    #[test]
    fn get_selected_text_only_when_selected() {
        let mut state = NumberEditState::new("hello");
        assert_eq!(state.get_selected_text(), Some("hello".to_string()));

        state.text_selected = false;
        assert!(state.get_selected_text().is_none());
    }
}
