use super::showcase_group::ShowcaseGroup;

/// Section identifiers for navigation
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ShowcaseSection {
    #[default]
    Buttons,
    Text,
    Badges,
    Avatars,
    FormControls,
    Progress,
    Alerts,
    Tabs,
    Cards,
    Breadcrumbs,
    Spinners,
    Layout,
    IconButtons,
    Toasts,
    Dialog,
    Menu,
    Table,
    Tooltips,
    Accordion,
    Wizard,
    Workflow,
    QrCode,
    ContextMenu,
    Popover,
    Sidebar,
    StatusBar,
    SearchBar,
    KeyboardShortcut,
    EmptyState,
    ConfirmDialog,
    SplitPane,
    ImageView,
    SettingsForm,
    StepIndicator,
    LoadingOverlay,
    Tag,
    Toolbar,
    Notification,
    TreeView,
    DragList,
    CommandPalette,
    Accessibility,
    AudioVisuals,
    ThinkingOrbs,
}

impl ShowcaseSection {
    pub fn all() -> &'static [ShowcaseSection] {
        &[
            ShowcaseSection::Buttons,
            ShowcaseSection::Text,
            ShowcaseSection::Badges,
            ShowcaseSection::Avatars,
            ShowcaseSection::FormControls,
            ShowcaseSection::Progress,
            ShowcaseSection::Alerts,
            ShowcaseSection::Tabs,
            ShowcaseSection::Cards,
            ShowcaseSection::Breadcrumbs,
            ShowcaseSection::Spinners,
            ShowcaseSection::Layout,
            ShowcaseSection::IconButtons,
            ShowcaseSection::Toasts,
            ShowcaseSection::Dialog,
            ShowcaseSection::Menu,
            ShowcaseSection::Table,
            ShowcaseSection::Tooltips,
            ShowcaseSection::Accordion,
            ShowcaseSection::Wizard,
            ShowcaseSection::Workflow,
            ShowcaseSection::QrCode,
            ShowcaseSection::ContextMenu,
            ShowcaseSection::Popover,
            ShowcaseSection::Sidebar,
            ShowcaseSection::StatusBar,
            ShowcaseSection::SearchBar,
            ShowcaseSection::KeyboardShortcut,
            ShowcaseSection::EmptyState,
            ShowcaseSection::ConfirmDialog,
            ShowcaseSection::SplitPane,
            ShowcaseSection::ImageView,
            ShowcaseSection::SettingsForm,
            ShowcaseSection::StepIndicator,
            ShowcaseSection::LoadingOverlay,
            ShowcaseSection::Tag,
            ShowcaseSection::Toolbar,
            ShowcaseSection::Notification,
            ShowcaseSection::TreeView,
            ShowcaseSection::DragList,
            ShowcaseSection::CommandPalette,
            ShowcaseSection::Accessibility,
            ShowcaseSection::AudioVisuals,
            ShowcaseSection::ThinkingOrbs,
        ]
    }

    pub fn label(&self) -> &'static str {
        match self {
            ShowcaseSection::Buttons => "Buttons",
            ShowcaseSection::Text => "Text",
            ShowcaseSection::Badges => "Badges",
            ShowcaseSection::Avatars => "Avatars",
            ShowcaseSection::FormControls => "Form Controls",
            ShowcaseSection::Progress => "Progress",
            ShowcaseSection::Alerts => "Alerts",
            ShowcaseSection::Tabs => "Tabs",
            ShowcaseSection::Cards => "Cards",
            ShowcaseSection::Breadcrumbs => "Breadcrumbs",
            ShowcaseSection::Spinners => "Spinners",
            ShowcaseSection::Layout => "Layout",
            ShowcaseSection::IconButtons => "Icon Buttons",
            ShowcaseSection::Toasts => "Toasts",
            ShowcaseSection::Dialog => "Dialog",
            ShowcaseSection::Menu => "Menu",
            ShowcaseSection::Table => "Table",
            ShowcaseSection::Tooltips => "Tooltips",
            ShowcaseSection::Accordion => "Accordion",
            ShowcaseSection::Wizard => "Wizard",
            ShowcaseSection::Workflow => "Workflow",
            ShowcaseSection::QrCode => "QR Code",
            ShowcaseSection::ContextMenu => "Context Menu",
            ShowcaseSection::Popover => "Popover",
            ShowcaseSection::Sidebar => "Sidebar",
            ShowcaseSection::StatusBar => "Status Bar",
            ShowcaseSection::SearchBar => "Search Bar",
            ShowcaseSection::KeyboardShortcut => "Keyboard Shortcuts",
            ShowcaseSection::EmptyState => "Empty State",
            ShowcaseSection::ConfirmDialog => "Confirm Dialog",
            ShowcaseSection::SplitPane => "Split Pane",
            ShowcaseSection::ImageView => "Image View",
            ShowcaseSection::SettingsForm => "Settings Form",
            ShowcaseSection::StepIndicator => "Step Indicator",
            ShowcaseSection::LoadingOverlay => "Loading Overlay",
            ShowcaseSection::Tag => "Tag",
            ShowcaseSection::Toolbar => "Toolbar",
            ShowcaseSection::Notification => "Notification",
            ShowcaseSection::TreeView => "Tree View",
            ShowcaseSection::DragList => "Drag List",
            ShowcaseSection::CommandPalette => "Command Palette",
            ShowcaseSection::Accessibility => "Accessibility",
            ShowcaseSection::AudioVisuals => "Audio Visuals",
            ShowcaseSection::ThinkingOrbs => "Thinking Orbs",
        }
    }

    pub fn group(&self) -> ShowcaseGroup {
        for group in ShowcaseGroup::all() {
            if group.sections().contains(self) {
                return *group;
            }
        }
        ShowcaseGroup::Actions
    }
}
