// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::component_lab_conformance_finding::ComponentLabConformanceFinding;
use anyhow::{Result, bail};
use gpui_design_tools::DesignTokenValidationReport;
use serde::Serialize;
use std::fmt::Write;

/// CI-facing component lab conformance report.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ComponentLabConformanceReport {
    pub passed: bool,
    pub story_count: usize,
    pub token_preset_count: usize,
    pub token_count: usize,
    pub findings: Vec<ComponentLabConformanceFinding>,
    pub design_conformance_markdown: String,
}

impl ComponentLabConformanceReport {
    pub(super) fn new(
        story_count: usize,
        token_report: &DesignTokenValidationReport,
        findings: Vec<ComponentLabConformanceFinding>,
    ) -> Self {
        Self {
            passed: findings.is_empty(),
            story_count,
            token_preset_count: token_report.preset_count,
            token_count: token_report.token_count,
            findings,
            design_conformance_markdown: token_report.conformance_markdown.clone(),
        }
    }

    pub fn passed(&self) -> bool {
        self.passed
    }

    pub fn to_markdown(&self) -> String {
        let mut output = String::with_capacity(
            128 + self.design_conformance_markdown.len() + self.findings.len() * 64,
        );
        writeln!(output, "# GPUI Component Lab Conformance\n").unwrap();
        writeln!(output, "- stories: {}", self.story_count).unwrap();
        writeln!(output, "- token presets: {}", self.token_preset_count).unwrap();
        writeln!(output, "- tokens: {}", self.token_count).unwrap();
        writeln!(
            output,
            "- status: {}\n",
            if self.passed { "pass" } else { "fail" }
        )
        .unwrap();
        output.push_str("## Design Tokens\n\n");
        output.push_str(&self.design_conformance_markdown);
        if !output.ends_with('\n') {
            output.push('\n');
        }
        output.push_str("\n## Component Findings\n\n");
        if self.findings.is_empty() {
            output.push_str("No component-lab findings.\n");
        } else {
            output.push_str("| category | id | story | message |\n");
            output.push_str("| --- | --- | --- | --- |\n");
            for finding in &self.findings {
                writeln!(
                    output,
                    "| {} | {} | {} | {} |",
                    finding.category,
                    finding.id,
                    finding.story_id.as_deref().unwrap_or("-"),
                    finding.message.replace('|', "\\|")
                )
                .unwrap();
            }
        }
        output
    }
}

pub fn ensure_component_lab_conformance_passed(
    report: &ComponentLabConformanceReport,
) -> Result<()> {
    if report.passed() {
        Ok(())
    } else {
        let mut message = String::from("component lab conformance failed: ");
        for (i, finding) in report.findings.iter().enumerate() {
            if i > 0 {
                message.push_str(", ");
            }
            write!(message, "{}:{}", finding.category, finding.id).unwrap();
        }
        bail!(message)
    }
}
