/// Story ids that have first-party GPUI renderers in the interactive lab.
pub const BUILTIN_RENDERER_STORY_IDS: &[&str] = &[
    "ui-kit.button",
    "ui-kit.form",
    "ui-kit.status",
    "ui-kit.navigation",
    "ui-kit.feedback",
    "ui-kit.card",
    "ui-kit.buttons",
    "ui-kit.text",
    "ui-kit.badges",
    "ui-kit.avatars",
    "ui-kit.form-controls",
    "ui-kit.progress",
    "ui-kit.alerts",
    "ui-kit.tabs",
    "ui-kit.cards",
    "ui-kit.breadcrumbs",
    "ui-kit.spinners",
    "ui-kit.layout",
    "ui-kit.icon-buttons",
    "ui-kit.toasts",
    "ui-kit.dialog",
    "ui-kit.menu",
    "ui-kit.table",
    "ui-kit.tooltips",
    "ui-kit.accordion",
    "ui-kit.wizard",
    "ui-kit.workflow",
    "ui-kit.qr-code",
    "ui-kit.context-menu",
    "ui-kit.popover",
    "ui-kit.sidebar",
    "ui-kit.status-bar",
    "ui-kit.search-bar",
    "ui-kit.keyboard-shortcut",
    "ui-kit.empty-state",
    "ui-kit.confirm-dialog",
    "ui-kit.split-pane",
    "ui-kit.image-view",
    "ui-kit.settings-form",
    "ui-kit.step-indicator",
    "ui-kit.loading-overlay",
    "ui-kit.tag",
    "ui-kit.toolbar",
    "ui-kit.notification",
    "ui-kit.tree-view",
    "ui-kit.drag-list",
    "ui-kit.command-palette",
    "ui-kit.accessibility",
    "ui-kit.button-set",
    "ui-kit.icon-button",
    "ui-kit.alert",
    "ui-kit.inline-alert",
    "ui-kit.toast",
    "ui-kit.toast-container",
    "ui-kit.checkbox",
    "ui-kit.color-picker",
    "ui-kit.input",
    "ui-kit.number-input",
    "ui-kit.select",
    "ui-kit.slider",
    "ui-kit.toggle",
    "ui-kit.avatar",
    "ui-kit.avatar-group",
    "ui-kit.badge",
    "ui-kit.badge-dot",
    "ui-kit.empty-state-component",
    "ui-kit.image-view-component",
    "ui-kit.keyboard-shortcut-label",
    "ui-kit.progress-bar",
    "ui-kit.circular-progress",
    "ui-kit.qr-code-component",
    "ui-kit.animated-qr-code",
    "ui-kit.spinner",
    "ui-kit.loading-dots",
    "ui-kit.step-indicator-component",
    "ui-kit.text-component",
    "ui-kit.heading",
    "ui-kit.code",
    "ui-kit.link",
    "ui-kit.search-bar-component",
    "ui-kit.tooltip-component",
    "ui-kit.with-tooltip",
    "ui-kit.loading-overlay-component",
    "ui-kit.pane-divider",
    "ui-kit.settings-row",
    "ui-kit.settings-form-component",
    "ui-kit.sidebar-component",
    "ui-kit.split-pane-component",
    "ui-kit.vstack",
    "ui-kit.hstack",
    "ui-kit.spacer",
    "ui-kit.divider",
    "ui-kit.grid-component",
    "ui-kit.center-component",
    "ui-kit.aspect-ratio-component",
    "ui-kit.resizable-component",
    "ui-kit.visually-hidden-component",
    "ui-kit.status-bar-component",
    "ui-kit.accordion-component",
    "ui-kit.breadcrumbs-component",
    "ui-kit.menu-component",
    "ui-kit.menu-bar",
    "ui-kit.dialog-component",
    "ui-kit.confirm-dialog-component",
    "ui-kit.popover-component",
    "ui-kit.context-menu-component",
    "ui-kit.tabs-component",
    "ui-kit.wizard-component",
    "ui-kit.wizard-header",
    "ui-kit.wizard-navigation",
    "ui-kit.command-palette-component",
    "ui-kit.drag-list-component",
    "ui-kit.notification-component",
    "ui-kit.tag-component",
    "ui-kit.toolbar-component",
    "ui-kit.tree-view-component",
    "ui-kit.table-component",
    "ui-kit.workflow-node",
    "ui-kit.focus-group",
    "ui-kit.workflow-port",
    "ui-kit.workflow-canvas",
    "ui-kit.showcase-component",
    "ui-kit.app-shell-component",
    "ui-kit.top-nav-component",
    "ui-kit.mobile-nav-component",
    "ui-kit.date-range-input-component",
    "ui-kit.time-input-component",
    "ui-kit.date-time-input-component",
    "ui-kit.chat-component",
    "ui-kit.markdown-component",
    "ui-kit.blockquote-component",
    "ui-kit.carousel-component",
    "ui-kit.selectable-card-component",
    "ui-kit.citation-component",
    "ui-kit.timestamp-component",
    "ui-kit.metadata-list-component",
    "ui-kit.file-input-component",
    "ui-kit.tokenizer-component",
    "ui-kit.field-component",
    "ui-kit.field-status-component",
    "ui-kit.skeleton-component",
    "ui-kit.lightbox-component",
    "ui-kit.hover-card-component",
    "ui-kit.layer-component",
    "ui-kit.calendar-component",
    "ui-kit.pagination-component",
    "ui-kit.list-component",
    "ui-kit.app-shell",
    "ui-kit.top-nav",
    "ui-kit.mobile-nav",
    "ui-kit.date-range-input",
    "ui-kit.time-input",
    "ui-kit.date-time-input",
    "ui-kit.chat",
    "ui-kit.markdown",
    "ui-kit.blockquote",
    "ui-kit.carousel",
    "ui-kit.selectable-card",
    "ui-kit.citation",
    "ui-kit.timestamp",
    "ui-kit.metadata-list",
    "ui-kit.file-input",
    "ui-kit.tokenizer",
    "ui-kit.field",
    "ui-kit.field-status",
    "ui-kit.skeleton",
    "ui-kit.lightbox",
    "ui-kit.hover-card",
    "ui-kit.layer",
    "ui-kit.calendar",
    "ui-kit.pagination",
    "ui-kit.list",
    "audio-kit.potentiometer",
    "audio-kit.vertical-slider",
    "audio-kit.volume-knob",
    "audio-kit.meter",
    "audio-kit.horizontal-meter",
    "audio-kit.spectrum",
    "audio-kit.spectrum-axis",
    "audio-kit.backend-compare",
    "px.line",
    "px.bar",
    "px.scatter",
    "px.area",
    "px.heatmap",
    "px.contour",
    "px.isoline",
    "px.pie",
    "px.donut",
    "px.boxplot",
    "px.treemap",
    "px.surface3d",
    "px.mesh_plot",
    "px.mesh_plot.mesh_only",
    "px.mesh_plot.smooth_fill",
    "px.mesh_plot.flat_fill",
    "px.mesh_plot.filled_contours",
    "px.mesh_plot.isolines",
    "px.mesh_plot.combined",
    "px.mesh_plot.axisymmetric_section",
    "px.mesh_plot.revolve",
    "px.mesh_plot.surface3d",
    "px.mesh_plot.large_mesh",
    "px.mesh_plot.picking",
];

pub const UI_KIT_EXPORTED_COMPONENT_STORY_IDS: &[&str] = &[
    "ui-kit.button",
    "ui-kit.card",
    "ui-kit.button-set",
    "ui-kit.icon-button",
    "ui-kit.alert",
    "ui-kit.inline-alert",
    "ui-kit.toast",
    "ui-kit.toast-container",
    "ui-kit.checkbox",
    "ui-kit.color-picker",
    "ui-kit.input",
    "ui-kit.number-input",
    "ui-kit.select",
    "ui-kit.slider",
    "ui-kit.toggle",
    "ui-kit.avatar",
    "ui-kit.avatar-group",
    "ui-kit.badge",
    "ui-kit.badge-dot",
    "ui-kit.empty-state-component",
    "ui-kit.image-view-component",
    "ui-kit.keyboard-shortcut-label",
    "ui-kit.progress-bar",
    "ui-kit.circular-progress",
    "ui-kit.qr-code-component",
    "ui-kit.animated-qr-code",
    "ui-kit.spinner",
    "ui-kit.loading-dots",
    "ui-kit.step-indicator-component",
    "ui-kit.text-component",
    "ui-kit.heading",
    "ui-kit.code",
    "ui-kit.link",
    "ui-kit.search-bar-component",
    "ui-kit.tooltip-component",
    "ui-kit.with-tooltip",
    "ui-kit.loading-overlay-component",
    "ui-kit.pane-divider",
    "ui-kit.settings-row",
    "ui-kit.settings-form-component",
    "ui-kit.sidebar-component",
    "ui-kit.split-pane-component",
    "ui-kit.vstack",
    "ui-kit.hstack",
    "ui-kit.spacer",
    "ui-kit.divider",
    "ui-kit.grid-component",
    "ui-kit.center-component",
    "ui-kit.aspect-ratio-component",
    "ui-kit.resizable-component",
    "ui-kit.visually-hidden-component",
    "ui-kit.status-bar-component",
    "ui-kit.accordion-component",
    "ui-kit.breadcrumbs-component",
    "ui-kit.menu-component",
    "ui-kit.menu-bar",
    "ui-kit.dialog-component",
    "ui-kit.confirm-dialog-component",
    "ui-kit.popover-component",
    "ui-kit.context-menu-component",
    "ui-kit.tabs-component",
    "ui-kit.wizard-component",
    "ui-kit.wizard-header",
    "ui-kit.wizard-navigation",
    "ui-kit.command-palette-component",
    "ui-kit.drag-list-component",
    "ui-kit.notification-component",
    "ui-kit.tag-component",
    "ui-kit.toolbar-component",
    "ui-kit.tree-view-component",
    "ui-kit.table-component",
    "ui-kit.workflow-node",
    "ui-kit.focus-group",
    "ui-kit.workflow-port",
    "ui-kit.workflow-canvas",
    "ui-kit.showcase-component",
    "ui-kit.app-shell-component",
    "ui-kit.top-nav-component",
    "ui-kit.mobile-nav-component",
    "ui-kit.date-range-input-component",
    "ui-kit.time-input-component",
    "ui-kit.date-time-input-component",
    "ui-kit.chat-component",
    "ui-kit.markdown-component",
    "ui-kit.blockquote-component",
    "ui-kit.carousel-component",
    "ui-kit.selectable-card-component",
    "ui-kit.citation-component",
    "ui-kit.timestamp-component",
    "ui-kit.metadata-list-component",
    "ui-kit.file-input-component",
    "ui-kit.tokenizer-component",
    "ui-kit.field-component",
    "ui-kit.field-status-component",
    "ui-kit.skeleton-component",
    "ui-kit.lightbox-component",
    "ui-kit.hover-card-component",
    "ui-kit.layer-component",
    "ui-kit.calendar-component",
    "ui-kit.pagination-component",
    "ui-kit.list-component",
];

pub const UI_KIT_EXPORTED_COMPONENT_STORY_TYPES: &[(&str, &str)] = &[
    ("Button", "ui-kit.button"),
    ("Card", "ui-kit.card"),
    ("ButtonSet", "ui-kit.button-set"),
    ("IconButton", "ui-kit.icon-button"),
    ("Alert", "ui-kit.alert"),
    ("InlineAlert", "ui-kit.inline-alert"),
    ("Toast", "ui-kit.toast"),
    ("ToastContainer", "ui-kit.toast-container"),
    ("Checkbox", "ui-kit.checkbox"),
    ("ColorPickerView", "ui-kit.color-picker"),
    ("Input", "ui-kit.input"),
    ("NumberInput", "ui-kit.number-input"),
    ("Select", "ui-kit.select"),
    ("Slider", "ui-kit.slider"),
    ("Toggle", "ui-kit.toggle"),
    ("Avatar", "ui-kit.avatar"),
    ("AvatarGroup", "ui-kit.avatar-group"),
    ("Badge", "ui-kit.badge"),
    ("BadgeDot", "ui-kit.badge-dot"),
    ("EmptyState", "ui-kit.empty-state-component"),
    ("ImageView", "ui-kit.image-view-component"),
    ("KeyboardShortcutLabel", "ui-kit.keyboard-shortcut-label"),
    ("Progress", "ui-kit.progress-bar"),
    ("CircularProgress", "ui-kit.circular-progress"),
    ("QrCode", "ui-kit.qr-code-component"),
    ("AnimatedQrCode", "ui-kit.animated-qr-code"),
    ("Spinner", "ui-kit.spinner"),
    ("LoadingDots", "ui-kit.loading-dots"),
    ("StepIndicator", "ui-kit.step-indicator-component"),
    ("Text", "ui-kit.text-component"),
    ("Heading", "ui-kit.heading"),
    ("Code", "ui-kit.code"),
    ("Link", "ui-kit.link"),
    ("SearchBar", "ui-kit.search-bar-component"),
    ("Tooltip", "ui-kit.tooltip-component"),
    ("WithTooltip", "ui-kit.with-tooltip"),
    ("LoadingOverlay", "ui-kit.loading-overlay-component"),
    ("PaneDivider", "ui-kit.pane-divider"),
    ("SettingsRow", "ui-kit.settings-row"),
    ("SettingsForm", "ui-kit.settings-form-component"),
    ("Sidebar", "ui-kit.sidebar-component"),
    ("SplitPane", "ui-kit.split-pane-component"),
    ("VStack", "ui-kit.vstack"),
    ("HStack", "ui-kit.hstack"),
    ("Spacer", "ui-kit.spacer"),
    ("Divider", "ui-kit.divider"),
    ("Grid", "ui-kit.grid-component"),
    ("Center", "ui-kit.center-component"),
    ("AspectRatio", "ui-kit.aspect-ratio-component"),
    ("Resizable", "ui-kit.resizable-component"),
    ("VisuallyHidden", "ui-kit.visually-hidden-component"),
    ("StatusBar", "ui-kit.status-bar-component"),
    ("Accordion", "ui-kit.accordion-component"),
    ("Breadcrumbs", "ui-kit.breadcrumbs-component"),
    ("Menu", "ui-kit.menu-component"),
    ("MenuBar", "ui-kit.menu-bar"),
    ("Dialog", "ui-kit.dialog-component"),
    ("ConfirmDialog", "ui-kit.confirm-dialog-component"),
    ("Popover", "ui-kit.popover-component"),
    ("ContextMenu", "ui-kit.context-menu-component"),
    ("Tabs", "ui-kit.tabs-component"),
    ("Wizard", "ui-kit.wizard-component"),
    ("WizardHeader", "ui-kit.wizard-header"),
    ("WizardNavigation", "ui-kit.wizard-navigation"),
    ("CommandPalette", "ui-kit.command-palette-component"),
    ("DragList", "ui-kit.drag-list-component"),
    ("Notification", "ui-kit.notification-component"),
    ("Tag", "ui-kit.tag-component"),
    ("Toolbar", "ui-kit.toolbar-component"),
    ("TreeView", "ui-kit.tree-view-component"),
    ("Table", "ui-kit.table-component"),
    ("WorkflowNode", "ui-kit.workflow-node"),
    ("FocusGroup", "ui-kit.focus-group"),
    ("Port", "ui-kit.workflow-port"),
    ("WorkflowCanvas", "ui-kit.workflow-canvas"),
    ("Showcase", "ui-kit.showcase-component"),
    ("AppShell", "ui-kit.app-shell-component"),
    ("TopNav", "ui-kit.top-nav-component"),
    ("MobileNav", "ui-kit.mobile-nav-component"),
    ("DateRangeInput", "ui-kit.date-range-input-component"),
    ("TimeInput", "ui-kit.time-input-component"),
    ("DateTimeInput", "ui-kit.date-time-input-component"),
    ("Chat", "ui-kit.chat-component"),
    ("Markdown", "ui-kit.markdown-component"),
    ("Blockquote", "ui-kit.blockquote-component"),
    ("Carousel", "ui-kit.carousel-component"),
    ("SelectableCard", "ui-kit.selectable-card-component"),
    ("Citation", "ui-kit.citation-component"),
    ("Timestamp", "ui-kit.timestamp-component"),
    ("MetadataList", "ui-kit.metadata-list-component"),
    ("FileInput", "ui-kit.file-input-component"),
    ("Tokenizer", "ui-kit.tokenizer-component"),
    ("Field", "ui-kit.field-component"),
    ("FieldStatus", "ui-kit.field-status-component"),
    ("Skeleton", "ui-kit.skeleton-component"),
    ("Lightbox", "ui-kit.lightbox-component"),
    ("HoverCard", "ui-kit.hover-card-component"),
    ("Layer", "ui-kit.layer-component"),
    ("Calendar", "ui-kit.calendar-component"),
    ("Pagination", "ui-kit.pagination-component"),
    ("List", "ui-kit.list-component"),
];

pub const PX_CHART_STORY_IDS: &[&str] = &[
    "px.line",
    "px.bar",
    "px.scatter",
    "px.area",
    "px.heatmap",
    "px.contour",
    "px.isoline",
    "px.pie",
    "px.donut",
    "px.boxplot",
    "px.treemap",
    "px.surface3d",
    "px.mesh_plot",
];

/// Component-lab mesh stories. The base story is the editable mode matrix;
/// the named variants keep the release captures deterministic and make each
/// required `MeshPlot` view directly addressable from the lab.
pub const MESH_PLOT_STORY_IDS: &[&str] = &[
    "px.mesh_plot",
    "px.mesh_plot.mesh_only",
    "px.mesh_plot.smooth_fill",
    "px.mesh_plot.flat_fill",
    "px.mesh_plot.filled_contours",
    "px.mesh_plot.isolines",
    "px.mesh_plot.combined",
    "px.mesh_plot.axisymmetric_section",
    "px.mesh_plot.revolve",
    "px.mesh_plot.surface3d",
    "px.mesh_plot.large_mesh",
    "px.mesh_plot.picking",
];

/// Mesh story variants kept out of the public `gpui-px` builder list.
pub const MESH_PLOT_STORY_VARIANT_IDS: &[&str] = &[
    "px.mesh_plot.mesh_only",
    "px.mesh_plot.smooth_fill",
    "px.mesh_plot.flat_fill",
    "px.mesh_plot.filled_contours",
    "px.mesh_plot.isolines",
    "px.mesh_plot.combined",
    "px.mesh_plot.axisymmetric_section",
    "px.mesh_plot.revolve",
    "px.mesh_plot.surface3d",
    "px.mesh_plot.large_mesh",
    "px.mesh_plot.picking",
];

pub const PX_CHART_STORY_TYPES: &[(&str, &str)] = &[
    ("LineChart", "px.line"),
    ("BarChart", "px.bar"),
    ("ScatterChart", "px.scatter"),
    ("AreaChart", "px.area"),
    ("HeatmapChart", "px.heatmap"),
    ("ContourChart", "px.contour"),
    ("IsolineChart", "px.isoline"),
    ("PieChart", "px.pie"),
    ("donut()", "px.donut"),
    ("BoxPlotChart", "px.boxplot"),
    ("Treemap", "px.treemap"),
    ("Surface3DChart", "px.surface3d"),
    ("MeshPlot", "px.mesh_plot"),
];

pub(super) fn ui_kit_showcase_story_id(story_id: &str) -> bool {
    UI_KIT_SHOWCASE_STORIES
        .iter()
        .any(|(id, _, _)| *id == story_id)
}

/// Exported component stories as (story id, component name, description).
///
/// Tooling (notably `gpui-toolkit doctor`) reads this to verify every
/// exported component resolves to a registered story.
pub const UI_KIT_EXPORTED_COMPONENT_STORIES: &[(&str, &str, &str)] = &[
    (
        "ui-kit.button-set",
        "ButtonSet",
        "Segmented button selection",
    ),
    (
        "ui-kit.icon-button",
        "IconButton",
        "Icon-only action button",
    ),
    ("ui-kit.alert", "Alert", "Dismissible alert surface"),
    (
        "ui-kit.inline-alert",
        "InlineAlert",
        "Inline feedback message",
    ),
    ("ui-kit.toast", "Toast", "Transient toast message"),
    (
        "ui-kit.toast-container",
        "ToastContainer",
        "Toast stack positioning",
    ),
    ("ui-kit.checkbox", "Checkbox", "Boolean form control"),
    (
        "ui-kit.color-picker",
        "ColorPickerView",
        "RGB/HSL color editor",
    ),
    ("ui-kit.input", "Input", "Text input field"),
    ("ui-kit.number-input", "NumberInput", "Numeric input field"),
    ("ui-kit.select", "Select", "Dropdown selection control"),
    ("ui-kit.slider", "Slider", "Range slider control"),
    ("ui-kit.toggle", "Toggle", "Switch/toggle control"),
    ("ui-kit.avatar", "Avatar", "User avatar"),
    ("ui-kit.avatar-group", "AvatarGroup", "Stacked avatar group"),
    ("ui-kit.badge", "Badge", "Status badge"),
    ("ui-kit.badge-dot", "BadgeDot", "Small status dot"),
    (
        "ui-kit.empty-state-component",
        "EmptyState",
        "Empty-state illustration block",
    ),
    (
        "ui-kit.image-view-component",
        "ImageView",
        "Image placeholder and fitting frame",
    ),
    (
        "ui-kit.keyboard-shortcut-label",
        "KeyboardShortcutLabel",
        "Keyboard shortcut token label",
    ),
    ("ui-kit.progress-bar", "Progress", "Linear progress bar"),
    (
        "ui-kit.circular-progress",
        "CircularProgress",
        "Circular progress indicator",
    ),
    ("ui-kit.qr-code-component", "QrCode", "QR code renderer"),
    (
        "ui-kit.animated-qr-code",
        "AnimatedQrCode",
        "Animated QR code renderer",
    ),
    ("ui-kit.spinner", "Spinner", "Loading spinner"),
    (
        "ui-kit.loading-dots",
        "LoadingDots",
        "Animated loading dots",
    ),
    (
        "ui-kit.step-indicator-component",
        "StepIndicator",
        "Step progress indicator",
    ),
    ("ui-kit.text-component", "Text", "Body text component"),
    ("ui-kit.heading", "Heading", "Heading text component"),
    ("ui-kit.code", "Code", "Inline code component"),
    ("ui-kit.link", "Link", "Clickable link text"),
    (
        "ui-kit.search-bar-component",
        "SearchBar",
        "Search field surface",
    ),
    (
        "ui-kit.tooltip-component",
        "Tooltip",
        "Standalone tooltip bubble",
    ),
    ("ui-kit.with-tooltip", "WithTooltip", "Tooltip wrapper"),
    (
        "ui-kit.loading-overlay-component",
        "LoadingOverlay",
        "Blocking loading overlay",
    ),
    (
        "ui-kit.pane-divider",
        "PaneDivider",
        "Collapsible pane divider",
    ),
    ("ui-kit.settings-row", "SettingsRow", "Settings form row"),
    (
        "ui-kit.settings-form-component",
        "SettingsForm",
        "Grouped settings form",
    ),
    (
        "ui-kit.sidebar-component",
        "Sidebar",
        "Sidebar layout surface",
    ),
    (
        "ui-kit.split-pane-component",
        "SplitPane",
        "Resizable split pane",
    ),
    ("ui-kit.vstack", "VStack", "Vertical stack layout"),
    ("ui-kit.hstack", "HStack", "Horizontal stack layout"),
    ("ui-kit.spacer", "Spacer", "Flexible stack spacer"),
    ("ui-kit.divider", "Divider", "Stack divider"),
    ("ui-kit.grid-component", "Grid", "Fixed-column grid layout"),
    (
        "ui-kit.center-component",
        "Center",
        "Single-child centering container",
    ),
    (
        "ui-kit.aspect-ratio-component",
        "AspectRatio",
        "Fixed aspect-ratio box",
    ),
    (
        "ui-kit.resizable-component",
        "Resizable",
        "User-resizable panel",
    ),
    (
        "ui-kit.visually-hidden-component",
        "VisuallyHidden",
        "Screen-reader-only content",
    ),
    (
        "ui-kit.status-bar-component",
        "StatusBar",
        "Application status bar",
    ),
    (
        "ui-kit.accordion-component",
        "Accordion",
        "Disclosure accordion",
    ),
    (
        "ui-kit.breadcrumbs-component",
        "Breadcrumbs",
        "Breadcrumb navigation",
    ),
    ("ui-kit.menu-component", "Menu", "Menu list"),
    ("ui-kit.menu-bar", "MenuBar", "Menu bar"),
    ("ui-kit.dialog-component", "Dialog", "Modal dialog"),
    (
        "ui-kit.confirm-dialog-component",
        "ConfirmDialog",
        "Confirmation dialog",
    ),
    ("ui-kit.popover-component", "Popover", "Popover panel"),
    (
        "ui-kit.context-menu-component",
        "ContextMenu",
        "Context menu list",
    ),
    ("ui-kit.tabs-component", "Tabs", "Tabs component"),
    ("ui-kit.wizard-component", "Wizard", "Wizard component"),
    ("ui-kit.wizard-header", "WizardHeader", "Wizard header"),
    (
        "ui-kit.wizard-navigation",
        "WizardNavigation",
        "Wizard navigation controls",
    ),
    (
        "ui-kit.command-palette-component",
        "CommandPalette",
        "Command palette overlay",
    ),
    ("ui-kit.drag-list-component", "DragList", "Reorderable list"),
    (
        "ui-kit.notification-component",
        "Notification",
        "Persistent notification banner",
    ),
    ("ui-kit.tag-component", "Tag", "Tag/chip component"),
    ("ui-kit.toolbar-component", "Toolbar", "Toolbar component"),
    ("ui-kit.tree-view-component", "TreeView", "Tree view"),
    ("ui-kit.table-component", "Table", "Table component"),
    ("ui-kit.workflow-node", "WorkflowNode", "Workflow node"),
    ("ui-kit.focus-group", "FocusGroup", "Focus-managed layout"),
    ("ui-kit.workflow-port", "Port", "Workflow connection port"),
    (
        "ui-kit.workflow-canvas",
        "WorkflowCanvas",
        "Node workflow canvas",
    ),
    (
        "ui-kit.showcase-component",
        "Showcase",
        "Embedded UI-kit showcase component",
    ),
    (
        "ui-kit.app-shell-component",
        "AppShell",
        "Application frame with header, sidebar, content, and footer slots",
    ),
    (
        "ui-kit.top-nav-component",
        "TopNav",
        "Top navigation bar with brand, items, and trailing actions",
    ),
    (
        "ui-kit.mobile-nav-component",
        "MobileNav",
        "Mobile bottom tab bar with parent-owned selection",
    ),
    (
        "ui-kit.date-range-input-component",
        "DateRangeInput",
        "Date range field without interactive range selection",
    ),
    (
        "ui-kit.time-input-component",
        "TimeInput",
        "Clock-time field without interactive time selection",
    ),
    (
        "ui-kit.date-time-input-component",
        "DateTimeInput",
        "Date-time field without interactive selection",
    ),
    (
        "ui-kit.chat-component",
        "Chat",
        "Conversation transcript with role-based bubbles",
    ),
    (
        "ui-kit.markdown-component",
        "Markdown",
        "Small Markdown source renderer",
    ),
    (
        "ui-kit.blockquote-component",
        "Blockquote",
        "Styled quotation with optional citation",
    ),
    (
        "ui-kit.carousel-component",
        "Carousel",
        "Slide rotation with dot navigation",
    ),
    (
        "ui-kit.selectable-card-component",
        "SelectableCard",
        "Card with selected state and click activation",
    ),
    (
        "ui-kit.citation-component",
        "Citation",
        "Source reference with attribution",
    ),
    (
        "ui-kit.timestamp-component",
        "Timestamp",
        "Muted inline time label",
    ),
    (
        "ui-kit.metadata-list-component",
        "MetadataList",
        "Label/value detail rows with dividers",
    ),
    (
        "ui-kit.file-input-component",
        "FileInput",
        "File picker trigger with chosen file name",
    ),
    (
        "ui-kit.tokenizer-component",
        "Tokenizer",
        "Multi-value token editor with removable chips",
    ),
    (
        "ui-kit.field-component",
        "Field",
        "Shared label, control slot, and help or error text",
    ),
    (
        "ui-kit.field-status-component",
        "FieldStatus",
        "Validation message with severity styling",
    ),
    (
        "ui-kit.skeleton-component",
        "Skeleton",
        "Loading placeholder reserving content shape",
    ),
    (
        "ui-kit.lightbox-component",
        "Lightbox",
        "Display-only image overlay with caption",
    ),
    (
        "ui-kit.hover-card-component",
        "HoverCard",
        "Text-only card next to a target",
    ),
    (
        "ui-kit.layer-component",
        "Layer",
        "Overlay container without stacking",
    ),
    (
        "ui-kit.calendar-component",
        "Calendar",
        "Month grid with keyboard selection",
    ),
    (
        "ui-kit.pagination-component",
        "Pagination",
        "Page buttons with ellipsis gaps",
    ),
    (
        "ui-kit.list-component",
        "List",
        "Selectable rows with descriptions",
    ),
];

/// Showcase stories as (story id, component name, description).
///
/// Tooling (notably `gpui-toolkit doctor`) reads this to verify every
/// showcase story resolves to a registered story.
pub const UI_KIT_SHOWCASE_STORIES: &[(&str, &str, &str)] = &[
    (
        "ui-kit.buttons",
        "Buttons",
        "Button variants, sizes, and states",
    ),
    ("ui-kit.text", "Text", "Typography, code, and link styles"),
    (
        "ui-kit.badges",
        "Badges",
        "Badge variants, dots, and sizing",
    ),
    (
        "ui-kit.avatars",
        "Avatars",
        "Avatar, group, shape, and status states",
    ),
    (
        "ui-kit.form-controls",
        "Form Controls",
        "Inputs, selects, sliders, toggles, and button sets",
    ),
    (
        "ui-kit.progress",
        "Progress",
        "Linear and circular progress indicators",
    ),
    ("ui-kit.alerts", "Alerts", "Alert and inline alert variants"),
    ("ui-kit.tabs", "Tabs", "Tab navigation variants and states"),
    ("ui-kit.cards", "Cards", "Card composition and slot styling"),
    ("ui-kit.breadcrumbs", "Breadcrumbs", "Breadcrumb navigation"),
    (
        "ui-kit.spinners",
        "Spinners",
        "Spinner and loading dot states",
    ),
    (
        "ui-kit.layout",
        "Layout",
        "Stack, spacer, and divider primitives",
    ),
    (
        "ui-kit.icon-buttons",
        "Icon Buttons",
        "Icon-only action buttons and states",
    ),
    (
        "ui-kit.toasts",
        "Toasts",
        "Toast container and notification states",
    ),
    ("ui-kit.dialog", "Dialog", "Modal dialog composition"),
    ("ui-kit.menu", "Menu", "Menu bar and menu item states"),
    (
        "ui-kit.table",
        "Table",
        "Table sorting, selection, and pagination",
    ),
    (
        "ui-kit.tooltips",
        "Tooltips",
        "Tooltip placements and triggers",
    ),
    (
        "ui-kit.accordion",
        "Accordion",
        "Accordion disclosure groups",
    ),
    ("ui-kit.wizard", "Wizard", "Step-based wizard navigation"),
    (
        "ui-kit.workflow",
        "Workflow",
        "Workflow canvas building blocks",
    ),
    ("ui-kit.qr-code", "QR Code", "QR code rendering"),
    (
        "ui-kit.context-menu",
        "Context Menu",
        "Context menu trigger patterns",
    ),
    ("ui-kit.popover", "Popover", "Popover placement and content"),
    ("ui-kit.sidebar", "Sidebar", "Sidebar layout variants"),
    (
        "ui-kit.status-bar",
        "Status Bar",
        "Status bar regions and items",
    ),
    ("ui-kit.search-bar", "Search Bar", "Search input states"),
    (
        "ui-kit.keyboard-shortcut",
        "Keyboard Shortcuts",
        "Keyboard shortcut label rendering",
    ),
    ("ui-kit.empty-state", "Empty State", "Empty state messaging"),
    (
        "ui-kit.confirm-dialog",
        "Confirm Dialog",
        "Confirmation dialog variants",
    ),
    (
        "ui-kit.split-pane",
        "Split Pane",
        "Resizable split pane behavior",
    ),
    (
        "ui-kit.image-view",
        "Image View",
        "Image fitting and preview states",
    ),
    (
        "ui-kit.settings-form",
        "Settings Form",
        "Settings form rows and grouping",
    ),
    (
        "ui-kit.step-indicator",
        "Step Indicator",
        "Horizontal and vertical step indicators",
    ),
    (
        "ui-kit.loading-overlay",
        "Loading Overlay",
        "Loading overlay states",
    ),
    ("ui-kit.tag", "Tag", "Tag states and removable tags"),
    ("ui-kit.toolbar", "Toolbar", "Toolbar action groups"),
    (
        "ui-kit.notification",
        "Notification",
        "Notification surface states",
    ),
    ("ui-kit.tree-view", "Tree View", "Tree hierarchy rendering"),
    ("ui-kit.drag-list", "Drag List", "Reorderable list preview"),
    (
        "ui-kit.command-palette",
        "Command Palette",
        "Command palette search and item states",
    ),
    (
        "ui-kit.accessibility",
        "Accessibility",
        "Accessible labeling and focus metadata examples",
    ),
    (
        "ui-kit.app-shell",
        "App Shell",
        "Application frame slot composition",
    ),
    (
        "ui-kit.top-nav",
        "Top Navigation",
        "Top navigation items and states",
    ),
    (
        "ui-kit.mobile-nav",
        "Mobile Navigation",
        "Mobile bottom tab selection",
    ),
    (
        "ui-kit.date-range-input",
        "Date Range Input",
        "Date range bounds and validation",
    ),
    (
        "ui-kit.time-input",
        "Time Input",
        "Clock-time value and placeholder states",
    ),
    (
        "ui-kit.date-time-input",
        "Date Time Input",
        "Combined date and time parts",
    ),
    (
        "ui-kit.chat",
        "Chat",
        "Conversation roles and bubble styling",
    ),
    (
        "ui-kit.markdown",
        "Markdown",
        "Headings, code, lists, and quotes",
    ),
    (
        "ui-kit.blockquote",
        "Blockquote",
        "Quotations with citations",
    ),
    (
        "ui-kit.carousel",
        "Carousel",
        "Slide rotation and dot navigation",
    ),
    (
        "ui-kit.selectable-card",
        "Selectable Card",
        "Selectable cards and plan pickers",
    ),
    (
        "ui-kit.citation",
        "Citation",
        "Inline and block source references",
    ),
    (
        "ui-kit.timestamp",
        "Timestamp",
        "Relative and absolute time labels",
    ),
    (
        "ui-kit.metadata-list",
        "Metadata List",
        "Label/value detail rows",
    ),
    (
        "ui-kit.file-input",
        "File Input",
        "File picker states and filter hints",
    ),
    (
        "ui-kit.tokenizer",
        "Tokenizer",
        "Token chips and removal states",
    ),
    (
        "ui-kit.field",
        "Field",
        "Labels, required markers, and help or error text",
    ),
    (
        "ui-kit.field-status",
        "Field Status",
        "Validation severities and announcements",
    ),
    (
        "ui-kit.skeleton",
        "Skeleton",
        "Text, rectangle, and circle placeholders",
    ),
    ("ui-kit.lightbox", "Lightbox", "Image overlay with caption"),
    (
        "ui-kit.hover-card",
        "Hover Card",
        "Text cards next to targets",
    ),
    ("ui-kit.layer", "Layer", "Minimal overlay container"),
    ("ui-kit.calendar", "Calendar", "Month grids and day picking"),
    (
        "ui-kit.pagination",
        "Pagination",
        "Page windows for results",
    ),
    ("ui-kit.list", "List", "Selectable static rows"),
];
