// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use gpui::SharedString;
use serde::{Deserialize, Serialize};

/// Theme/design selector used by stories.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThemePreset {
    pub id: SharedString,
    pub label: SharedString,
    pub design: String,
    pub reduced_motion: bool,
}

impl ThemePreset {
    pub fn new(
        id: impl Into<SharedString>,
        label: impl Into<SharedString>,
        design: impl Into<String>,
        reduced_motion: bool,
    ) -> Self {
        Self {
            id: id.into(),
            label: label.into(),
            design: design.into(),
            reduced_motion,
        }
    }
}
