// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::types::Sizing;
use crate::util::format_number;

pub(super) fn format_sizing(sizing: Sizing<'_>) -> String {
    match sizing {
        Sizing::Fixed(size) => format!("Fixed({})", format_number(size)),
        Sizing::Fractional { initial, min, max } => format!(
            "Fractional(initial={},min={},max={})",
            format_number(initial),
            format_number(min),
            if max == f32::MAX {
                "unbounded".to_string()
            } else {
                format_number(max)
            }
        ),
        Sizing::Flex { min, weight } => {
            format!(
                "Flex(min={},weight={})",
                format_number(min),
                format_number(weight)
            )
        }
        Sizing::Text {
            text,
            line_height,
            min,
            ..
        } => format!(
            "Text(chars={},line_height={},min={})",
            text.chars().count(),
            format_number(line_height),
            format_number(min)
        ),
    }
}
