// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::format::format_sizing;
use super::misc::WARNING_EPSILON;
use super::misc::axis_name;
use super::misc::source_child;
use super::solved_node::SolvedNode;
use super::solved_node::visibility_label;
use super::types::LayoutDebugWarningKind;
use crate::types::LayoutNode;
use crate::util::format_number;
use std::fmt;

/// A single warning emitted by a [`LayoutDebugReport`].
#[derive(Debug, Clone, PartialEq)]
pub struct LayoutDebugWarning {
    /// Node where the suspicious outcome was detected.
    pub node_id: String,
    /// Warning category and related measurements.
    pub kind: LayoutDebugWarningKind,
}

impl fmt::Display for LayoutDebugWarning {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.kind {
            LayoutDebugWarningKind::InvalidSize { width, height } => write!(
                f,
                "{} has invalid size {}x{}",
                self.node_id,
                format_number(*width),
                format_number(*height)
            ),
            LayoutDebugWarningKind::InvisibleWithoutCollapseLabel => {
                write!(f, "{} is invisible without a collapse label", self.node_id)
            }
            LayoutDebugWarningKind::MainAxisOverflow {
                axis,
                used,
                available,
            } => write!(
                f,
                "{} children use {}px on the {} axis, exceeding {}px",
                self.node_id,
                format_number(*used),
                axis_name(*axis),
                format_number(*available)
            ),
            LayoutDebugWarningKind::CrossAxisOverflow {
                axis,
                child_id,
                used,
                available,
            } => write!(
                f,
                "{} child {} uses {}px on the {} axis, exceeding {}px",
                self.node_id,
                child_id,
                format_number(*used),
                axis_name(*axis),
                format_number(*available)
            ),
        }
    }
}

pub(super) fn append_debug_node<'a>(
    node: &SolvedNode<'a>,
    source: Option<&LayoutNode<'a>>,
    depth: usize,
    lines: &mut Vec<String>,
    warnings: &mut Vec<LayoutDebugWarning>,
) {
    let indent = "  ".repeat(depth);
    let mut line = format!(
        "{indent}{} size={}x{} {}",
        node.id,
        format_number(node.width),
        format_number(node.height),
        visibility_label(node),
    );

    if let Some(axis) = node.resolved_axis {
        line.push_str(" axis=");
        line.push_str(axis_name(axis));
    }

    if let Some(tier) = node.active_tier {
        line.push_str(" tier=");
        line.push_str(tier);
    }

    if let Some(label) = node.collapse_label
        && !node.visible
    {
        line.push_str(" label=");
        line.push_str(&format!("{label:?}"));
    }

    if let Some(source) = source {
        line.push_str(" sizing=");
        line.push_str(&format_sizing(source.sizing()));

        if source.collapsible() {
            line.push_str(" collapsible priority=");
            line.push_str(&format_number(source.priority()));
        }
    }

    lines.push(line);
    collect_node_warnings(node, warnings);

    for child in &node.children {
        let source_child = source_child(source, child.id);
        append_debug_node(child, source_child, depth + 1, lines, warnings);
    }
}

pub(super) fn collect_node_warnings<'a>(
    node: &SolvedNode<'a>,
    warnings: &mut Vec<LayoutDebugWarning>,
) {
    if !node.width.is_finite()
        || !node.height.is_finite()
        || node.width < -WARNING_EPSILON
        || node.height < -WARNING_EPSILON
    {
        warnings.push(LayoutDebugWarning {
            node_id: node.id.to_string(),
            kind: LayoutDebugWarningKind::InvalidSize {
                width: node.width,
                height: node.height,
            },
        });
    }

    if !node.visible && node.collapse_label.is_none() {
        warnings.push(LayoutDebugWarning {
            node_id: node.id.to_string(),
            kind: LayoutDebugWarningKind::InvisibleWithoutCollapseLabel,
        });
    }

    let Some(axis) = node.resolved_axis else {
        return;
    };
    if !node.visible {
        return;
    }

    let available = node.size_along(axis);
    let used: f32 = node
        .children
        .iter()
        .filter(|child| child.visible)
        .map(|child| child.size_along(axis))
        .sum();

    if available.is_finite() && used.is_finite() && used > available + WARNING_EPSILON {
        warnings.push(LayoutDebugWarning {
            node_id: node.id.to_string(),
            kind: LayoutDebugWarningKind::MainAxisOverflow {
                axis,
                used,
                available,
            },
        });
    }

    let cross = axis.cross();
    let available_cross = node.size_along(cross);
    if !available_cross.is_finite() {
        return;
    }

    for child in node.children.iter().filter(|child| child.visible) {
        let child_cross = child.size_along(cross);
        if child_cross.is_finite() && child_cross > available_cross + WARNING_EPSILON {
            warnings.push(LayoutDebugWarning {
                node_id: node.id.to_string(),
                kind: LayoutDebugWarningKind::CrossAxisOverflow {
                    axis: cross,
                    child_id: child.id.to_string(),
                    used: child_cross,
                    available: available_cross,
                },
            });
        }
    }
}
