// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::analysis_profile::analyze_text;
use super::is::is_cjk;
use super::normalize::normalize_whitespace_normal;
use super::normalize::normalize_whitespace_pre_wrap;
use super::split::split_segment_by_break_kind;
use super::types::AnalysisProfile;
use super::types::WhiteSpaceMode;
use super::types::get_white_space_profile;

#[test]
fn test_normalize_normal() {
    assert_eq!(
        normalize_whitespace_normal("  hello   world  ").as_ref(),
        "hello world"
    );
    assert_eq!(normalize_whitespace_normal("a\tb\nc").as_ref(), "a b c");
    assert_eq!(normalize_whitespace_normal("hello").as_ref(), "hello");
}

#[test]
fn test_normalize_pre_wrap() {
    assert_eq!(normalize_whitespace_pre_wrap("a\r\nb").as_ref(), "a\nb");
    assert_eq!(normalize_whitespace_pre_wrap("a\rb").as_ref(), "a\nb");
}

#[test]
fn test_normalize_cow_borrowed_when_unchanged() {
    // Inputs that require no transformation should be returned borrowed.
    assert!(matches!(
        normalize_whitespace_normal("hello"),
        std::borrow::Cow::Borrowed(_)
    ));
    assert!(matches!(
        normalize_whitespace_pre_wrap("hello"),
        std::borrow::Cow::Borrowed(_)
    ));
}

#[test]
fn test_is_cjk() {
    assert!(is_cjk("你好"));
    assert!(is_cjk("こんにちは"));
    assert!(!is_cjk("hello"));
}

#[test]
fn test_analyze_empty() {
    let profile = AnalysisProfile {
        carry_cjk_after_closing_quote: false,
    };
    let result = analyze_text("", &profile, WhiteSpaceMode::Normal);
    assert!(result.is_empty());
}

#[test]
fn test_analyze_simple() {
    let profile = AnalysisProfile {
        carry_cjk_after_closing_quote: false,
    };
    let result = analyze_text("hello world", &profile, WhiteSpaceMode::Normal);
    assert!(result.len() >= 3); // "hello", " ", "world"
}

#[test]
fn test_analyze_pre_wrap_hard_breaks() {
    let profile = AnalysisProfile {
        carry_cjk_after_closing_quote: false,
    };
    let result = analyze_text("a\nb\nc", &profile, WhiteSpaceMode::PreWrap);
    assert!(result.chunks.len() >= 3);
}

#[test]
fn test_split_segment_by_break_kind_returns_slices() {
    let ws = get_white_space_profile(WhiteSpaceMode::Normal);
    let pieces = split_segment_by_break_kind("a b", true, 10, &ws);
    assert_eq!(pieces.len(), 3);
    assert_eq!(pieces[0].text, "a");
    assert_eq!(pieces[0].start, 10);
    assert_eq!(pieces[1].text, " ");
    assert_eq!(pieces[2].text, "b");
    assert_eq!(pieces[2].start, 12);
}
