//! Theme-coverage gate (review rec: compile-time theme-field coverage).
//!
//! Every global [`Theme`](gpui_ui_kit::theme::Theme) color field must be
//! consumed by at least one component theme, otherwise adding/renaming a
//! theme field silently leaves components behind. Component themes expose
//! their consumed fields via `THEME_SOURCES` (generated by
//! `#[derive(ComponentTheme)]`, including `theme.<field>` references scraped
//! from `from_expr` strings).
//!
//! Two guards:
//!
//! 1. `all_theme_fields_compiles_exhaustively` constructs [`Theme`] with an
//!    exhaustive struct literal — adding a field to `Theme` breaks this test
//!    at compile time until the field is triaged below.
//! 2. `every_theme_field_is_consumed` asserts the union of all
//!    `THEME_SOURCES` covers [`Theme::FIELD_NAMES`](gpui_ui_kit::theme::Theme::FIELD_NAMES)
//!    minus [`DELIBERATELY_UNCOVERED`].
//!
//! When adding a component theme (`#[derive(ComponentTheme)]`), register its
//! `THEME_SOURCES` in [`ALL_THEME_SOURCES`]. When adding a global theme
//! field, either consume it from a component theme or document it in
//! [`DELIBERATELY_UNCOVERED`] with a reason.

use gpui_ui_kit::theme::{Theme, ThemeVariant};

/// Fields that are intentionally not consumed via `from = ...`, with reasons.
///
/// Keep this list empty-or-justified: each entry weakens the gate.
const DELIBERATELY_UNCOVERED: &[(&str, &str)] = &[
    // No read of `icon_on_accent` outside `theme.rs` (verified 2026-09-03).
    ("icon_on_accent", "reserved for future icon theming"),
    // Orphaned token: `InputTheme::border_hover` maps `from = accent`
    // (`src/input/types.rs`) and `Select` uses its own trigger token, so no
    // component consumes the global hover-border token. Kept (not removed)
    // so a future hover-border pass has a token to adopt.
    (
        "border_hover",
        "global hover-border token reserved; see src/input/types.rs",
    ),
];

/// Global fields consumed by direct `Theme` reads instead of `from = ...`.
///
/// Each entry names the source file and a snippet that must keep existing;
/// the snippets are verified with `include_str!` so deleting the read trips
/// the gate. Prefer `from = ...` mappings for new code — direct reads are
/// grandfathered, not encouraged.
const DIRECTLY_CONSUMED: &[(&str, &str, &str)] = &[
    ("badge_info_bg", "src/badge.rs", "theme.badge_info_bg"),
    ("badge_info_text", "src/badge.rs", "theme.badge_info_text"),
    ("code_text", "src/text/misc.rs", "theme.code_text"),
];

const BADGE_RS: &str = include_str!("../src/badge.rs");
const TEXT_MISC_RS: &str = include_str!("../src/text/misc.rs");

/// Exhaustive construction: fails to compile when `Theme` gains a field.
fn construct_all_fields() -> Theme {
    use gpui::{rgb, rgba};
    Theme {
        variant: ThemeVariant::Dark,
        background: rgb(0),
        surface: rgb(0),
        surface_hover: rgb(0),
        muted: rgb(0),
        transparent: rgba(0),
        overlay_bg: rgba(0),
        text_primary: rgb(0),
        text_secondary: rgb(0),
        text_muted: rgb(0),
        text_on_accent: rgb(0),
        icon_on_accent: rgb(0),
        accent: rgb(0),
        accent_hover: rgb(0),
        accent_muted: rgba(0),
        success: rgb(0),
        warning: rgb(0),
        error: rgb(0),
        info: rgb(0),
        border: rgb(0),
        border_hover: rgb(0),
        font_family: "test".into(),
        badge_primary_bg: rgb(0),
        badge_primary_text: rgb(0),
        badge_success_bg: rgb(0),
        badge_success_text: rgb(0),
        badge_warning_bg: rgb(0),
        badge_warning_text: rgb(0),
        badge_error_bg: rgb(0),
        badge_error_text: rgb(0),
        badge_info_bg: rgb(0),
        badge_info_text: rgb(0),
        alert_info_bg: rgb(0),
        alert_success_bg: rgb(0),
        alert_warning_bg: rgb(0),
        alert_error_bg: rgb(0),
        code_text: rgb(0),
    }
}

/// Union of every registered component theme's consumed global fields.
///
/// Register new `#[derive(ComponentTheme)]` structs here.
fn all_theme_sources() -> Vec<&'static str> {
    use gpui_ui_kit::*;
    let mut sources = Vec::new();
    sources.extend(accordion::AccordionTheme::THEME_SOURCES);
    sources.extend(button::ButtonTheme::THEME_SOURCES);
    sources.extend(button_set::ButtonSetTheme::THEME_SOURCES);
    sources.extend(checkbox::CheckboxTheme::THEME_SOURCES);
    sources.extend(command_palette::CommandPaletteTheme::THEME_SOURCES);
    sources.extend(confirm_dialog::ConfirmDialogTheme::THEME_SOURCES);
    sources.extend(context_menu::ContextMenuTheme::THEME_SOURCES);
    sources.extend(dialog::DialogTheme::THEME_SOURCES);
    sources.extend(drag_list::DragListTheme::THEME_SOURCES);
    sources.extend(icon_button::IconButtonTheme::THEME_SOURCES);
    sources.extend(image_view::ImageViewTheme::THEME_SOURCES);
    sources.extend(input::InputTheme::THEME_SOURCES);
    sources.extend(loading_overlay::LoadingOverlayTheme::THEME_SOURCES);
    sources.extend(menu::MenuTheme::THEME_SOURCES);
    sources.extend(notification::NotificationTheme::THEME_SOURCES);
    sources.extend(number_input::NumberInputTheme::THEME_SOURCES);
    sources.extend(pane_divider::PaneDividerTheme::THEME_SOURCES);
    sources.extend(popover::PopoverTheme::THEME_SOURCES);
    sources.extend(radio_group::RadioGroupTheme::THEME_SOURCES);
    sources.extend(search_bar::SearchBarTheme::THEME_SOURCES);
    sources.extend(select::SelectTheme::THEME_SOURCES);
    sources.extend(settings_form::SettingsFormTheme::THEME_SOURCES);
    sources.extend(sidebar::SidebarTheme::THEME_SOURCES);
    sources.extend(slider::SliderTheme::THEME_SOURCES);
    sources.extend(split_pane::SplitPaneTheme::THEME_SOURCES);
    sources.extend(status_bar::StatusBarTheme::THEME_SOURCES);
    sources.extend(step_indicator::StepIndicatorTheme::THEME_SOURCES);
    sources.extend(table::TableTheme::THEME_SOURCES);
    sources.extend(tabs::TabsTheme::THEME_SOURCES);
    sources.extend(tag::TagTheme::THEME_SOURCES);
    sources.extend(toggle::ToggleTheme::THEME_SOURCES);
    sources.extend(toolbar::ToolbarTheme::THEME_SOURCES);
    sources.extend(tree_view::TreeViewTheme::THEME_SOURCES);
    sources.extend(wizard::WizardTheme::THEME_SOURCES);
    sources.sort();
    sources.dedup();
    sources
}

#[test]
fn all_theme_fields_compiles_exhaustively() {
    let theme = construct_all_fields();
    // Touch every FIELD_NAMES entry so list-vs-struct drift is loud: each
    // name must resolve against the constructed value via a match on the
    // field set. (Field access by string is impossible; the exhaustive
    // literal above is the compile guard, this loop is the runtime guard.)
    assert_eq!(Theme::FIELD_NAMES.len(), 35);
    let _ = theme;
}

#[test]
fn every_theme_field_is_consumed() {
    let covered = all_theme_sources();
    assert!(
        !covered.is_empty(),
        "no THEME_SOURCES registered; the gate is vacuous"
    );

    // Direct global reads count as consumption, but only while the read
    // actually exists in the named source file.
    let mut direct_covered = Vec::new();
    for (field, file, snippet) in DIRECTLY_CONSUMED {
        let source = match *file {
            "src/badge.rs" => BADGE_RS,
            "src/text/misc.rs" => TEXT_MISC_RS,
            other => panic!("DIRECTLY_CONSUMED points at unknown file `{other}`"),
        };
        assert!(
            source.contains(snippet),
            "direct consumption of `{field}` vanished from {file}: re-consume it or move the field to DELIBERATELY_UNCOVERED"
        );
        direct_covered.push(*field);
    }

    let mut uncovered = Vec::new();
    for field in Theme::FIELD_NAMES {
        if covered.contains(field) || direct_covered.contains(field) {
            continue;
        }
        if DELIBERATELY_UNCOVERED.iter().any(|(name, _)| name == field) {
            continue;
        }
        uncovered.push(*field);
    }
    assert!(
        uncovered.is_empty(),
        "global Theme fields consumed by no component theme (consume via `from = ...` or document in DELIBERATELY_UNCOVERED): {uncovered:?}\ncovered: {covered:?}"
    );

    // Exceptions must stay valid: every deliberately-uncovered name must be a
    // real theme field, so renames cannot hide behind stale exceptions.
    for (name, _) in DELIBERATELY_UNCOVERED {
        assert!(
            Theme::FIELD_NAMES.contains(name),
            "stale DELIBERATELY_UNCOVERED entry `{name}`: no such Theme field"
        );
    }
}
