from collections.abc import Callable, Iterable, Mapping, Sequence
from typing import Any

class DataError(ValueError): ...
class SchemaError(DataError): ...
class ClosedResourceError(DataError): ...
class MutationError(DataError): ...
class DataTransportError(DataError): ...

class Expr:
    def to_spec(self) -> dict[str, Any]: ...
    def is_null(self) -> Expr: ...
    def isin(self, values: Sequence[str | int | float | bool | None]) -> Expr: ...
def col(name: str) -> Expr: ...

class FieldRef:
    name: str
    def __init__(self, name: str) -> None: ...
    def to_spec(self) -> dict[str, str]: ...
def field(name: str) -> FieldRef: ...

class Categorical:
    codes: Sequence[int | None]
    categories: Sequence[str]
    def __init__(self, codes: Sequence[int | None], categories: Sequence[str]) -> None: ...

class DatasetView:
    @property
    def available_fields(self) -> tuple[str, ...]: ...
    @property
    def selected_fields(self) -> tuple[str, ...] | None: ...
    def filter(self, expression: Expr) -> DatasetView: ...
    def select(self, *fields: str) -> DatasetView: ...
    def sort(self, field: str, *, descending: bool = False) -> DatasetView: ...
    def group_by(self, *fields: str) -> DatasetView: ...
    def aggregate(self, **aggregations: str) -> DatasetView: ...
    def bin(self, field: str, *, count: int) -> DatasetView: ...
    def window(self, *, size: int, step: int = 1) -> DatasetView: ...
    def range(self, start: int, stop: int) -> DatasetView: ...
    def to_spec(self) -> dict[str, Any]: ...

class DataBinding:
    def role(self, name: str, field_name: str) -> DataBinding: ...
    def x(self, field_name: str) -> DataBinding: ...
    def y(self, field_name: str) -> DataBinding: ...
    def y0(self, field_name: str) -> DataBinding: ...
    def y2(self, field_name: str) -> DataBinding: ...
    def color(self, field_name: str) -> DataBinding: ...
    def size(self, field_name: str) -> DataBinding: ...
    def label(self, field_name: str) -> DataBinding: ...
    def series(self, field_name: str) -> DataBinding: ...
    def dash(self, field_name: str) -> DataBinding: ...
    def row_id(self, field_name: str) -> DataBinding: ...
    def tooltip(self, field_name: str) -> DataBinding: ...
    def accessibility_description(self, field_name: str) -> DataBinding: ...
    def to_spec(self) -> dict[str, Any]: ...

class Dataset:
    id: str
    key: str | None
    generation: int
    schema: tuple[str, ...]
    row_count: int
    @classmethod
    def from_mapping(cls, columns: Mapping[str, Sequence[Any]], *, key: str | None = None, id: str | None = None) -> Dataset: ...
    @classmethod
    def from_rows(cls, rows: Iterable[Mapping[str, Any]], *, key: str | None = None, id: str | None = None) -> Dataset: ...
    @classmethod
    def from_pandas(cls, frame: Any, *, key: str | None = None, id: str | None = None) -> Dataset: ...
    @classmethod
    def from_polars(cls, frame: Any, *, key: str | None = None, id: str | None = None) -> Dataset: ...
    @classmethod
    def from_arrow(cls, table: Any, *, key: str | None = None, id: str | None = None) -> Dataset: ...
    @classmethod
    def from_dataframe(cls, frame: Any, *, key: str | None = None, id: str | None = None) -> Dataset: ...
    def view(self) -> DatasetView: ...
    def binding(self) -> DataBinding: ...
    def append(self, batch: Mapping[str, Sequence[Any]] | Iterable[Mapping[str, Any]]) -> None: ...
    def upsert(self, batch: Mapping[str, Sequence[Any]] | Iterable[Mapping[str, Any]], *, key: str | None = None) -> None: ...
    def delete(self, keys: Iterable[Any]) -> None: ...
    def replace(self, snapshot: Mapping[str, Sequence[Any]] | Iterable[Mapping[str, Any]]) -> None: ...
    def migrate(self, snapshot: Mapping[str, Sequence[Any]], *, key: str | None = None) -> None: ...
    def subscribe(self, callback: Callable[[Dataset], None]) -> Callable[[], None]: ...
    def close(self) -> None: ...
    def to_spec(self) -> dict[str, Any]: ...
    def to_arrow_ipc(self) -> bytes: ...
    def arrow_ipc_chunks(self, *, max_bytes: int = ...) -> tuple[bytes, ...]: ...

class ArrayData:
    id: str
    shape: tuple[int, ...]
    dtype: str
    generation: int
    @classmethod
    def from_buffer(cls, data: Any, *, shape: Sequence[int], dtype: str, id: str | None = None) -> ArrayData: ...
    @classmethod
    def from_numpy(cls, array: Any, *, id: str | None = None) -> ArrayData: ...
    @classmethod
    def from_dlpack(cls, source: Any, *, id: str | None = None) -> ArrayData: ...
    def replace(self, data: Any, *, shape: Sequence[int] | None = None, dtype: str | None = None) -> None: ...
    def subscribe(self, callback: Callable[[ArrayData], None]) -> Callable[[], None]: ...
    def close(self) -> None: ...
    def to_spec(self) -> dict[str, Any]: ...
