from typing import Any
from .scene2d import GridCell

class Event:
    id: str
    sequence: int
    node_id: str
    event: str
    action: str | None
    payload: dict[str, Any] | None
    def __init__(self, id: str, sequence: int, node_id: str, event: str, action: str | None = ..., payload: dict[str, Any] | None = ...) -> None: ...
    @property
    def kind(self) -> str: ...
    @classmethod
    def from_message(cls, message: dict[str, Any]) -> Event: ...

class Click(Event):
    @property
    def modifiers(self) -> tuple[str, ...]: ...

class Selection(Event):
    @property
    def selected_keys(self) -> tuple[str, ...]: ...
    @property
    def keys(self) -> tuple[str, ...]: ...
    @property
    def key(self) -> str | None: ...
    @property
    def selected_id(self) -> str | None: ...
    @property
    def x(self) -> float | None: ...
    @property
    def y(self) -> float | None: ...
    @property
    def series(self) -> str | None: ...
    @property
    def series_index(self) -> int | None: ...
    @property
    def point_index(self) -> int | None: ...
    @property
    def value(self) -> float | None: ...
    @property
    def plot_id(self) -> str | None: ...
    @property
    def mesh_id(self) -> str | None: ...
    @property
    def cell_index(self) -> int | None: ...
    @property
    def cell_id(self) -> int | None: ...
    @property
    def vertex_id(self) -> int | None: ...
    @property
    def world_position(self) -> tuple[float, float, float] | None: ...
    @property
    def displayed_value(self) -> float | None: ...
    @property
    def field_id(self) -> str | None: ...

class Viewport(Event):
    @property
    def x_range(self) -> tuple[float, float] | None: ...
    @property
    def y_range(self) -> tuple[float, float] | None: ...
    @property
    def zoom_level(self) -> int | None: ...
    @property
    def is_zoomed(self) -> bool | None: ...
    @property
    def camera(self) -> dict[str, Any] | None: ...
    @property
    def camera_distance(self) -> float | None: ...
    @property
    def camera_angles(self) -> tuple[float, float] | None: ...
    @property
    def camera_target(self) -> tuple[float, float, float] | None: ...

class ValueChange(Event):
    @property
    def value(self) -> Any: ...

class Scene2DPointerInput:
    phase: str
    device: str
    contact_id: int
    timestamp_ns: int
    x: float
    y: float
    buttons: tuple[str, ...]
    modifiers: tuple[str, ...]
    hit_id: str | None
    cell: GridCell | None
    def __init__(self, phase: str, device: str, contact_id: int, timestamp_ns: int, x: float, y: float, buttons: tuple[str, ...] = ..., modifiers: tuple[str, ...] = ..., hit_id: str | None = ..., cell: GridCell | None = ...) -> None: ...
    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> Scene2DPointerInput: ...

class Scene2DKeyInput:
    phase: str
    key: str
    repeat: bool
    modifiers: tuple[str, ...]
    timestamp_ns: int
    def __init__(self, phase: str, key: str, repeat: bool, modifiers: tuple[str, ...], timestamp_ns: int) -> None: ...
    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> Scene2DKeyInput: ...

class Scene2DLifecycleInput:
    reason: str
    timestamp_ns: int
    def __init__(self, reason: str, timestamp_ns: int) -> None: ...

class Scene2DTransitionCompleteInput:
    id: str
    completion_id: str
    timestamp_ns: int
    def __init__(self, id: str, completion_id: str, timestamp_ns: int) -> None: ...

class Scene2DActivateInput:
    id: str
    timestamp_ns: int
    hit_id: str | None
    cell: GridCell | None
    def __init__(self, id: str, timestamp_ns: int, hit_id: str | None = ..., cell: GridCell | None = ...) -> None: ...

class Scene2DEvent(Event):
    surface_id: str
    input: Scene2DPointerInput | Scene2DKeyInput | Scene2DLifecycleInput | Scene2DTransitionCompleteInput | Scene2DActivateInput | None
    def __init__(self, id: str, sequence: int, node_id: str, event: str, action: str | None = ..., payload: dict[str, Any] | None = ..., surface_id: str = ..., input: Scene2DPointerInput | Scene2DKeyInput | Scene2DLifecycleInput | Scene2DTransitionCompleteInput | Scene2DActivateInput | None = ...) -> None: ...
    @classmethod
    def from_event(cls, event: Event) -> Scene2DEvent: ...

class Scene2DTick:
    elapsed_ns: int
    frame: int
    surface_id: str
    def __init__(self, elapsed_ns: int, frame: int, surface_id: str = ...) -> None: ...
    @classmethod
    def from_event(cls, event: Event) -> Scene2DTick: ...
    @property
    def elapsed_seconds(self) -> float: ...

def specialize(message: dict[str, Any]) -> Event: ...

ChartSelection = Selection
ChartViewport = Viewport

def specialize(message: dict[str, Any]) -> Event: ...
