from typing import Any

class Event:
    id: str
    sequence: int
    node_id: str
    event: str
    action: str | None
    payload: dict[str, Any] | None
    @property
    def kind(self) -> str: ...
    @classmethod
    def from_message(cls, message: dict[str, Any]) -> Event: ...

class Click(Event):
    @property
    def modifiers(self) -> tuple[str, ...]: ...

class Selection(Event):
    @property
    def selected_keys(self) -> tuple[str, ...]: ...
    @property
    def keys(self) -> tuple[str, ...]: ...
    @property
    def key(self) -> str | None: ...
    @property
    def selected_id(self) -> str | None: ...
    @property
    def x(self) -> float | None: ...
    @property
    def y(self) -> float | None: ...
    @property
    def series(self) -> str | None: ...
    @property
    def series_index(self) -> int | None: ...
    @property
    def point_index(self) -> int | None: ...
    @property
    def value(self) -> float | None: ...
    @property
    def plot_id(self) -> str | None: ...
    @property
    def mesh_id(self) -> str | None: ...
    @property
    def cell_index(self) -> int | None: ...
    @property
    def cell_id(self) -> int | None: ...
    @property
    def vertex_id(self) -> int | None: ...
    @property
    def world_position(self) -> tuple[float, float, float] | None: ...
    @property
    def displayed_value(self) -> float | None: ...
    @property
    def field_id(self) -> str | None: ...

class Viewport(Event):
    @property
    def x_range(self) -> tuple[float, float] | None: ...
    @property
    def y_range(self) -> tuple[float, float] | None: ...
    @property
    def zoom_level(self) -> int | None: ...
    @property
    def is_zoomed(self) -> bool | None: ...
    @property
    def camera(self) -> dict[str, Any] | None: ...
    @property
    def camera_distance(self) -> float | None: ...
    @property
    def camera_angles(self) -> tuple[float, float] | None: ...
    @property
    def camera_target(self) -> tuple[float, float, float] | None: ...

class ValueChange(Event):
    @property
    def value(self) -> Any: ...

ChartSelection = Selection
ChartViewport = Viewport

def specialize(message: dict[str, Any]) -> Event: ...
