from typing import Protocol, Sequence

class CueBackend(Protocol):
    def preload(self, cue_ids: Sequence[str]) -> None: ...
    def play(self, cue_id: str, command_id: str) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...

class GameCueAdapter:
    dropped_cues: int
    backend_errors: int
    def __init__(self, backend: CueBackend | None = ..., *, max_pending: int = ..., dedupe_window: int = ...) -> None: ...
    @property
    def available(self) -> bool: ...
    def preload(self, cue_ids: Sequence[str]) -> bool: ...
    def play(self, cue_id: str, command_id: str) -> bool: ...
    def pause(self) -> bool: ...
    def resume(self) -> bool: ...
    def close(self) -> None: ...
