from enum import Enum
from typing import Callable
from .data import ArrayData, DataBinding, Dataset, DatasetView
from .d3 import Renderer2D, VelloBackend
from .meshplot import MeshGeometry, MeshPlotSpec, MeshRevolve, MeshScalarField
from .resources import Resource
from .commands import CommandResult
from .app import SessionContext

class Lod(str, Enum):
    AUTO: Lod
    OFF: Lod
    AGGRESSIVE: Lod

class LegendPosition(str, Enum):
    RIGHT: LegendPosition
    LEFT: LegendPosition
    TOP: LegendPosition
    BOTTOM: LegendPosition
    HIDDEN: LegendPosition

class TilingMethod(str, Enum):
    SQUARIFY: TilingMethod
    BINARY: TilingMethod
    SLICE: TilingMethod
    DICE: TilingMethod
    SLICE_DICE: TilingMethod
class CurveType(str, Enum):
    LINEAR: CurveType
    STEP: CurveType
    STEP_BEFORE: CurveType
    STEP_AFTER: CurveType
    BASIS: CurveType
    CARDINAL: CurveType
    CATMULL_ROM: CurveType
    MONOTONE_X: CurveType
    NATURAL: CurveType

class TreemapNode:
    name: str
    value: float
    children: tuple[TreemapNode, ...]
    def __init__(self, name: str, value: float = 0.0, children: tuple[TreemapNode, ...] = ()) -> None: ...
    @classmethod
    def new(cls, name: str, value: float) -> TreemapNode: ...
    @classmethod
    def with_children(cls, name: str, children: tuple[TreemapNode, ...] | list[TreemapNode]) -> TreemapNode: ...
    def add_child(self, child: TreemapNode) -> TreemapNode: ...
    def total_value(self) -> float: ...
    def is_leaf(self) -> bool: ...

class TreemapRect:
    x0: float
    y0: float
    x1: float
    y1: float
    name: str
    value: float
    depth: int
    category_index: int

class TreemapLayoutError(ValueError): ...

def treemap_layout(
    root: TreemapNode,
    width: float,
    height: float,
    method: TilingMethod = TilingMethod.SQUARIFY,
    padding: float = 1.0,
) -> tuple[TreemapRect, ...]: ...

class InteractionMode(str, Enum):
    NONE: InteractionMode
    BRUSH: InteractionMode
    PAN: InteractionMode
    ZOOM: InteractionMode

class ChartKeyboardAction(str, Enum):
    ZOOM_IN: ChartKeyboardAction
    ZOOM_OUT: ChartKeyboardAction
    PAN_LEFT: ChartKeyboardAction
    PAN_RIGHT: ChartKeyboardAction
    PAN_UP: ChartKeyboardAction
    PAN_DOWN: ChartKeyboardAction
    RESET_ZOOM: ChartKeyboardAction

class ChartCapabilityStatus(str, Enum):
    IMPLEMENTED: ChartCapabilityStatus
    PARTIAL: ChartCapabilityStatus
    MISSING: ChartCapabilityStatus
    APP_BRIDGE_REQUIRED: ChartCapabilityStatus
    def is_release_ready(self) -> bool: ...

class ChartCapabilityEntry:
    id: str
    capability: str
    chart_families: tuple[str, ...]
    story_ids: tuple[str, ...]
    test_contracts: tuple[str, ...]
    status: ChartCapabilityStatus
    evidence: str
    release_requirement: str

class ChartCapabilityReport:
    schema_version: int
    report_type: str
    reviewed_on: str
    entries: tuple[ChartCapabilityEntry, ...]
    def all_release_ready(self) -> bool: ...
    def blocking_entries(self) -> tuple[ChartCapabilityEntry, ...]: ...
    def to_markdown_table(self) -> str: ...

def chart_capability_report() -> ChartCapabilityReport: ...

def keyboard_action_for_key(key: str) -> ChartKeyboardAction | None: ...

class InteractionSelection:
    x0: float
    y0: float
    x1: float
    y1: float

class ChartInteraction:
    def __init__(self, x_min: float, x_max: float, y_min: float, y_max: float) -> None: ...
    def with_log_x(self, enabled: bool = True) -> ChartInteraction: ...
    def with_log_y(self, enabled: bool = True) -> ChartInteraction: ...
    def with_size(self, width: float, height: float) -> ChartInteraction: ...
    def with_mode(self, mode: InteractionMode) -> ChartInteraction: ...
    def start_brush(self, x: float, y: float) -> None: ...
    def update_brush(self, x: float, y: float) -> None: ...
    def end_brush(self, apply_zoom: bool = False) -> InteractionSelection | None: ...
    def cancel_brush(self) -> None: ...
    def current_brush_selection(self) -> InteractionSelection | None: ...
    def is_brushing(self) -> bool: ...
    def zoom_to(self, x_min: float, x_max: float, y_min: float, y_max: float) -> None: ...
    def set_viewport_without_history(self, x_min: float, x_max: float, y_min: float, y_max: float) -> None: ...
    def reset_zoom(self) -> None: ...
    def zoom_back(self) -> bool: ...
    def is_zoomed(self) -> bool: ...
    def x_domain(self) -> tuple[float, float]: ...
    def y_domain(self) -> tuple[float, float]: ...
    def zoom_level(self) -> int: ...
    def point_to_domain(self, x: float, y: float) -> tuple[float, float]: ...
    def update_hover_pixel(self, x: float, y: float) -> tuple[float, float] | None: ...
    def clear_hover(self) -> None: ...
    def hover_domain(self) -> tuple[float, float] | None: ...
    def pan_by_pixels(self, dx: float, dy: float) -> None: ...
    def zoom_around_pixel(self, x: float, y: float, factor: float) -> None: ...
    def zoom_around_domain(self, x: float, y: float, factor: float) -> None: ...

class MeshPick:
    plot_id: str
    mesh_id: str
    cell_index: int
    cell_id: int | None
    nearest_vertex_index: int | None
    vertex_id: int | None
    world_position: tuple[float, float, float]
    displayed_value: float | None
    field_id: str | None

class MeshPickIndex:
    def __init__(
        self,
        positions: ArrayData,
        triangles: ArrayData,
        *,
        mesh_id: str = "mesh",
        plot_id: str = "mesh_plot",
        horizontal: str = "x",
        vertical: str = "y",
        field: ArrayData | None = None,
        field_association: str = "vertex",
        field_id: str = "field",
        valid: ArrayData | None = None,
        vertex_ids: ArrayData | None = None,
        cell_ids: ArrayData | None = None,
    ) -> None: ...
    def pick(self, x: float, y: float) -> MeshPick | None: ...
    @property
    def vertex_count(self) -> int: ...
    @property
    def triangle_count(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> MeshPickIndex: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class ColorScale(str, Enum):
    VIRIDIS: ColorScale
    PLASMA: ColorScale
    INFERNO: ColorScale
    MAGMA: ColorScale
    HEAT: ColorScale
    COOLWARM: ColorScale
    GREYS: ColorScale
    def map(self, value: float) -> str: ...
    def to_colormap_index(self) -> int: ...
    def to_fn(self) -> Callable[[float], str]: ...
    @classmethod
    def custom(cls, callback: Callable[[float], str]) -> CustomColorScale: ...

class CustomColorScale:
    callback: Callable[[float], str]
    def map(self, value: float) -> str: ...
    def to_colormap_index(self) -> int: ...
    def to_fn(self) -> Callable[[float], str]: ...

class AutoOrFixed:
    value: float | None
    @classmethod
    def auto(cls) -> AutoOrFixed: ...
    @classmethod
    def fixed(cls, value: float) -> AutoOrFixed: ...
    @property
    def is_auto(self) -> bool: ...

class ColorRangeError(ValueError):
    path: str
    reason: str

class ColorRange:
    kind: str
    lower: float | None
    upper: float | None
    center: float | None
    extent: AutoOrFixed | None
    @classmethod
    def auto(cls) -> ColorRange: ...
    @classmethod
    def fixed(cls, lower: float, upper: float) -> ColorRange: ...
    @classmethod
    def symmetric(cls, center: float = 0.0, extent: AutoOrFixed | None = None) -> ColorRange: ...
    def resolve(self, data_min: float, data_max: float) -> tuple[float, float]: ...
    def to_spec(self) -> str | tuple[float, float] | dict[str, float | str]: ...
class ColorbarOrientation(str, Enum):
    VERTICAL: ColorbarOrientation
    HORIZONTAL: ColorbarOrientation
class MeshPlotBackend(str, Enum):
    AUTO: MeshPlotBackend
    WGPU: MeshPlotBackend
class MeshColorbar:
    label: str
    def __init__(self, label: str) -> None: ...
    def unit(self, value: str | None) -> MeshColorbar: ...
    def scale(self, value: ColorScale | str) -> MeshColorbar: ...
    def range(self, value: ColorRange) -> MeshColorbar: ...
    def ticks(self, values: tuple[float, ...] | list[float] | None) -> MeshColorbar: ...
    def orientation(self, value: ColorbarOrientation | str) -> MeshColorbar: ...
    def to_spec(self) -> dict[str, object]: ...

class SvgExportResult:
    chart_id: str
    svg: str
    @classmethod
    def from_command(cls, result: CommandResult) -> SvgExportResult: ...

class ChartViewportResult:
    chart_id: str
    x_domain: tuple[float, float]
    y_domain: tuple[float, float]
    zoom_level: int
    is_zoomed: bool
    @classmethod
    def from_command(cls, result: CommandResult) -> ChartViewportResult: ...
class SurfaceCameraResult:
    chart_id: str
    distance: float
    azimuth: float
    elevation: float
    target: tuple[float, float, float]
    @classmethod
    def from_command(cls, result: CommandResult) -> SurfaceCameraResult: ...
class ChartAccessibilitySummary:
    chart_id: str
    chart_type: str
    title: str | None
    series_count: int
    datum_count: int
    x_range: tuple[float, float] | None
    y_range: tuple[float, float] | None
    value_range: tuple[float, float] | None
    x_scale: str | None
    y_scale: str | None
    series_labels: tuple[str, ...]
    description: str
    accessible_label: str
    accessible_value_text: str
    @classmethod
    def from_command(cls, result: CommandResult) -> ChartAccessibilitySummary: ...
class ChartLegendItem:
    series_index: int
    label: str
    color: int
    marker: str
    hidden: bool
    uses_secondary_axis: bool
class ChartLegendSummary:
    chart_type: str
    visible: bool
    position: LegendPosition
    position_explicit: bool
    items: tuple[ChartLegendItem, ...]
    description: str
class ChartAnnotationTarget:
    kind: str
    x: float | None
    y: float | None
    category: str | None
class ChartAnnotationItem:
    id: str
    label: str
    target: ChartAnnotationTarget
    color: int | None
    series_index: int | None
class ChartAnnotationSummary:
    chart_type: str
    annotations: tuple[ChartAnnotationItem, ...]
    description: str
class ChartMetadataResult:
    chart_id: str
    accessibility: ChartAccessibilitySummary
    legend: ChartLegendSummary
    annotations: ChartAnnotationSummary
    @classmethod
    def from_command(cls, result: CommandResult) -> ChartMetadataResult: ...
class StaticSvgOptions:
    width: float
    height: float
    @classmethod
    def new(cls, width: float, height: float) -> StaticSvgOptions: ...
    def margins(self, *, left: float = ..., right: float = ..., top: float = ..., bottom: float = ...) -> StaticSvgOptions: ...
    def background(self, value: str | None) -> StaticSvgOptions: ...
    def show_axes(self, value: bool) -> StaticSvgOptions: ...
    def to_spec(self) -> dict[str, object]: ...

class Annotation:
    id: str
    label: str
    target: str
    @classmethod
    def point(cls, id: str, label: str, x: float, y: float) -> Annotation: ...
    @classmethod
    def x_value(cls, id: str, label: str, x: float) -> Annotation: ...
    @classmethod
    def y_value(cls, id: str, label: str, y: float) -> Annotation: ...
    @classmethod
    def category(cls, id: str, label: str, category: str) -> Annotation: ...
    def color(self, value: str | None) -> Annotation: ...
    def series_index(self, value: int | None) -> Annotation: ...
    def to_spec(self) -> dict[str, object]: ...

class ChartBuilder:
    chart: str
    id: str
    def data(self, source: Dataset | DatasetView | ArrayData) -> ChartBuilder: ...
    def bind(self, binding: DataBinding) -> ChartBuilder: ...
    def x(self, field: str) -> ChartBuilder: ...
    def y(self, field: str) -> ChartBuilder: ...
    def y2(self, field: str) -> ChartBuilder: ...
    def y0(self, field: str) -> ChartBuilder: ...
    def color(self, field: str) -> ChartBuilder: ...
    def size(self, field: str) -> ChartBuilder: ...
    def label(self, field: str) -> ChartBuilder: ...
    def series(self, field: str) -> ChartBuilder: ...
    def dash(self, field: str) -> ChartBuilder: ...
    def row_id(self, field: str) -> ChartBuilder: ...
    def parent(self, field: str) -> ChartBuilder: ...
    def title(self, value: str | None) -> ChartBuilder: ...
    def lod(self, policy: Lod) -> ChartBuilder: ...
    def on_selection_change(self, action: str | None) -> ChartBuilder: ...
    def on_viewport_change(self, action: str | None) -> ChartBuilder: ...
    def accessibility_description(self, value: str | None) -> ChartBuilder: ...
    def legend_position(self, position: LegendPosition) -> ChartBuilder: ...
    def annotation(self, value: Annotation) -> ChartBuilder: ...
    def annotations(self, values: tuple[Annotation, ...] | list[Annotation]) -> ChartBuilder: ...
    def tiling_method(self, method: TilingMethod) -> ChartBuilder: ...
    def padding(self, value: float) -> ChartBuilder: ...
    def color_scale(self, value: ColorScale | str) -> ChartBuilder: ...
    def point_radius(self, value: float) -> ChartBuilder: ...
    def x_log(self, enabled: bool = True) -> ChartBuilder: ...
    def y_log(self, enabled: bool = True) -> ChartBuilder: ...
    def x_label(self, value: str | None) -> ChartBuilder: ...
    def y_label(self, value: str | None) -> ChartBuilder: ...
    def y2_label(self, value: str | None) -> ChartBuilder: ...
    def z_label(self, value: str | None) -> ChartBuilder: ...
    def x_range(self, minimum: float, maximum: float) -> ChartBuilder: ...
    def y_range(self, minimum: float, maximum: float) -> ChartBuilder: ...
    def y2_range(self, minimum: float, maximum: float) -> ChartBuilder: ...
    def z_range(self, minimum: float, maximum: float) -> ChartBuilder: ...
    def stroke_width(self, value: float) -> ChartBuilder: ...
    def opacity(self, value: float) -> ChartBuilder: ...
    def bar_gap(self, value: float) -> ChartBuilder: ...
    def border_radius(self, value: float) -> ChartBuilder: ...
    def box_color(self, value: str) -> ChartBuilder: ...
    def median_color(self, value: str) -> ChartBuilder: ...
    def whisker_color(self, value: str) -> ChartBuilder: ...
    def outlier_color(self, value: str) -> ChartBuilder: ...
    def box_opacity(self, value: float) -> ChartBuilder: ...
    def box_width(self, value: float) -> ChartBuilder: ...
    def outlier_radius(self, value: float) -> ChartBuilder: ...
    def bins(self, value: int) -> ChartBuilder: ...
    def wireframe(self, enabled: bool = True) -> ChartBuilder: ...
    def dimensions(self, width: float, height: float) -> ChartBuilder: ...
    def fill(self) -> ChartBuilder: ...
    def min_size(self, width: float, height: float) -> ChartBuilder: ...
    def aspect_ratio(self, value: float) -> ChartBuilder: ...
    def thresholds(self, values: tuple[float, ...] | list[float]) -> ChartBuilder: ...
    def levels(self, values: tuple[float, ...] | list[float]) -> ChartBuilder: ...
    def hole(self, fraction: float) -> ChartBuilder: ...
    def colors(self, values: tuple[str, ...] | list[str]) -> ChartBuilder: ...
    def hover(self, enabled: bool = True) -> ChartBuilder: ...
    def renderer_2d(self, renderer: Renderer2D | str) -> ChartBuilder: ...
    def vello_backend(self, backend: VelloBackend | str) -> ChartBuilder: ...
    def graph_ratio(self, value: float) -> ChartBuilder: ...
    def hidden_series(self, indices: tuple[int, ...] | list[int]) -> ChartBuilder: ...
    def on_legend_click(self, action: str | None) -> ChartBuilder: ...
    def fill_color(self, value: str) -> ChartBuilder: ...
    def primary_color(self, value: str) -> ChartBuilder: ...
    def stroke_color(self, value: str) -> ChartBuilder: ...
    def pad_angle(self, angle: float) -> ChartBuilder: ...
    def corner_radius(self, radius: float) -> ChartBuilder: ...
    def sort(self, enabled: bool = True) -> ChartBuilder: ...
    def curve(self, value: CurveType | str) -> ChartBuilder: ...
    def dash_style(self, value: str) -> ChartBuilder: ...
    def show_points(self, enabled: bool = True) -> ChartBuilder: ...
    def contour_upsample_factor(self, factor: int) -> ChartBuilder: ...
    def smooth_strokes(self, enabled: bool = True) -> ChartBuilder: ...
    def smoothing_iterations(self, iterations: int) -> ChartBuilder: ...
    def smoothing_max_deviation_px(self, deviation: float) -> ChartBuilder: ...
    def request_svg_export(self, context: SessionContext, request_id: str, *, options: StaticSvgOptions | None = None, width: float = 800.0, height: float = 600.0) -> None: ...
    def request_accessibility_summary(self, context: SessionContext, request_id: str) -> None: ...
    def request_metadata(self, context: SessionContext, request_id: str) -> None: ...
    def request_viewport(self, context: SessionContext, request_id: str) -> None: ...
    def request_camera(self, context: SessionContext, request_id: str) -> None: ...
    def reset_camera(self, context: SessionContext, request_id: str) -> None: ...
class MeshPlotBuilder:
    id: str
    @property
    def selection_action(self) -> str | None: ...
    @property
    def export_action(self) -> str | None: ...
    def geometry(self, value: MeshGeometry) -> MeshPlotBuilder: ...
    def field(self, value: MeshScalarField | None) -> MeshPlotBuilder: ...
    def revision(self, value: int) -> MeshPlotBuilder: ...
    def view(self, value: str) -> MeshPlotBuilder: ...
    def mode(self, value: str) -> MeshPlotBuilder: ...
    def color_scale(self, value: ColorScale | str) -> MeshPlotBuilder: ...
    def color_range(self, value: ColorRange | str | tuple[float, float] | dict[str, object]) -> MeshPlotBuilder: ...
    def missing_value_policy(self, value: str) -> MeshPlotBuilder: ...
    def wireframe(self, value: bool) -> MeshPlotBuilder: ...
    def title(self, value: str | None) -> MeshPlotBuilder: ...
    def size(self, width: float | None, height: float | None) -> MeshPlotBuilder: ...
    def fill(self) -> MeshPlotBuilder: ...
    def min_size(self, width: float, height: float) -> MeshPlotBuilder: ...
    def aspect_ratio(self, value: float) -> MeshPlotBuilder: ...
    def selection(self, value: dict[str, object] | None) -> MeshPlotBuilder: ...
    def camera(self, value: dict[str, object] | None) -> MeshPlotBuilder: ...
    def viewport(self, value: dict[str, object] | None) -> MeshPlotBuilder: ...
    def contour_levels(self, value: dict[str, object] | None) -> MeshPlotBuilder: ...
    def equal_aspect(self, value: bool) -> MeshPlotBuilder: ...
    def axes(self, value: dict[str, object] | None) -> MeshPlotBuilder: ...
    def interactions(self, values: tuple[str, ...] | list[str]) -> MeshPlotBuilder: ...
    def toolbar(self, enabled: bool) -> MeshPlotBuilder: ...
    def toolbar_action_hidden(self, action: str, hidden: bool = True) -> MeshPlotBuilder: ...
    def colorbar(self, value: MeshColorbar | None) -> MeshPlotBuilder: ...
    def renderer_backend(self, value: MeshPlotBackend | str) -> MeshPlotBuilder: ...
    def revolve(self, value: MeshRevolve | None) -> MeshPlotBuilder: ...
    def on_selection_change(self, action: str | None) -> MeshPlotBuilder: ...
    def on_export(self, action: str | None) -> MeshPlotBuilder: ...
    def to_plot(self) -> MeshPlotSpec: ...
    def to_spec(self) -> dict[str, object]: ...
    def request_svg_export(self, context: SessionContext, request_id: str, *, options: StaticSvgOptions | None = None, width: float = 800.0, height: float = 600.0) -> None: ...
    def request_accessibility_summary(self, context: SessionContext, request_id: str) -> None: ...
def scatter(id: str = "scatter") -> ChartBuilder: ...
def line(id: str = "line") -> ChartBuilder: ...
def area(id: str = "area") -> ChartBuilder: ...
def boxplot(id: str = "boxplot") -> ChartBuilder: ...
def heatmap(id: str = "heatmap") -> ChartBuilder: ...
def contour(id: str = "contour") -> ChartBuilder: ...
def isoline(id: str = "isoline") -> ChartBuilder: ...
def surface(id: str = "surface") -> ChartBuilder: ...
def pie(id: str = "pie") -> ChartBuilder: ...
def donut(id: str = "donut") -> ChartBuilder: ...
def bar(id: str = "bar") -> ChartBuilder: ...
def treemap(id: str = "treemap") -> ChartBuilder: ...
def mesh(id: str = "mesh_plot") -> MeshPlotBuilder: ...
def mesh_geometry(positions: Resource | ArrayData, triangles: Resource | ArrayData, *, id: str = "mesh", vertex_ids: Resource | ArrayData | None = None, cell_ids: Resource | ArrayData | None = None) -> MeshGeometry: ...
def mesh_field(values: Resource | ArrayData, *, association: str = "vertex", id: str = "field", label: str | None = None, unit: str | None = None, valid: Resource | ArrayData | None = None) -> MeshScalarField: ...
def mesh_plot(
    geometry: MeshGeometry,
    field: MeshScalarField | None = None,
    *,
    id: str = "mesh_plot",
    revision: int = 0,
    view: str = "planar",
    mode: str = "mesh",
    color_scale: str = "viridis",
    color_range: str | tuple[float, float] | dict[str, object] = "auto",
    missing_value_policy: str = "reject",
    wireframe: bool = True,
    title: str | None = None,
    width: float | None = None,
    height: float | None = None,
    selection: dict[str, object] | None = None,
    camera: dict[str, object] | None = None,
    viewport: dict[str, object] | None = None,
    contour_levels: dict[str, object] | None = None,
    equal_aspect: bool = True,
    axes: dict[str, object] | None = None,
    interactions: tuple[str, ...] = ("pan", "zoom", "inspect", "select", "reset", "fit"),
    revolve: MeshRevolve | None = None,
) -> MeshPlotSpec: ...
def request_mesh_svg_export(plot: MeshPlotSpec, context: SessionContext, request_id: str, *, options: StaticSvgOptions | None = None, width: float = 800.0, height: float = 600.0) -> None: ...
