[package]
name = "perf"
version = "0.1.0"
edition = "2024"
description = "A tool for measuring Zed test performance, with too many Clippy lints"
license = "Apache-2.0"
publish = false

[dependencies]
collections = { version = "0.1.0", git = "https://github.com/zed-industries/zed.git", tag = "v1.9.0" }
serde = { version = "1.0.221", features = ["derive", "rc"] }
serde_json = { version = "1.0.144", features = ["preserve_order", "raw_value"] }
