// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::borrow::Cow;
use std::cell::RefCell;

use crate::analysis::{AnalysisChunk, SegmentBreakKind};
use crate::line_break::PreparedLineChunk;
/// Main public API for text measurement and layout, ported from chenglou/pretext.
///
/// Two-phase approach:
/// 1. **Prepare**: Analyze and measure text once, producing a `PreparedText`.
/// 2. **Layout**: Use cached widths for fast arithmetic-only line breaking.
use unicode_segmentation::UnicodeSegmentation;

thread_local! {
    /// Reusable buffer for building line text on layout paths.
    static LINE_TEXT_SCRATCH: RefCell<String> = const { RefCell::new(String::new()) };
}

/// Run `f` with a cleared thread-local line-text scratch buffer.
pub(super) fn with_line_text_scratch<R>(f: impl FnOnce(&mut String) -> R) -> R {
    LINE_TEXT_SCRATCH.with(|scratch| {
        let mut scratch = scratch.borrow_mut();
        scratch.clear();
        f(&mut scratch)
    })
}

pub(super) fn map_analysis_chunks_to_prepared_chunks(
    chunks: &[AnalysisChunk],
    prepared_start_by_analysis: &[usize],
    prepared_end_by_analysis: &[usize],
) -> Vec<PreparedLineChunk> {
    let fallback = prepared_end_by_analysis.last().copied().unwrap_or(0);

    chunks
        .iter()
        .map(|chunk| {
            let start = if chunk.start_segment_index < prepared_start_by_analysis.len() {
                prepared_start_by_analysis[chunk.start_segment_index]
            } else {
                fallback
            };
            let end = if chunk.end_segment_index < prepared_start_by_analysis.len() {
                prepared_start_by_analysis[chunk.end_segment_index]
            } else {
                fallback
            };
            let consumed_end =
                if chunk.consumed_end_segment_index < prepared_start_by_analysis.len() {
                    prepared_start_by_analysis[chunk.consumed_end_segment_index]
                } else {
                    fallback
                };
            PreparedLineChunk {
                start_segment_index: start,
                end_segment_index: end,
                consumed_end_segment_index: consumed_end,
            }
        })
        .collect()
}

pub(super) fn line_has_discretionary_hyphen(
    kinds: &[SegmentBreakKind],
    start_seg: usize,
    start_graph: usize,
    end_seg: usize,
) -> bool {
    end_seg > 0
        && kinds[end_seg - 1] == SegmentBreakKind::SoftHyphen
        && !(start_seg == end_seg && start_graph > 0)
}

#[cfg(test)]
pub(super) fn build_line_text(
    segments: &[String],
    kinds: &[SegmentBreakKind],
    start_seg: usize,
    start_graph: usize,
    end_seg: usize,
    end_graph: usize,
) -> String {
    let mut text = String::new();
    build_line_text_into(
        segments,
        kinds,
        start_seg,
        start_graph,
        end_seg,
        end_graph,
        &mut text,
    );
    text
}

pub(super) fn build_line_text_into(
    segments: &[String],
    kinds: &[SegmentBreakKind],
    start_seg: usize,
    start_graph: usize,
    end_seg: usize,
    end_graph: usize,
    buf: &mut String,
) {
    let has_hyphen = line_has_discretionary_hyphen(kinds, start_seg, start_graph, end_seg);

    for i in start_seg..end_seg {
        if kinds[i] == SegmentBreakKind::SoftHyphen || kinds[i] == SegmentBreakKind::HardBreak {
            continue;
        }
        if i == start_seg && start_graph > 0 {
            for (_, g) in segments[i].grapheme_indices(true).skip(start_graph) {
                buf.push_str(g);
            }
        } else {
            buf.push_str(&segments[i]);
        }
    }

    if end_graph > 0 && end_seg < segments.len() {
        if has_hyphen {
            buf.push('-');
        }
        let skip = if start_seg == end_seg { start_graph } else { 0 };
        let take_count = end_graph.saturating_sub(skip);
        for (_, g) in segments[end_seg]
            .grapheme_indices(true)
            .skip(skip)
            .take(take_count)
        {
            buf.push_str(g);
        }
    } else if has_hyphen {
        buf.push('-');
    }
}

/// Build line text, borrowing from `segments` when the line covers exactly one
/// whole segment. This avoids a fresh allocation for the common single-word
/// line case.
pub(super) fn build_line_text_cow<'a>(
    segments: &'a [String],
    kinds: &[SegmentBreakKind],
    start_seg: usize,
    start_graph: usize,
    end_seg: usize,
    end_graph: usize,
) -> Cow<'a, str> {
    // Fast path: the line spans exactly one whole prepared segment.
    if start_graph == 0 && end_graph == 0 && start_seg + 1 == end_seg && start_seg < segments.len()
    {
        return Cow::Borrowed(&segments[start_seg]);
    }

    with_line_text_scratch(|scratch| {
        build_line_text_into(
            segments,
            kinds,
            start_seg,
            start_graph,
            end_seg,
            end_graph,
            scratch,
        );
        Cow::Owned(scratch.clone())
    })
}
