// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::borrow::Cow;

use super::types::LayoutCursor;
use super::types::LayoutLineRange;
use super::types::PreparedCore;
use crate::line_break::{InternalLayoutLine, PreparedLineBreakData};

pub(super) fn to_line_break_data(core: &PreparedCore) -> PreparedLineBreakData<'_> {
    PreparedLineBreakData {
        widths: Cow::Borrowed(&core.widths),
        line_end_fit_advances: Cow::Borrowed(&core.line_end_fit_advances),
        line_end_paint_advances: Cow::Borrowed(&core.line_end_paint_advances),
        kinds: Cow::Borrowed(&core.kinds),
        simple_line_walk_fast_path: core.simple_line_walk_fast_path,
        breakable_widths: Cow::Borrowed(&core.breakable_widths),
        breakable_prefix_widths: Cow::Borrowed(&core.breakable_prefix_widths),
        discretionary_hyphen_width: core.discretionary_hyphen_width,
        tab_stop_advance: core.tab_stop_advance,
        chunks: Cow::Borrowed(&core.chunks),
        start_segment: 0,
        end_segment: core.widths.len(),
        kp_item_cache: Some(&core.kp_item_cache),
    }
}

pub(super) fn to_layout_line_range(line: &InternalLayoutLine) -> LayoutLineRange {
    LayoutLineRange {
        width: line.width,
        start: LayoutCursor {
            segment_index: line.start_segment_index,
            grapheme_index: line.start_grapheme_index,
        },
        end: LayoutCursor {
            segment_index: line.end_segment_index,
            grapheme_index: line.end_grapheme_index,
        },
    }
}
