// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use d3rs::shape::{LinePoint, StrokeDashArray};
use gpui::{App, Window};
use std::rc::Rc;
use std::sync::Arc;

pub(super) type LineDataCache = Option<(Arc<[f64]>, Arc<[f64]>, Arc<[LinePoint]>)>;

/// Position of the legend relative to the chart
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub enum LegendPosition {
    /// Legend on the right side of the chart (default)
    #[default]
    Right,
    /// Legend on the left side of the chart
    Left,
    /// Legend above the chart
    Top,
    /// Legend below the chart
    Bottom,
    /// Legend is hidden
    Hidden,
}

/// A single series in a line chart
#[derive(Debug, Clone)]
pub(super) struct LineSeries {
    /// Optional custom X values (if None, uses the primary X values)
    pub(super) x: Option<Arc<[f64]>>,
    pub(super) y: Arc<[f64]>,
    pub(super) label: Option<String>,
    pub(super) color: u32,
    pub(super) stroke_width: f32,
    pub(super) opacity: f32,
    /// Whether this series uses the secondary (right) Y-axis
    pub(super) use_secondary_axis: bool,
    /// Optional dash pattern for this series
    pub(super) dash_array: Option<StrokeDashArray>,
    /// Cache of mapped points keyed by source `(x, y)` `Arc` pointer equality.
    pub(super) data_cache: LineDataCache,
}

/// Callback type for legend click events
pub type LegendClickCallback = Rc<dyn Fn(usize, &mut Window, &mut App)>;
