// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::Theme;
use std::sync::Arc;

/// Extension trait for easy theme access
pub trait ThemeExt {
    /// Get the current theme as a cheap-to-clone `Arc<Theme>`.
    fn theme(&self) -> Arc<Theme>;
}
