[package]
name = "gpui-android"
version = "0.9.4"
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Android platform backend for GPUI"
license.workspace = true
publish = false

[lib]
crate-type = ["rlib"]

[features]
default = []
autoeq = []
deeplink = []
gpu-2d = []
gpu-3d = []
media_session = []
reqwest = []
showcase = []
spinorama = []
tokio = []
urlencoding = []

[dependencies]
accesskit = "0.24.0"
anyhow = { workspace = true }
futures = { workspace = true }
gpui = { workspace = true }
gpui_wgpu = { workspace = true }
log = { workspace = true, features = ["kv_unstable_serde", "serde"] }
parking_lot = { workspace = true }
raw-window-handle = { workspace = true }
smallvec = { workspace = true, features = ["union", "const_new"] }
serde_json = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
android-activity = { workspace = true }
android_logger = { workspace = true }
jni = { workspace = true }
libc = { workspace = true }
ndk = { workspace = true, features = ["nativewindow"] }
ndk-context = { workspace = true }
ndk-sys = { workspace = true }
rustc-hash = { workspace = true }
uuid = { workspace = true, features = ["v5"] }
