// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::scale::Scale;
use gpui::prelude::*;
use gpui::*;

use super::*;
use crate::scale::{LinearScale, Scale};

#[test]
fn test_line_y_rel_inverted_range_with_zero() {
    // Inverted range where y_min == 0.0 used to divide by zero
    let y_scale = LinearScale::new().domain(0.0, 100.0).range(0.0, -100.0);
    let (y_min, y_max) = y_scale.range();
    assert_eq!(y_min, 0.0);
    assert_eq!(y_max, -100.0);

    // Simulate the y_rel calculation logic inline
    let y_range = y_scale.scale(50.0); // should be -50.0
    let y_range_span = y_max - y_min;
    assert!(y_range_span != 0.0);
    let y_rel = if y_min > y_max {
        ((y_range - y_max) / (y_min - y_max)) as f32
    } else {
        ((y_range - y_min) / y_range_span) as f32
    };
    // 50% of domain should map to middle of relative coords
    assert!(
        (y_rel - 0.5).abs() < 1e-5,
        "y_rel should be 0.5, got {}",
        y_rel
    );
}

#[test]
fn test_line_flat_range() {
    let y_scale = LinearScale::new().domain(0.0, 100.0).range(50.0, 50.0);
    let (y_min, y_max) = y_scale.range();
    let y_range = y_scale.scale(25.0);
    let y_range_span = y_max - y_min;
    assert_eq!(y_range_span, 0.0);
    let y_rel = if y_range_span == 0.0 {
        0.5_f32
    } else if y_min > y_max {
        ((y_range - y_max) / (y_min - y_max)) as f32
    } else {
        ((y_range - y_min) / y_range_span) as f32
    };
    assert_eq!(y_rel, 0.5);
}


#[test]
fn test_compute_line_segments_linear() {
    use super::{compute_line_segments, CurveType};

    let points = vec![(-0.2, 0.5), (0.5, 0.5), (1.2, 0.5)];
    let segments = compute_line_segments(&points, CurveType::Linear);

    // Points outside [0,1] should be clipped, leaving a single visible segment.
    assert_eq!(segments.len(), 1);
    let (x0, y0, x1, y1) = segments[0];
    assert_eq!(y0, 0.5);
    assert_eq!(y1, 0.5);
    assert!(x0 >= 0.0);
    assert!(x1 <= 1.0);
}
