// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::apply_features_and_fallbacks;
use super::misc::kCGImageAlphaOnly;
use super::misc::recti_to_bounds_device_pixels;
use super::string_index_converter::StringIndexConverter;
use super::types::FontKey;
use anyhow::anyhow;
use core_foundation::{
    attributed_string::CFMutableAttributedString,
    base::{CFRange, TCFType},
    number::CFNumber,
    string::CFString,
};
use core_graphics::{
    base::{CGFloat, CGGlyph, kCGImageAlphaPremultipliedLast},
    color_space::CGColorSpace,
    context::{CGContext, CGTextDrawingMode},
    geometry::CGPoint,
};
use core_text::{
    font::CTFont,
    font_descriptor::{
        kCTFontSlantTrait, kCTFontSymbolicTrait, kCTFontWeightTrait, kCTFontWidthTrait,
    },
    line::CTLine,
    string_attributes::kCTFontAttributeName,
};
use font_kit::{
    font::Font as FontKitFont, handle::Handle, hinting::HintingOptions, source::SystemSource,
    sources::mem::MemSource,
};
use gpui::{
    Bounds, DevicePixels, Font, FontFallbacks, FontFeatures, FontId, FontRun, GlyphId, LineLayout,
    Pixels, RenderGlyphParams, Result, SUBPIXEL_VARIANTS_X, ShapedGlyph, ShapedRun, Size, point,
    px,
};
use pathfinder_geometry::transform2d::Transform2F;
use smallvec::SmallVec;
use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use std::{borrow::Cow, cell::RefCell, char, sync::Arc};

thread_local! {
    /// Reusable bitmap scratch buffer for glyph rasterization.
    static GLYPH_BITMAP_SCRATCH: RefCell<Vec<u8>> = const { RefCell::new(Vec::new()) };
}

#[derive(Clone, Debug)]
pub(super) struct LayoutCacheKey {
    text: Arc<str>,
    font_size: Pixels,
    runs: SmallVec<[FontRun; 2]>,
}

impl PartialEq for LayoutCacheKey {
    fn eq(&self, other: &Self) -> bool {
        self.text == other.text
            && self.font_size.as_f32().to_bits() == other.font_size.as_f32().to_bits()
            && self.runs == other.runs
    }
}

impl Eq for LayoutCacheKey {}

impl Hash for LayoutCacheKey {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.text.hash(state);
        self.font_size.as_f32().to_bits().hash(state);
        self.runs.hash(state);
    }
}

pub(super) struct AuTextSystemState {
    pub(super) memory_source: MemSource,
    pub(super) system_source: SystemSource,
    pub(super) fonts: Vec<FontKitFont>,
    pub(super) font_selections: HashMap<Font, FontId>,
    pub(super) font_ids_by_postscript_name: HashMap<String, FontId>,
    pub(super) font_ids_by_font_key: HashMap<Arc<FontKey>, SmallVec<[FontId; 4]>>,
    pub(super) postscript_names_by_font_id: HashMap<FontId, String>,
    pub(super) is_emoji: Vec<bool>,
    pub(super) layout_cache: HashMap<LayoutCacheKey, Arc<LineLayout>>,
}

impl AuTextSystemState {
    pub(super) fn add_fonts(&mut self, fonts: Vec<Cow<'static, [u8]>>) -> Result<()> {
        let fonts = fonts
            .into_iter()
            .map(|bytes| match bytes {
                Cow::Borrowed(embedded_font) => {
                    let data_provider = unsafe {
                        core_graphics::data_provider::CGDataProvider::from_slice(embedded_font)
                    };
                    let font = core_graphics::font::CGFont::from_data_provider(data_provider)
                        .map_err(|()| anyhow!("Could not load an embedded font."))?;
                    let font = font_kit::loaders::core_text::Font::from_core_graphics_font(font);
                    Ok(Handle::from_native(&font))
                }
                Cow::Owned(bytes) => Ok(Handle::from_memory(Arc::new(bytes), 0)),
            })
            .collect::<Result<Vec<_>>>()?;
        self.memory_source.add_fonts(fonts.into_iter())?;
        Ok(())
    }

    pub(super) fn load_family(
        &mut self,
        name: &str,
        features: &FontFeatures,
        fallbacks: Option<&FontFallbacks>,
    ) -> Result<SmallVec<[FontId; 4]>> {
        let mut font_ids = SmallVec::new();
        // Map virtual font names to iOS equivalents.
        // gpui uses ".SystemUIFont", gpui-ui-kit theme uses ".SystemUI" — both
        // must resolve to the iOS system font (.AppleSystemUIFont = San Francisco).
        let name = gpui::font_name_with_fallbacks(name, ".AppleSystemUIFont");
        let name = match name {
            ".SystemUI" => ".AppleSystemUIFont",
            _ => name,
        };
        let family = self
            .memory_source
            .select_family_by_name(name)
            .or_else(|_| self.system_source.select_family_by_name(name))?;
        for font in family.fonts() {
            let mut font = font.load()?;
            apply_features_and_fallbacks(&mut font, features, fallbacks)?;
            {
                let has_m_glyph = font.glyph_for_char('m').is_some();
                let is_segoe_fluent_icons = font.full_name() == "Segoe Fluent Icons";
                if !has_m_glyph && !is_segoe_fluent_icons {
                    log::warn!(
                        "font '{}' has no 'm' character and was not loaded",
                        font.full_name()
                    );
                    continue;
                }
            }
            let traits = font.native_font().all_traits();
            if unsafe {
                !(traits
                    .get(kCTFontSymbolicTrait)
                    .downcast::<CFNumber>()
                    .is_some()
                    && traits
                        .get(kCTFontWidthTrait)
                        .downcast::<CFNumber>()
                        .is_some()
                    && traits
                        .get(kCTFontWeightTrait)
                        .downcast::<CFNumber>()
                        .is_some()
                    && traits
                        .get(kCTFontSlantTrait)
                        .downcast::<CFNumber>()
                        .is_some())
            } {
                log::error!(
                    "Failed to read traits for font {}",
                    font.postscript_name().as_deref().unwrap_or("<unknown>")
                );
                continue;
            }
            let font_id = FontId(self.fonts.len());
            font_ids.push(font_id);
            let postscript_name = font.postscript_name();
            let is_emoji = postscript_name.as_deref() == Some("AppleColorEmoji")
                || postscript_name.as_deref() == Some(".AppleColorEmojiUI");
            if let Some(postscript_name) = postscript_name {
                self.font_ids_by_postscript_name
                    .insert(postscript_name.clone(), font_id);
                self.postscript_names_by_font_id
                    .insert(font_id, postscript_name);
            } else {
                log::warn!(
                    "Font '{}' has no PostScript name; skipping name-based lookups",
                    font.full_name()
                );
            }
            self.is_emoji.push(is_emoji);
            self.fonts.push(font);
        }
        Ok(font_ids)
    }

    pub(super) fn glyph_for_char(&self, font_id: FontId, ch: char) -> Option<GlyphId> {
        self.fonts[font_id.0].glyph_for_char(ch).map(GlyphId)
    }

    pub(super) fn id_for_native_font(&mut self, requested_font: CTFont) -> FontId {
        let postscript_name = requested_font.postscript_name();
        if let Some(font_id) = self.font_ids_by_postscript_name.get(&postscript_name) {
            *font_id
        } else {
            let font_id = FontId(self.fonts.len());
            let is_emoji =
                postscript_name == "AppleColorEmoji" || postscript_name == ".AppleColorEmojiUI";
            self.font_ids_by_postscript_name
                .insert(postscript_name.clone(), font_id);
            self.postscript_names_by_font_id
                .insert(font_id, postscript_name);
            self.is_emoji.push(is_emoji);
            self.fonts
                .push(font_kit::font::Font::from_core_graphics_font(
                    requested_font.copy_to_CGFont(),
                ));
            font_id
        }
    }

    pub(super) fn is_emoji(&self, font_id: FontId) -> bool {
        self.is_emoji.get(font_id.0).copied().unwrap_or(false)
    }

    pub(super) fn raster_bounds(&self, params: &RenderGlyphParams) -> Result<Bounds<DevicePixels>> {
        let font = &self.fonts[params.font_id.0];
        let scale = Transform2F::from_scale(params.scale_factor);
        Ok(recti_to_bounds_device_pixels(font.raster_bounds(
            params.glyph_id.0,
            params.font_size.into(),
            scale,
            HintingOptions::None,
            font_kit::canvas::RasterizationOptions::GrayscaleAa,
        )?))
    }

    pub(super) fn rasterize_glyph(
        &self,
        params: &RenderGlyphParams,
        glyph_bounds: Bounds<DevicePixels>,
    ) -> Result<(Size<DevicePixels>, Vec<u8>)> {
        if glyph_bounds.size.width.0 == 0 || glyph_bounds.size.height.0 == 0 {
            anyhow::bail!("glyph bounds are empty");
        }
        let mut bitmap_size = glyph_bounds.size;
        if params.subpixel_variant.x > 0 {
            bitmap_size.width += DevicePixels(1);
        }
        if params.subpixel_variant.y > 0 {
            bitmap_size.height += DevicePixels(1);
        }
        let bitmap_size = bitmap_size;
        let needed = if params.is_emoji {
            bitmap_size.width.0 as usize * 4 * bitmap_size.height.0 as usize
        } else {
            bitmap_size.width.0 as usize * bitmap_size.height.0 as usize
        };
        let mut bitmap = vec![0u8; needed];

        GLYPH_BITMAP_SCRATCH.with(|scratch| {
            let mut scratch = scratch.borrow_mut();
            scratch.resize(needed, 0);
            let (color_space, alpha_info, bytes_per_row) = if params.is_emoji {
                (
                    CGColorSpace::create_device_rgb(),
                    kCGImageAlphaPremultipliedLast,
                    bitmap_size.width.0 as usize * 4,
                )
            } else {
                (
                    CGColorSpace::create_device_gray(),
                    kCGImageAlphaOnly,
                    bitmap_size.width.0 as usize,
                )
            };
            let cx = CGContext::create_bitmap_context(
                Some(scratch.as_mut_ptr() as *mut _),
                bitmap_size.width.0 as usize,
                bitmap_size.height.0 as usize,
                8,
                bytes_per_row,
                &color_space,
                alpha_info,
            );
            cx.translate(
                -glyph_bounds.origin.x.0 as CGFloat,
                (glyph_bounds.origin.y.0 + glyph_bounds.size.height.0) as CGFloat,
            );
            cx.scale(
                params.scale_factor as CGFloat,
                params.scale_factor as CGFloat,
            );
            let subpixel_shift = params
                .subpixel_variant
                .map(|v| v as f32 / SUBPIXEL_VARIANTS_X as f32);
            cx.set_text_drawing_mode(CGTextDrawingMode::CGTextFill);
            cx.set_gray_fill_color(0.0, 1.0);
            cx.set_allows_antialiasing(true);
            cx.set_should_antialias(true);
            cx.set_allows_font_subpixel_positioning(true);
            cx.set_should_subpixel_position_fonts(true);
            cx.set_allows_font_subpixel_quantization(false);
            cx.set_should_subpixel_quantize_fonts(false);
            self.fonts[params.font_id.0]
                .native_font()
                .clone_with_font_size(f32::from(params.font_size) as CGFloat)
                .draw_glyphs(
                    &[params.glyph_id.0 as CGGlyph],
                    &[CGPoint::new(
                        (subpixel_shift.x / params.scale_factor) as CGFloat,
                        (subpixel_shift.y / params.scale_factor) as CGFloat,
                    )],
                    cx,
                );
            if params.is_emoji {
                for pixel in scratch.chunks_exact_mut(4) {
                    gpui::swap_rgba_pa_to_bgra(pixel);
                }
            }
            bitmap.copy_from_slice(&scratch[..needed]);
        });
        Ok((bitmap_size, bitmap))
    }

    pub(super) fn layout_line(
        &mut self,
        text: &str,
        font_size: Pixels,
        font_runs: &[FontRun],
    ) -> LineLayout {
        let key = LayoutCacheKey {
            text: text.into(),
            font_size,
            runs: font_runs.iter().copied().collect(),
        };
        if let Some(cached) = self.layout_cache.get(&key) {
            let cached = Arc::clone(cached);
            return LineLayout {
                font_size: cached.font_size,
                width: cached.width,
                ascent: cached.ascent,
                descent: cached.descent,
                runs: cached.runs.clone(),
                len: cached.len,
            };
        }

        let result = self.layout_line_uncached(text, font_size, font_runs);
        self.layout_cache
            .insert(key, Arc::new(Self::clone_layout(&result)));
        result
    }

    fn clone_layout(layout: &LineLayout) -> LineLayout {
        LineLayout {
            font_size: layout.font_size,
            width: layout.width,
            ascent: layout.ascent,
            descent: layout.descent,
            runs: layout.runs.clone(),
            len: layout.len,
        }
    }

    fn layout_line_uncached(
        &mut self,
        text: &str,
        font_size: Pixels,
        font_runs: &[FontRun],
    ) -> LineLayout {
        let mut string = CFMutableAttributedString::new();
        let mut max_ascent = 0.0f32;
        let mut max_descent = 0.0f32;
        {
            let mut text = text;
            let mut break_ligature = true;
            for run in font_runs {
                let text_run;
                (text_run, text) = text.split_at(run.len);
                let utf16_start = string.char_len();
                string.replace_str(&CFString::new(text_run), CFRange::init(utf16_start, 0));
                let utf16_end = string.char_len();
                let length = utf16_end - utf16_start;
                let cf_range = CFRange::init(utf16_start, length);
                let font = &self.fonts[run.font_id.0];
                let font_metrics = font.metrics();
                let font_scale = font_size.as_f32() / font_metrics.units_per_em as f32;
                max_ascent = max_ascent.max(font_metrics.ascent * font_scale);
                max_descent = max_descent.max(-font_metrics.descent * font_scale);
                let run_font_size = if break_ligature {
                    px(font_size.as_f32().next_up())
                } else {
                    font_size
                };
                unsafe {
                    string.set_attribute(
                        cf_range,
                        kCTFontAttributeName,
                        &font
                            .native_font()
                            .clone_with_font_size(run_font_size.into()),
                    );
                }
                break_ligature = !break_ligature;
            }
        }
        let line = CTLine::new_with_attributed_string(string.as_concrete_TypeRef());
        let glyph_runs = line.glyph_runs();
        let mut runs = <Vec<ShapedRun>>::with_capacity(glyph_runs.len() as usize);
        let mut ix_converter = StringIndexConverter::new(text);
        for run in glyph_runs.into_iter() {
            let attributes = run.attributes().unwrap();
            let font = unsafe {
                attributes
                    .get(kCTFontAttributeName)
                    .downcast::<CTFont>()
                    .unwrap()
            };
            let font_id = self.id_for_native_font(font);
            let glyphs = match runs.last_mut() {
                Some(run) if run.font_id == font_id => &mut run.glyphs,
                _ => {
                    runs.push(ShapedRun {
                        font_id,
                        glyphs: Vec::with_capacity(run.glyph_count().try_into().unwrap_or(0)),
                    });
                    &mut runs.last_mut().unwrap().glyphs
                }
            };
            for ((&glyph_id, position), &glyph_utf16_ix) in run
                .glyphs()
                .iter()
                .zip(run.positions().iter())
                .zip(run.string_indices().iter())
            {
                let glyph_utf16_ix = usize::try_from(glyph_utf16_ix).unwrap();
                ix_converter.rewind_to_utf16_ix(glyph_utf16_ix);
                glyphs.push(ShapedGlyph {
                    id: GlyphId(glyph_id as u32),
                    position: point(position.x as f32, position.y as f32).map(px),
                    index: ix_converter.utf8_ix,
                    is_emoji: self.is_emoji(font_id),
                });
            }
        }
        let typographic_bounds = line.get_typographic_bounds();
        LineLayout {
            runs,
            font_size,
            width: typographic_bounds.width.into(),
            ascent: max_ascent.into(),
            descent: max_descent.into(),
            len: text.len(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use font_kit::source::SystemSource;
    use gpui::{DevicePixels, FontRun, GlyphId, point, px, size};

    fn empty_state() -> AuTextSystemState {
        AuTextSystemState {
            memory_source: MemSource::empty(),
            system_source: SystemSource::new(),
            fonts: Vec::new(),
            font_selections: HashMap::default(),
            font_ids_by_postscript_name: HashMap::default(),
            font_ids_by_font_key: HashMap::default(),
            postscript_names_by_font_id: HashMap::default(),
            is_emoji: Vec::new(),
            layout_cache: HashMap::default(),
        }
    }

    fn load_system_family(state: &mut AuTextSystemState, family: &str) -> Option<FontId> {
        state
            .load_family(family, &Default::default(), None)
            .ok()
            .and_then(|ids| ids.first().copied())
    }

    #[test]
    fn test_is_emoji_caches_bool() {
        let mut state = empty_state();
        assert!(!state.is_emoji(FontId(0)));

        if let Some(regular_id) = load_system_family(&mut state, "Helvetica") {
            assert!(!state.is_emoji(regular_id));
        }

        if let Some(emoji_id) = load_system_family(&mut state, "AppleColorEmoji") {
            assert!(state.is_emoji(emoji_id));
        }
    }

    #[test]
    fn test_rasterize_glyph_empty_bounds_errors() {
        let state = empty_state();
        let params = gpui::RenderGlyphParams {
            font_id: FontId(0),
            glyph_id: GlyphId(0),
            font_size: px(12.0),
            subpixel_variant: point(0, 0),
            scale_factor: 1.0,
            is_emoji: false,
            subpixel_rendering: false,
        };
        let bounds = Bounds {
            origin: point(DevicePixels(0), DevicePixels(0)),
            size: size(DevicePixels(0), DevicePixels(0)),
        };
        assert!(state.rasterize_glyph(&params, bounds).is_err());
    }

    #[test]
    fn test_layout_line_empty_text() {
        let mut state = empty_state();
        let layout = state.layout_line("", px(12.0), &[]);
        assert_eq!(layout.width, px(0.0));
        assert_eq!(layout.len, 0);
    }

    #[test]
    fn test_layout_line_repeated_text_is_consistent() {
        let mut state = empty_state();
        let font_id = match load_system_family(&mut state, ".AppleSystemUIFont") {
            Some(id) => id,
            None => {
                // System font may not be available in all test environments.
                return;
            }
        };
        let text = "hello";
        let runs = [FontRun {
            font_id,
            len: text.len(),
        }];
        let layout1 = state.layout_line(text, px(12.0), &runs);
        let layout2 = state.layout_line(text, px(12.0), &runs);
        assert_eq!(layout1.width, layout2.width);
        assert_eq!(layout1.len, layout2.len);
    }

    #[test]
    fn test_string_index_converter_rewind() {
        let mut converter = StringIndexConverter::new("aéb");
        converter.advance_to_utf16_ix(2);
        assert_eq!(converter.utf8_ix, 3);
        assert_eq!(converter.utf16_ix, 2);
        converter.rewind_to_utf16_ix(1);
        assert_eq!(converter.utf8_ix, 1);
        assert_eq!(converter.utf16_ix, 1);
    }

    #[test]
    fn test_layout_line_uses_cache_for_repeated_calls() {
        let mut state = empty_state();
        let font_id = match load_system_family(&mut state, ".AppleSystemUIFont") {
            Some(id) => id,
            None => {
                // System font may not be available in all test environments.
                return;
            }
        };
        let text = "cache me";
        let runs = [FontRun {
            font_id,
            len: text.len(),
        }];

        let layout1 = state.layout_line(text, px(12.0), &runs);
        let cached_count_after_first = state.layout_cache.len();

        let layout2 = state.layout_line(text, px(12.0), &runs);
        let cached_count_after_second = state.layout_cache.len();

        assert_eq!(layout1.width, layout2.width);
        assert_eq!(layout1.len, layout2.len);
        assert_eq!(layout1.runs.len(), layout2.runs.len());
        assert!(
            cached_count_after_first > 0,
            "first layout should populate the cache"
        );
        assert_eq!(
            cached_count_after_first, cached_count_after_second,
            "second layout should reuse the cached entry"
        );
    }
}
