// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::types::LayoutIssueKind;
use super::validate::validate_layout;
use crate::{Axis, ContainerNode, DisplayTier, LayoutNode, Sizing, SlotNode};

#[test]
fn clean_layout_has_no_issues() {
    static TIERS: &[DisplayTier<'_>] = &[
        DisplayTier {
            name: "Full",
            min_size: 200.0,
        },
        DisplayTier {
            name: "Mini",
            min_size: 80.0,
        },
    ];
    let children = [
        LayoutNode::Slot(SlotNode {
            id: "main",
            sizing: Sizing::flex(200.0),
            priority: 1.0,
            collapsible: false,
            display_tiers: TIERS,
            collapse_label: None,
        }),
        LayoutNode::Slot(SlotNode {
            id: "inspector",
            sizing: Sizing::fractional(0.25, 80.0),
            priority: 0.4,
            collapsible: true,
            display_tiers: &[],
            collapse_label: Some("Inspector"),
        }),
    ];
    let root = LayoutNode::Container(ContainerNode {
        id: "root",
        axis: Axis::Horizontal,
        auto_axis: Some(1.0),
        sizing: Sizing::flex(0.0),
        children: &children,
        divider_size: 6.0,
    });

    let report = validate_layout(&root);

    assert!(report.is_clean(), "{report}");
    assert_eq!(report.to_text(), "layout validation: clean\n");
}

#[test]
fn validation_report_text_is_stable() {
    let children = [
        LayoutNode::Slot(SlotNode {
            id: "panel",
            sizing: Sizing::Fixed(-1.0),
            priority: 1.5,
            collapsible: true,
            display_tiers: &[],
            collapse_label: None,
        }),
        LayoutNode::Slot(SlotNode {
            id: "panel",
            sizing: Sizing::flex(20.0),
            priority: 1.0,
            collapsible: false,
            display_tiers: &[],
            collapse_label: None,
        }),
    ];
    let root = LayoutNode::Container(ContainerNode {
        id: "root",
        axis: Axis::Horizontal,
        auto_axis: Some(0.0),
        sizing: Sizing::flex(0.0),
        children: &children,
        divider_size: -2.0,
    });

    let report = validate_layout(&root);

    assert!(report.has_errors());
    assert!(report.has_warnings());
    assert_eq!(report.error_count(), 4);
    assert_eq!(report.warning_count(), 2);
    assert_eq!(
        report.to_text(),
        concat!(
            "layout validation: 4 error(s), 2 warning(s)\n",
            "- ERROR root: auto_axis threshold must be finite and > 0, got 0\n",
            "- ERROR root: divider_size must be finite and >= 0, got -2\n",
            "- ERROR root/panel: Fixed size must be finite and >= 0, got -1\n",
            "- WARNING root/panel: priority should be in 0.0..=1.0, got 1.5\n",
            "- WARNING root/panel: collapsible slot should set collapse_label ",
            "for restore UI/accessibility\n",
            "- ERROR root/panel: duplicate id \"panel\" (first seen at root/panel)\n",
        )
    );
}

#[test]
fn warns_for_tier_and_container_quality_issues() {
    static TIERS: &[DisplayTier<'_>] = &[
        DisplayTier {
            name: "Mini",
            min_size: 80.0,
        },
        DisplayTier {
            name: "Mini",
            min_size: 200.0,
        },
        DisplayTier {
            name: "",
            min_size: 200.0,
        },
    ];
    let children = [LayoutNode::Slot(SlotNode {
        id: "slot",
        sizing: Sizing::fractional(0.5, 10.0),
        priority: 1.0,
        collapsible: true,
        display_tiers: TIERS,
        collapse_label: Some(" "),
    })];
    let empty_children = [];
    let root_children = [
        children[0],
        LayoutNode::Container(ContainerNode {
            id: "empty",
            axis: Axis::Vertical,
            auto_axis: None,
            sizing: Sizing::flex(0.0),
            children: &empty_children,
            divider_size: 0.0,
        }),
    ];
    let root = LayoutNode::Container(ContainerNode {
        id: "root",
        axis: Axis::Vertical,
        auto_axis: None,
        sizing: Sizing::flex(0.0),
        children: &root_children,
        divider_size: 0.0,
    });

    let report = validate_layout(&root);

    assert_eq!(report.error_count(), 0);
    assert_eq!(report.warning_count(), 6);
    assert!(
        report
            .issues()
            .iter()
            .any(|issue| issue.kind == LayoutIssueKind::EmptyCollapseLabel)
    );
    assert!(
        report
            .issues()
            .iter()
            .any(|issue| issue.kind == LayoutIssueKind::DisplayTiersNotDescending)
    );
    assert!(
        report
            .issues()
            .iter()
            .any(|issue| issue.kind == LayoutIssueKind::EmptyContainer)
    );
}

#[test]
fn validation_reports_invalid_sizing_and_tier_values() {
    struct DummyMeasure;
    impl gpui_pretext::TextMeasure for DummyMeasure {
        fn measure_width(&self, _text: &str) -> f64 {
            0.0
        }
    }
    static MEASURE: DummyMeasure = DummyMeasure;

    static BAD_TIERS: &[DisplayTier<'_>] = &[
        DisplayTier {
            name: "",
            min_size: -10.0,
        },
        DisplayTier {
            name: "Mini",
            min_size: 50.0,
        },
        DisplayTier {
            name: "Mini",
            min_size: 50.0,
        },
        DisplayTier {
            name: "Small",
            min_size: 100.0,
        },
    ];

    let empty_children: &[LayoutNode<'_>] = &[];
    let children = [
        LayoutNode::Slot(SlotNode {
            id: "",
            sizing: Sizing::Fixed(-1.0),
            priority: f32::NAN,
            collapsible: true,
            display_tiers: BAD_TIERS,
            collapse_label: None,
        }),
        LayoutNode::Slot(SlotNode {
            id: "bad-frac",
            sizing: Sizing::Fractional {
                initial: 1.5,
                min: -1.0,
                max: -2.0,
            },
            priority: 1.0,
            collapsible: false,
            display_tiers: &[],
            collapse_label: None,
        }),
        LayoutNode::Slot(SlotNode {
            id: "bad-flex",
            sizing: Sizing::Flex {
                min: f32::NEG_INFINITY,
                weight: 0.0,
            },
            priority: 1.0,
            collapsible: false,
            display_tiers: &[],
            collapse_label: None,
        }),
        LayoutNode::Slot(SlotNode {
            id: "bad-text",
            sizing: Sizing::Text {
                text: "x",
                measure: &MEASURE,
                line_height: 0.0,
                min: f32::NAN,
            },
            priority: 1.0,
            collapsible: false,
            display_tiers: &[],
            collapse_label: None,
        }),
        LayoutNode::Container(ContainerNode {
            id: "empty",
            axis: Axis::Vertical,
            auto_axis: None,
            sizing: Sizing::flex(0.0),
            children: empty_children,
            divider_size: 0.0,
        }),
    ];
    let root = LayoutNode::Container(ContainerNode {
        id: "root",
        axis: Axis::Horizontal,
        auto_axis: Some(f32::NAN),
        sizing: Sizing::flex(0.0),
        children: &children,
        divider_size: f32::NAN,
    });

    let report = validate_layout(&root);

    assert!(report.has_errors());
    let kinds: Vec<_> = report
        .issues()
        .iter()
        .map(|issue| issue.kind.clone())
        .collect();
    assert!(kinds.contains(&LayoutIssueKind::EmptyId));
    assert!(kinds.contains(&LayoutIssueKind::InvalidPriority));
    assert!(kinds.contains(&LayoutIssueKind::InvalidSizing));
    assert!(kinds.contains(&LayoutIssueKind::InvalidAutoAxis));
    assert!(kinds.contains(&LayoutIssueKind::InvalidDividerSize));
    assert!(kinds.contains(&LayoutIssueKind::InvalidDisplayTier));
    assert!(
        kinds
            .iter()
            .any(|kind| matches!(kind, LayoutIssueKind::DuplicateDisplayTierName { .. }))
    );
    assert!(
        kinds
            .iter()
            .any(|kind| matches!(kind, LayoutIssueKind::DuplicateDisplayTierThreshold { .. }))
    );
    assert!(kinds.contains(&LayoutIssueKind::DisplayTiersNotDescending));
    assert!(kinds.contains(&LayoutIssueKind::EmptyContainer));
}
