[package]
name = "gpui-toolkit-gpui-shared-string"
version = "0.1.0"
edition = "2024"
description.workspace = true
license = "Apache-2.0"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "gpui_shared_string"
path = "gpui_shared_string.rs"

[dependencies]
schemars = { version = "1.0", features = ["indexmap2"] }
serde = { version = "1.0.221", features = ["derive", "rc"] }
smol_str = "0.3.6"
