// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// Vertical slider size variants
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum VerticalSliderSize {
    /// Compact size
    Sm,
    /// Default size
    #[default]
    Md,
    /// Large size
    Lg,
}

impl VerticalSliderSize {
    pub(super) fn track_width(
        &self,
        tokens: &crate::audio_design_tokens::AudioDesignTokens,
    ) -> f32 {
        match self {
            Self::Sm => tokens.slider_track_widths[0],
            Self::Md => tokens.slider_track_widths[1],
            Self::Lg => tokens.slider_track_widths[2],
        }
    }

    pub(super) fn track_height(&self) -> f32 {
        match self {
            Self::Sm => 80.0,
            Self::Md => 120.0,
            Self::Lg => 160.0,
        }
    }

    pub(super) fn min_width(&self) -> f32 {
        match self {
            Self::Sm => 50.0,
            Self::Md => 70.0,
            Self::Lg => 90.0,
        }
    }
}

impl From<crate::ComponentSize> for VerticalSliderSize {
    fn from(size: crate::ComponentSize) -> Self {
        match size {
            crate::ComponentSize::Xs | crate::ComponentSize::Sm => Self::Sm,
            crate::ComponentSize::Md => Self::Md,
            crate::ComponentSize::Lg | crate::ComponentSize::Xl => Self::Lg,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::VerticalSliderSize;
    use crate::ComponentSize;

    #[test]
    fn default_size_is_medium() {
        assert_eq!(VerticalSliderSize::default(), VerticalSliderSize::Md);
    }

    #[test]
    fn sizes_increase_monotonically() {
        for window in [VerticalSliderSize::Sm, VerticalSliderSize::Md, VerticalSliderSize::Lg].windows(2) {
            assert!(window[0].track_width(&Default::default()) < window[1].track_width(&Default::default()));
            assert!(window[0].track_height() < window[1].track_height());
            assert!(window[0].min_width() < window[1].min_width());
        }
    }

    #[test]
    fn component_size_maps_to_slider_size() {
        assert_eq!(VerticalSliderSize::from(ComponentSize::Xs), VerticalSliderSize::Sm);
        assert_eq!(VerticalSliderSize::from(ComponentSize::Sm), VerticalSliderSize::Sm);
        assert_eq!(VerticalSliderSize::from(ComponentSize::Md), VerticalSliderSize::Md);
        assert_eq!(VerticalSliderSize::from(ComponentSize::Lg), VerticalSliderSize::Lg);
        assert_eq!(VerticalSliderSize::from(ComponentSize::Xl), VerticalSliderSize::Lg);
    }
}
