// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::menu_item::MenuItem;
use gpui::SharedString;

/// A menu bar item (top-level menu)
pub struct MenuBarItem {
    pub(super) id: SharedString,
    pub(super) label: SharedString,
    pub(super) items: Vec<MenuItem>,
}

impl MenuBarItem {
    /// Create a new menu bar item
    pub fn new(id: impl Into<SharedString>, label: impl Into<SharedString>) -> Self {
        Self {
            id: id.into(),
            label: label.into(),
            items: Vec::new(),
        }
    }

    /// Set the dropdown items
    pub fn with_items(mut self, items: Vec<MenuItem>) -> Self {
        self.items = items;
        self
    }

    /// Get the menu ID
    pub fn id(&self) -> &SharedString {
        &self.id
    }

    /// Get the menu label
    pub fn label(&self) -> &SharedString {
        &self.label
    }

    /// Get the menu items
    pub fn items(&self) -> &[MenuItem] {
        &self.items
    }
}


#[cfg(test)]
mod tests {
    use super::MenuBarItem;

    #[test]
    fn menu_bar_item_builder_and_getters() {
        let item = MenuBarItem::new("file", "File").with_items(vec![]);
        assert_eq!(item.id(), &gpui::SharedString::from("file"));
        assert_eq!(item.label(), &gpui::SharedString::from("File"));
        assert!(item.items().is_empty());
    }
}

