// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::camera::Camera3D;
use super::super::config::Surface3DConfig;
use super::super::config::SurfacePlotType;
use super::super::data::SurfaceData;
use super::super::mesh::SurfaceMesh;
use super::super::renderer::Surface3DRenderer;
use super::angle::angle_major_ticks;
use super::cartesian::cartesian_grid_lines;
use super::consts::MAX_SURFACE_RENDER_DIMENSION;
use super::misc::default_frequency_ticks;
use super::misc::project_world_to_screen;
use super::paint::paint_depth_clipped_stroke_segment;
use super::paint::paint_stroke_segment;
use super::projected_depth_buffer::ProjectedDepthBuffer;
use super::spl::spl_major_ticks;
use super::surface3_dstate::Surface3DState;
use super::types::CartesianGridLineKind;
use crate::color::D3Color;
use crate::contour::ContourGenerator;
use crate::shape::contour_smoothing::StrokePoint;
use crate::text::{GlyphTextConfig, HorizontalTextAnchor, VerticalTextAnchor, paint_chart_text_at};
use glam::Vec3;
use gpui::*;
use image::{Frame, RgbaImage};
use std::cell::RefCell;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::panic;
use std::rc::Rc;
use std::sync::Arc;

/// Cached offscreen surface render result.
#[derive(Clone)]
pub(super) struct SurfaceTextureCache {
    pub key: u64,
    pub width: u32,
    pub height: u32,
    pub render_image: Arc<RenderImage>,
}

/// Cached paint-time geometry for isolines, depth buffer, and pre-formatted tick labels.
pub(super) struct SurfaceGeometryCache {
    pub key: u64,
    pub isoline_segments: Vec<(Vec3, Vec3)>,
    pub depth_buffer: Option<ProjectedDepthBuffer>,
    pub freq_labels: Vec<String>,
    pub angle_labels: Vec<String>,
    pub spl_labels: Vec<String>,
    pub azimuth_labels: Vec<String>,
    pub elevation_labels: Vec<String>,
    pub colorbar_labels: Vec<String>,
}

/// GPUI Element for interactive 3D surface visualization
#[derive(Clone)]
pub struct Surface3DElement {
    pub(super) data: SurfaceData,
    pub(super) config: Surface3DConfig,
    pub(super) state: Rc<RefCell<Surface3DState>>,
    pub(super) renderer: Rc<RefCell<Option<Surface3DRenderer>>>,
    pub(super) mesh: Rc<RefCell<Option<SurfaceMesh>>>,
    pub(super) surface_cache: Rc<RefCell<Option<SurfaceTextureCache>>>,
    pub(super) geometry_cache: Rc<RefCell<Option<SurfaceGeometryCache>>>,
}

impl Surface3DElement {
    /// Create a new 3D surface element
    pub fn new(data: SurfaceData, config: Surface3DConfig) -> Self {
        let state = Surface3DState::new(
            config.camera_distance,
            config.camera_azimuth,
            config.camera_elevation,
        );

        Self {
            data,
            config,
            state: Rc::new(RefCell::new(state)),
            renderer: Rc::new(RefCell::new(None)),
            mesh: Rc::new(RefCell::new(None)),
            surface_cache: Rc::new(RefCell::new(None)),
            geometry_cache: Rc::new(RefCell::new(None)),
        }
    }

    /// Create with default configuration
    pub fn from_data(data: SurfaceData) -> Self {
        Self::new(data, Surface3DConfig::default())
    }

    /// Update the surface data
    pub fn set_data(&mut self, data: SurfaceData) {
        self.data = data;
        // Clear cached mesh, surface render, and paint geometry to force regeneration
        *self.mesh.borrow_mut() = None;
        *self.surface_cache.borrow_mut() = None;
        *self.geometry_cache.borrow_mut() = None;
    }

    /// Update configuration
    pub fn set_config(&mut self, config: Surface3DConfig) {
        // If plot type changes, we need to regenerate the mesh
        if self.config.plot_type != config.plot_type {
            *self.mesh.borrow_mut() = None;
        }
        // If any render-relevant setting changes, invalidate the cached surface texture.
        if surface_render_config_changed(&self.config, &config) {
            *self.surface_cache.borrow_mut() = None;
        }
        // Isoline / label settings may change independently; invalidate geometry cache.
        *self.geometry_cache.borrow_mut() = None;
        self.config = config;
        if let Some(renderer) = self.renderer.borrow_mut().as_mut() {
            renderer.set_config(self.config.clone());
        }
    }

    /// Get mutable access to state for external control
    pub fn state(&self) -> Rc<RefCell<Surface3DState>> {
        self.state.clone()
    }

    /// Set external state for the element (allows sharing state with view)
    pub fn with_state(mut self, state: Rc<RefCell<Surface3DState>>) -> Self {
        self.state = state;
        self
    }

    pub(super) fn ensure_renderer(&self) -> bool {
        let mut renderer_ref = self.renderer.borrow_mut();
        if renderer_ref.is_none() {
            *renderer_ref = Some(Surface3DRenderer::new(self.config.clone()));
        }
        true
    }

    pub(super) fn ensure_mesh(&self) {
        let mut mesh_ref = self.mesh.borrow_mut();
        if mesh_ref.is_none() {
            let mesh = SurfaceMesh::from_data(&self.data, self.config.plot_type);
            if let Some(renderer) = self.renderer.borrow_mut().as_mut() {
                renderer.set_mesh(&mesh);
            }
            *mesh_ref = Some(mesh);
        }
    }

    /// Compute a cache key for the offscreen surface render.
    ///
    /// The key covers everything that affects the rendered surface texture:
    /// render size, camera, data, and render-relevant configuration.
    pub fn compute_surface_cache_key(
        &self,
        bounds: &Bounds<Pixels>,
        scale_factor: f32,
        camera: &Camera3D,
    ) -> u64 {
        let mut hasher = DefaultHasher::new();

        // Render size
        let width: f32 = bounds.size.width.into();
        let height: f32 = bounds.size.height.into();
        width.to_bits().hash(&mut hasher);
        height.to_bits().hash(&mut hasher);
        scale_factor.to_bits().hash(&mut hasher);

        // Camera
        camera.position.x.to_bits().hash(&mut hasher);
        camera.position.y.to_bits().hash(&mut hasher);
        camera.position.z.to_bits().hash(&mut hasher);
        camera.target.x.to_bits().hash(&mut hasher);
        camera.target.y.to_bits().hash(&mut hasher);
        camera.target.z.to_bits().hash(&mut hasher);
        camera.up.x.to_bits().hash(&mut hasher);
        camera.up.y.to_bits().hash(&mut hasher);
        camera.up.z.to_bits().hash(&mut hasher);
        camera.fov.to_bits().hash(&mut hasher);
        camera.aspect.to_bits().hash(&mut hasher);
        camera.near.to_bits().hash(&mut hasher);
        camera.far.to_bits().hash(&mut hasher);

        // Data
        for x in &self.data.x_values {
            x.to_bits().hash(&mut hasher);
        }
        for y in &self.data.y_values {
            y.to_bits().hash(&mut hasher);
        }
        for row in &self.data.z_values {
            for z in row {
                z.to_bits().hash(&mut hasher);
            }
        }
        self.data.x_min.to_bits().hash(&mut hasher);
        self.data.x_max.to_bits().hash(&mut hasher);
        self.data.y_min.to_bits().hash(&mut hasher);
        self.data.y_max.to_bits().hash(&mut hasher);
        self.data.z_min.to_bits().hash(&mut hasher);
        self.data.z_max.to_bits().hash(&mut hasher);
        self.data.x_log.hash(&mut hasher);
        self.data.y_log.hash(&mut hasher);
        self.data.z_log.hash(&mut hasher);

        // Render-relevant config
        (self.config.colormap as i32).hash(&mut hasher);
        self.config.wireframe.hash(&mut hasher);
        self.config.wireframe_color[0].to_bits().hash(&mut hasher);
        self.config.wireframe_color[1].to_bits().hash(&mut hasher);
        self.config.wireframe_color[2].to_bits().hash(&mut hasher);
        self.config.ambient.to_bits().hash(&mut hasher);
        self.config.diffuse.to_bits().hash(&mut hasher);
        self.config.light_direction.x.to_bits().hash(&mut hasher);
        self.config.light_direction.y.to_bits().hash(&mut hasher);
        self.config.light_direction.z.to_bits().hash(&mut hasher);
        self.config.msaa_samples.hash(&mut hasher);
        self.config.opacity.to_bits().hash(&mut hasher);
        (self.config.plot_type as i32).hash(&mut hasher);

        hasher.finish()
    }

    /// Compute a cache key for paint-time geometry (isolines, depth buffer, tick labels).
    ///
    /// Covers the surface render key plus isoline configuration and label data so that
    /// changes to line appearance or data ranges invalidate the cache without recomputing
    /// the offscreen surface texture.
    pub fn compute_geometry_cache_key(
        &self,
        bounds: &Bounds<Pixels>,
        scale_factor: f32,
        camera: &Camera3D,
    ) -> u64 {
        let mut hasher = DefaultHasher::new();
        self.compute_surface_cache_key(bounds, scale_factor, camera)
            .hash(&mut hasher);

        // Isoline configuration
        self.config.isoline_step.to_bits().hash(&mut hasher);
        self.config.isoline_opacity.to_bits().hash(&mut hasher);
        self.config.isoline_width_px.to_bits().hash(&mut hasher);
        self.config.isoline_color[0].to_bits().hash(&mut hasher);
        self.config.isoline_color[1].to_bits().hash(&mut hasher);
        self.config.isoline_color[2].to_bits().hash(&mut hasher);
        self.config.isoline_upsample_factor.hash(&mut hasher);
        self.config.show_grid.hash(&mut hasher);
        self.config.show_axes.hash(&mut hasher);
        self.config.show_colorbar.hash(&mut hasher);

        // Tick label data
        if let Some(ticks) = &self.data.x_ticks {
            for v in ticks {
                v.to_bits().hash(&mut hasher);
            }
        }
        if let Some(ticks) = &self.data.y_ticks {
            for v in ticks {
                v.to_bits().hash(&mut hasher);
            }
        }
        if let Some(ticks) = &self.data.z_ticks {
            for v in ticks {
                v.to_bits().hash(&mut hasher);
            }
        }
        self.data.z_min.to_bits().hash(&mut hasher);
        self.data.z_max.to_bits().hash(&mut hasher);

        hasher.finish()
    }

    /// Ensure the paint-time geometry cache is populated for the current
    /// camera, bounds, scale factor, and configuration.
    ///
    /// This moves isoline contour generation, world-to-screen projection, depth
    /// buffer construction, and tick-label formatting out of the hot `paint`
    /// path. The cache is invalidated automatically when data or relevant config
    /// changes.
    pub(super) fn ensure_geometry_cache(
        &self,
        bounds: Bounds<Pixels>,
        width: f32,
        height: f32,
        scale_factor: f32,
        camera: &Camera3D,
    ) {
        let key = self.compute_geometry_cache_key(&bounds, scale_factor, camera);
        if self
            .geometry_cache
            .borrow()
            .as_ref()
            .is_some_and(|c| c.key == key)
        {
            return;
        }

        let view_projection = camera.view_projection_matrix();

        let isoline_segments = if self.config.isolines
            && self.config.isoline_opacity > 0.0
            && self.config.isoline_width_px > 0.0
            && self.data.x_count() >= 2
            && self.data.y_count() >= 2
        {
            let levels = self.isoline_levels();
            let values = self.normalized_z_grid();
            let contour_segments = ContourGenerator::new(self.data.x_count(), self.data.y_count())
                .x_values(self.data.x_values.clone())
                .y_values(self.data.y_values.clone())
                .x_log_interpolation(self.data.x_log)
                .y_log_interpolation(self.data.y_log)
                .upsample_factor(self.config.isoline_upsample_factor)
                .contour_segments(&values, &levels);

            let mut segments = Vec::with_capacity(contour_segments.len());
            for segment in contour_segments {
                let start_world =
                    self.isoline_world_position(segment.start.x, segment.start.y, segment.value);
                let end_world =
                    self.isoline_world_position(segment.end.x, segment.end.y, segment.value);
                if let (Some(start), Some(end)) = (
                    project_world_to_screen(view_projection, start_world, width, height),
                    project_world_to_screen(view_projection, end_world, width, height),
                ) {
                    segments.push((start, end));
                }
            }
            segments
        } else {
            Vec::new()
        };

        let depth_buffer = if self.config.isolines
            && self.config.opacity > 0.0
            && self.data.x_count() >= 2
            && self.data.y_count() >= 2
        {
            self.ensure_mesh();
            let mesh_ref = self.mesh.borrow();
            mesh_ref.as_ref().and_then(|mesh| {
                ProjectedDepthBuffer::from_mesh(mesh, view_projection, width, height)
            })
        } else {
            None
        };

        let freq_labels: Vec<String> = self
            .data
            .x_ticks
            .clone()
            .unwrap_or_else(default_frequency_ticks)
            .iter()
            .map(|&freq| {
                if freq >= 1000.0 {
                    format!("{}k", freq / 1000.0)
                } else {
                    format!("{}", freq)
                }
            })
            .collect();

        let angle_labels: Vec<String> = angle_major_ticks(&self.data)
            .iter()
            .map(|&angle| format!("{}°", angle))
            .collect();

        let (spl_ticks, _) = spl_major_ticks(&self.data);
        let spl_labels: Vec<String> = spl_ticks.iter().map(|&spl| format!("{}dB", spl)).collect();

        let azimuth_labels: Vec<String> = self
            .data
            .y_ticks
            .clone()
            .unwrap_or_else(|| vec![-180.0, -90.0, 0.0, 90.0, 180.0])
            .iter()
            .map(|&az| format!("{}°", az))
            .collect();

        let elevation_labels: Vec<String> = self
            .data
            .x_ticks
            .clone()
            .unwrap_or_else(|| vec![-90.0, -45.0, 0.0, 45.0, 90.0])
            .iter()
            .map(|&el| format!("{}°", el))
            .collect();

        let (z_min, z_max) = (self.data.z_min, self.data.z_max);
        let num_ticks = 5;
        let colorbar_labels: Vec<String> = (0..=num_ticks)
            .map(|i| {
                let t = i as f64 / num_ticks as f64;
                let value = z_min + t * (z_max - z_min);
                format!("{:.0}", value)
            })
            .collect();

        *self.geometry_cache.borrow_mut() = Some(SurfaceGeometryCache {
            key,
            isoline_segments,
            depth_buffer,
            freq_labels,
            angle_labels,
            spl_labels,
            azimuth_labels,
            elevation_labels,
            colorbar_labels,
        });
    }

    pub(super) fn normalized_z_grid(&self) -> Vec<f64> {
        let x_count = self.data.x_count();
        let y_count = self.data.y_count();
        let mut values = Vec::with_capacity(x_count * y_count);
        for y in 0..y_count {
            for x in 0..x_count {
                let z = self.data.z_at(x, y).unwrap_or(self.data.z_min);
                values.push(self.data.normalize_z(z).clamp(0.0, 1.0) as f64);
            }
        }
        values
    }

    pub(super) fn isoline_levels(&self) -> Vec<f64> {
        let step = self.config.isoline_step.max(0.001) as f64;
        let mut level = step;
        let mut levels = Vec::new();
        while level < 1.0 {
            levels.push(level);
            level += step;
        }
        levels
    }

    pub(super) fn isoline_world_position(&self, x: f64, y: f64, normalized_z: f64) -> Vec3 {
        let nx = self.data.normalize_x(x);
        let ny = self.data.normalize_y(y);
        let nz = normalized_z as f32;
        match self.config.plot_type {
            SurfacePlotType::Cartesian => Vec3::new(nx, nz - 0.5, ny),
            SurfacePlotType::Spherical => {
                let phi = nx * std::f32::consts::FRAC_PI_2;
                let theta = ny * std::f32::consts::PI;
                let radius = 1.0;
                let y_pos = radius * phi.sin();
                let r_xz = radius * phi.cos();
                let x_pos = r_xz * theta.sin();
                let z_pos = r_xz * theta.cos();
                Vec3::new(x_pos, y_pos, z_pos)
            }
        }
    }

    pub(super) fn paint_projected_isolines(
        &self,
        bounds: Bounds<Pixels>,
        width: f32,
        height: f32,
        scale_factor: f32,
        camera: &Camera3D,
        window: &mut Window,
    ) {
        if !self.config.isolines
            || self.config.isoline_opacity <= 0.0
            || self.config.isoline_width_px <= 0.0
            || self.data.x_count() < 2
            || self.data.y_count() < 2
        {
            return;
        }

        self.ensure_geometry_cache(bounds, width, height, scale_factor, camera);
        let cache = self.geometry_cache.borrow();
        let cache = cache.as_ref().expect("geometry cache just ensured");

        let mut stroke_color = D3Color {
            r: self.config.isoline_color[0].clamp(0.0, 1.0),
            g: self.config.isoline_color[1].clamp(0.0, 1.0),
            b: self.config.isoline_color[2].clamp(0.0, 1.0),
            a: 1.0,
        }
        .to_rgba();
        stroke_color.a *= self.config.isoline_opacity.clamp(0.0, 1.0);

        for &(start, end) in &cache.isoline_segments {
            if let Some(depth_buffer) = cache.depth_buffer.as_ref() {
                paint_depth_clipped_stroke_segment(
                    start,
                    end,
                    depth_buffer,
                    bounds,
                    self.config.isoline_width_px,
                    stroke_color,
                    window,
                );
            } else {
                paint_stroke_segment(
                    &[
                        StrokePoint::new(start.x, start.y),
                        StrokePoint::new(end.x, end.y),
                    ],
                    bounds,
                    self.config.isoline_width_px,
                    stroke_color,
                    window,
                );
            }
        }
    }

    pub(super) fn paint_projected_grid(
        &self,
        bounds: Bounds<Pixels>,
        width: f32,
        height: f32,
        camera: &Camera3D,
        overlay_color: Rgba,
        window: &mut Window,
    ) {
        if !self.config.show_grid
            || !self.config.show_axes
            || self.config.plot_type != SurfacePlotType::Cartesian
        {
            return;
        }

        for line in cartesian_grid_lines(&self.data, camera) {
            let (stroke_width, alpha) = match line.kind {
                CartesianGridLineKind::Minor => (0.75, 0.18),
                CartesianGridLineKind::Major => (1.0, 0.36),
                CartesianGridLineKind::Border => (1.25, 0.68),
            };
            let Some(start) = camera.project_to_screen(line.start, width, height) else {
                continue;
            };
            let Some(end) = camera.project_to_screen(line.end, width, height) else {
                continue;
            };

            let mut color = overlay_color;
            color.a *= alpha;
            paint_stroke_segment(
                &[
                    StrokePoint::new(start.x, start.y),
                    StrokePoint::new(end.x, end.y),
                ],
                bounds,
                stroke_width,
                color,
                window,
            );
        }
    }

    pub(super) fn paint_chart_background(&self, bounds: Bounds<Pixels>, window: &mut Window) {
        let [r, g, b] = self.config.background_color;
        window.paint_quad(PaintQuad {
            bounds,
            corner_radii: Corners::default(),
            background: Rgba {
                r: r.clamp(0.0, 1.0),
                g: g.clamp(0.0, 1.0),
                b: b.clamp(0.0, 1.0),
                a: 1.0,
            }
            .into(),
            border_widths: Edges::default(),
            border_color: transparent_black(),
            border_style: Default::default(),
        });
    }

    /// Paint the cached surface texture, rendering and caching it on a cache miss.
    pub(super) fn paint_cached_surface(
        &self,
        bounds: Bounds<Pixels>,
        width_u32: u32,
        height_u32: u32,
        scale_factor: f32,
        camera: &Camera3D,
        window: &mut Window,
    ) {
        let key = self.compute_surface_cache_key(&bounds, scale_factor, camera);

        // Reuse the cached image if the key and dimensions match.
        {
            let cache = self.surface_cache.borrow();
            if let Some(cache) = cache.as_ref()
                && cache.key == key
                && cache.width == width_u32
                && cache.height == height_u32
            {
                let _ = window.paint_image(
                    bounds,
                    Corners::default(),
                    cache.render_image.clone(),
                    0,
                    false,
                );
                return;
            }
        }

        // Render to texture and cache the result.
        self.ensure_renderer();
        self.ensure_mesh();

        if let Some(renderer) = self.renderer.borrow_mut().as_mut() {
            renderer.resize(width_u32, height_u32);

            let log_settings = if self.data.x_log {
                let min_x = self.data.x_min as f32;
                let max_x = self.data.x_max as f32;
                Some((min_x, max_x))
            } else {
                None
            };

            if let Some(pixels) = renderer.render_transparent(camera, log_settings)
                && let Some(rgba_image) = RgbaImage::from_raw(width_u32, height_u32, pixels)
            {
                let frame = Frame::new(rgba_image);
                let render_image = Arc::new(RenderImage::new(vec![frame]));
                *self.surface_cache.borrow_mut() = Some(SurfaceTextureCache {
                    key,
                    width: width_u32,
                    height: height_u32,
                    render_image: render_image.clone(),
                });
                let _ = window.paint_image(bounds, Corners::default(), render_image, 0, false);
            }
        }
    }
}

/// Returns `true` if a configuration change should invalidate the cached surface texture.
fn surface_render_config_changed(old: &Surface3DConfig, new: &Surface3DConfig) -> bool {
    old.colormap != new.colormap
        || old.wireframe != new.wireframe
        || old.wireframe_color != new.wireframe_color
        || old.ambient.to_bits() != new.ambient.to_bits()
        || old.diffuse.to_bits() != new.diffuse.to_bits()
        || old.light_direction != new.light_direction
        || old.msaa_samples != new.msaa_samples
        || old.opacity.to_bits() != new.opacity.to_bits()
        || old.plot_type != new.plot_type
}

impl IntoElement for Surface3DElement {
    type Element = Self;

    fn into_element(self) -> Self::Element {
        self
    }
}

impl Element for Surface3DElement {
    type RequestLayoutState = ();
    type PrepaintState = ();

    fn id(&self) -> Option<ElementId> {
        None
    }

    fn source_location(&self) -> Option<&'static panic::Location<'static>> {
        None
    }

    fn request_layout(
        &mut self,
        _id: Option<&GlobalElementId>,
        _inspector_id: Option<&InspectorElementId>,
        window: &mut Window,
        cx: &mut App,
    ) -> (LayoutId, Self::RequestLayoutState) {
        let style = Style {
            size: Size {
                width: relative(1.0).into(),
                height: relative(1.0).into(),
            },
            ..Default::default()
        };
        (window.request_layout(style, [], cx), ())
    }

    fn prepaint(
        &mut self,
        _id: Option<&GlobalElementId>,
        _inspector_id: Option<&InspectorElementId>,
        bounds: Bounds<Pixels>,
        _request_layout: &mut Self::RequestLayoutState,
        _window: &mut Window,
        _cx: &mut App,
    ) -> Self::PrepaintState {
        // Update camera aspect ratio
        let width: f32 = bounds.size.width.into();
        let height: f32 = bounds.size.height.into();
        if height > 0.0 {
            self.state.borrow_mut().camera.aspect = width / height;
        }
    }

    fn paint(
        &mut self,
        _id: Option<&GlobalElementId>,
        _inspector_id: Option<&InspectorElementId>,
        bounds: Bounds<Pixels>,
        _request_layout: &mut Self::RequestLayoutState,
        _prepaint: &mut Self::PrepaintState,
        window: &mut Window,
        cx: &mut App,
    ) {
        // Register mouse event handlers (must be done during paint)
        let _state = self.state.clone();
        let _bounds_for_handler = bounds;

        // Mouse event handlers are now handled by the parent view

        let width: f32 = bounds.size.width.into();
        let height: f32 = bounds.size.height.into();
        let bg = self.config.background_color;
        let luminance = 0.299 * bg[0] + 0.587 * bg[1] + 0.114 * bg[2];
        let overlay_color = if luminance > 0.5 {
            gpui::rgba(0x000000ff) // dark text on light background
        } else {
            gpui::rgba(0xffffffff) // white text on dark background
        };

        self.paint_chart_background(bounds, window);

        // Paint the Cartesian grid below the surface image. The offscreen
        // surface renderer clears to transparent, so the surface naturally
        // occludes grid strokes when composited over them.
        {
            let camera = &self.state.borrow().camera;
            self.paint_projected_grid(bounds, width, height, camera, overlay_color, window);
        }

        // Now render the surface
        let scale_factor = window.scale_factor().clamp(1.0, 3.0);
        let mut render_width = width * scale_factor;
        let mut render_height = height * scale_factor;
        let max_render_dimension = render_width.max(render_height);
        if max_render_dimension > MAX_SURFACE_RENDER_DIMENSION {
            let downscale = MAX_SURFACE_RENDER_DIMENSION / max_render_dimension;
            render_width *= downscale;
            render_height *= downscale;
        }
        let width_u32 = render_width.ceil().max(1.0) as u32;
        let height_u32 = render_height.ceil().max(1.0) as u32;

        if width_u32 > 0 && height_u32 > 0 {
            let camera = self.state.borrow().camera.clone();
            self.paint_cached_surface(bounds, width_u32, height_u32, scale_factor, &camera, window);
        }

        {
            let camera = &self.state.borrow().camera;
            self.paint_projected_isolines(bounds, width, height, scale_factor, camera, window);
        }

        // Ensure paint-time geometry (isoline segments, depth buffer, tick labels)
        // is cached before drawing axes and colorbar.
        if self.config.show_axes || self.config.show_colorbar {
            let camera = &self.state.borrow().camera;
            self.ensure_geometry_cache(bounds, width, height, scale_factor, camera);
        }

        // Draw axis labels (AFTER rendering surface to be ON TOP)
        let camera = &self.state.borrow().camera;
        let geometry_cache = self.geometry_cache.borrow();
        let cache = geometry_cache.as_ref().expect("geometry cache ensured");
        // Re-use width/height f32 from above

        let upright_rotation = |mut angle: f32| -> f32 {
            while angle > std::f32::consts::FRAC_PI_2 {
                angle -= std::f32::consts::PI;
            }
            while angle < -std::f32::consts::FRAC_PI_2 {
                angle += std::f32::consts::PI;
            }
            angle
        };

        let billboard_rotation = |pos: glam::Vec3| -> f32 {
            let (right, _) = camera.billboard_axes();
            if let (Some(a), Some(b)) = (
                camera.project_to_screen(pos, width, height),
                camera.project_to_screen(pos + right * 0.08, width, height),
            ) {
                upright_rotation((b.y - a.y).atan2(b.x - a.x))
            } else {
                0.0
            }
        };

        // Helper to draw text at 3D position
        let draw_label = |window: &mut Window,
                          text: String,
                          pos: glam::Vec3,
                          horizontal_anchor: HorizontalTextAnchor,
                          vertical_anchor: VerticalTextAnchor| {
            if let Some(screen_pos) = camera.project_to_screen(pos, width, height) {
                // Check if point is within reasonable bounds (not clipped)
                if screen_pos.z >= 0.0 && screen_pos.z <= 1.0 {
                    let font_size = 10.0;
                    let text_config =
                        GlyphTextConfig::rotated(font_size, overlay_color, billboard_rotation(pos));
                    paint_chart_text_at(
                        window,
                        cx,
                        &text,
                        screen_pos.x + f32::from(bounds.origin.x),
                        screen_pos.y + f32::from(bounds.origin.y),
                        &text_config,
                        horizontal_anchor,
                        vertical_anchor,
                    );
                }
            }
        };

        // Helper to draw tick lines
        // (Functionality moved inline for dynamic axes)

        // Only render grid and labels if in Cartesian mode
        if self.config.plot_type == SurfacePlotType::Cartesian {
            // Helper to get screen position of a 3D point
            let to_screen = |pos: glam::Vec3| -> Option<glam::Vec3> {
                let p = camera.project_to_screen(pos, width, height)?;
                if p.z >= 0.0 && p.z <= 1.0 {
                    Some(p)
                } else {
                    None
                }
            };

            // Shared helper to draw a single tick and its label
            let draw_tick_and_label =
                |window: &mut Window, pos: glam::Vec3, tick_vec: glam::Vec3, label: &str| {
                    // Draw tick
                    let tick_end = pos + tick_vec;
                    if let (Some(s_start), Some(s_end)) = (to_screen(pos), to_screen(tick_end)) {
                        let p1 = gpui::Point {
                            x: px(s_start.x) + bounds.origin.x,
                            y: px(s_start.y) + bounds.origin.y,
                        };
                        let p2 = gpui::Point {
                            x: px(s_end.x) + bounds.origin.x,
                            y: px(s_end.y) + bounds.origin.y,
                        };
                        let mut builder = gpui::PathBuilder::stroke(px(1.0));
                        builder.move_to(p1);
                        builder.line_to(p2);
                        if let Ok(path) = builder.build() {
                            window.paint_path(path, overlay_color);
                        }
                    }

                    // Draw label with offset to avoid overlapping tick line
                    // Position label past the tick end, then offset perpendicular in screen space
                    let label_pos_3d = pos + tick_vec * 1.5;
                    if let (Some(tick_start_screen), Some(tick_end_screen), Some(label_screen)) =
                        (to_screen(pos), to_screen(tick_end), to_screen(label_pos_3d))
                    {
                        let font_size = 8.0;

                        // Compute tick direction in screen space
                        let tick_dx = tick_end_screen.x - tick_start_screen.x;
                        let tick_dy = tick_end_screen.y - tick_start_screen.y;
                        let tick_len = (tick_dx * tick_dx + tick_dy * tick_dy).sqrt();

                        // Compute perpendicular offset in screen space
                        // This ensures label doesn't overlap tick even when viewed along tick axis
                        let (offset_x, offset_y) = if tick_len > 0.1 {
                            // Perpendicular to tick direction, biased downward (positive y in screen)
                            let perp_x = -tick_dy / tick_len;
                            let perp_y = tick_dx / tick_len;
                            // Choose direction that moves label down/right (more readable)
                            let offset_amount = font_size * 0.8;
                            if perp_y >= 0.0 {
                                (perp_x * offset_amount, perp_y * offset_amount)
                            } else {
                                (-perp_x * offset_amount, -perp_y * offset_amount)
                            }
                        } else {
                            // Tick is very short in screen space, just offset down
                            (0.0, font_size * 0.8)
                        };

                        let text_config = GlyphTextConfig::rotated(
                            font_size,
                            overlay_color,
                            billboard_rotation(label_pos_3d),
                        );
                        paint_chart_text_at(
                            window,
                            cx,
                            label,
                            label_screen.x + f32::from(bounds.origin.x) + offset_x,
                            label_screen.y + f32::from(bounds.origin.y) + offset_y,
                            &text_config,
                            HorizontalTextAnchor::Middle,
                            VerticalTextAnchor::Middle,
                        );
                    }
                };

            // Dynamic X Axis (Freq)
            // candidates: (y=-0.5, z=1) "Front", (y=-0.5, z=-1) "Back"
            let x_candidates = [
                (glam::Vec3::new(0.0, -0.5, 1.0), 1.0),   // Front edge center
                (glam::Vec3::new(0.0, -0.5, -1.0), -1.0), // Back edge center
            ];

            let mut best_x_z_val = x_candidates[0].1;
            let mut max_screen_y = -f32::INFINITY;

            for (pos, z_val) in x_candidates {
                if let Some(screen_pos) = to_screen(pos)
                    && screen_pos.y > max_screen_y
                {
                    max_screen_y = screen_pos.y;
                    best_x_z_val = z_val;
                }
            }

            // Freq Labels (X axis)
            let freq_ticks = self
                .data
                .x_ticks
                .clone()
                .unwrap_or_else(default_frequency_ticks);
            for (i, &freq) in freq_ticks.iter().enumerate() {
                let x = self.data.normalize_x(freq);
                let pos = glam::Vec3::new(x, -0.5, best_x_z_val);
                let tick_dir_z = if best_x_z_val > 0.0 { 1.0 } else { -1.0 };
                let tick_vec = glam::Vec3::new(0.0, 0.0, 0.1 * tick_dir_z);

                let label = cache.freq_labels.get(i).map(|s| s.as_str()).unwrap_or("");
                draw_tick_and_label(window, pos, tick_vec, label);
            }

            // X Axis Title
            draw_label(
                window,
                self.data
                    .x_label
                    .clone()
                    .unwrap_or("Freq. (Hz)".to_string()),
                glam::Vec3::new(
                    0.0,
                    -0.5,
                    best_x_z_val + 0.4 * (if best_x_z_val > 0.0 { 1.0 } else { -1.0 }),
                ),
                HorizontalTextAnchor::Middle,
                VerticalTextAnchor::Middle,
            );

            // Dynamic Z Axis (Angle)
            let z_candidates = [
                (glam::Vec3::new(1.0, -0.5, 0.0), 1.0),   // Right edge center
                (glam::Vec3::new(-1.0, -0.5, 0.0), -1.0), // Left edge center
            ];

            let mut best_z_x_val = z_candidates[0].1;
            max_screen_y = -f32::INFINITY;

            for (pos, x_val) in z_candidates {
                if let Some(screen_pos) = to_screen(pos)
                    && screen_pos.y > max_screen_y
                {
                    max_screen_y = screen_pos.y;
                    best_z_x_val = x_val;
                }
            }

            // Angle Labels (Z axis) - 30° major ticks
            let angle_ticks = angle_major_ticks(&self.data);

            for (i, &angle) in angle_ticks.iter().enumerate() {
                let z = self.data.normalize_y(angle);
                let pos = glam::Vec3::new(best_z_x_val, -0.5, z);
                let tick_dir_x = if best_z_x_val > 0.0 { 1.0 } else { -1.0 };
                let tick_vec = glam::Vec3::new(0.1 * tick_dir_x, 0.0, 0.0);

                let label = cache.angle_labels.get(i).map(|s| s.as_str()).unwrap_or("");
                draw_tick_and_label(window, pos, tick_vec, label);
            }
            // Angle Axis Title
            draw_label(
                window,
                self.data.y_label.clone().unwrap_or("Angle".to_string()),
                glam::Vec3::new(
                    best_z_x_val + 0.3 * (if best_z_x_val > 0.0 { 1.0 } else { -1.0 }),
                    -0.5,
                    0.0,
                ),
                HorizontalTextAnchor::Middle,
                VerticalTextAnchor::Middle,
            );

            // Dynamic Y Axis (SPL)
            let y_candidates = [
                (glam::Vec3::new(1.0, 0.0, 1.0), 1.0, 1.0),
                (glam::Vec3::new(1.0, 0.0, -1.0), 1.0, -1.0),
                (glam::Vec3::new(-1.0, 0.0, 1.0), -1.0, 1.0),
                (glam::Vec3::new(-1.0, 0.0, -1.0), -1.0, -1.0),
            ];

            let mut best_y_x = y_candidates[0].1;
            let mut best_y_z = y_candidates[0].2;
            let mut min_screen_x = f32::INFINITY;

            for (pos, x_val, z_val) in y_candidates {
                if let Some(screen_pos) = to_screen(pos)
                    && screen_pos.x < min_screen_x
                {
                    min_screen_x = screen_pos.x;
                    best_y_x = x_val;
                    best_y_z = z_val;
                }
            }

            // SPL Labels (Y axis)
            // Generate dynamic ticks based on actual data range
            let (spl_ticks, _) = spl_major_ticks(&self.data);
            for (i, &spl) in spl_ticks.iter().enumerate() {
                let y = self.data.normalize_z(spl) - 0.5;
                let pos = glam::Vec3::new(best_y_x, y, best_y_z);
                let tick_vec = glam::Vec3::new(best_y_x * 0.1, 0.0, best_y_z * 0.1);

                let label = cache.spl_labels.get(i).map(|s| s.as_str()).unwrap_or("");
                draw_tick_and_label(window, pos, tick_vec, label);
            }
            // SPL Axis Title
            draw_label(
                window,
                self.data.z_label.clone().unwrap_or("SPL".to_string()),
                glam::Vec3::new(best_y_x * 1.4, 0.0, best_y_z * 1.4),
                HorizontalTextAnchor::Middle,
                VerticalTextAnchor::Middle,
            );
        } else if self.config.plot_type == SurfacePlotType::Spherical {
            // Helper to get screen position of a 3D point
            let to_screen = |pos: glam::Vec3| -> Option<glam::Vec3> {
                let p = camera.project_to_screen(pos, width, height)?;
                // In Sphere mode, we might see back of sphere?
                // Just use z-buffer check [0,1]
                if p.z >= 0.0 && p.z <= 1.0 {
                    Some(p)
                } else {
                    None
                }
            };

            // Shared helper to draw a single tick and its label
            // Re-defining for simplicity as scope is separate
            let draw_tick_and_label =
                |window: &mut Window, pos: glam::Vec3, tick_vec: glam::Vec3, label: &str| {
                    let tick_end = pos + tick_vec;
                    if let (Some(s_start), Some(s_end)) = (to_screen(pos), to_screen(tick_end)) {
                        let p1 = gpui::Point {
                            x: px(s_start.x) + bounds.origin.x,
                            y: px(s_start.y) + bounds.origin.y,
                        };
                        let p2 = gpui::Point {
                            x: px(s_end.x) + bounds.origin.x,
                            y: px(s_end.y) + bounds.origin.y,
                        };
                        let mut builder = gpui::PathBuilder::stroke(px(1.0));
                        builder.move_to(p1);
                        builder.line_to(p2);
                        if let Ok(path) = builder.build() {
                            window.paint_path(path, overlay_color);
                        }
                    }

                    // Draw label with offset to avoid overlapping tick line
                    let label_pos_3d = pos + tick_vec * 1.5;
                    if let (Some(tick_start_screen), Some(tick_end_screen), Some(label_screen)) =
                        (to_screen(pos), to_screen(tick_end), to_screen(label_pos_3d))
                    {
                        let font_size = 8.0;

                        // Compute tick direction in screen space
                        let tick_dx = tick_end_screen.x - tick_start_screen.x;
                        let tick_dy = tick_end_screen.y - tick_start_screen.y;
                        let tick_len = (tick_dx * tick_dx + tick_dy * tick_dy).sqrt();

                        // Compute perpendicular offset in screen space
                        let (offset_x, offset_y) = if tick_len > 0.1 {
                            let perp_x = -tick_dy / tick_len;
                            let perp_y = tick_dx / tick_len;
                            let offset_amount = font_size * 0.8;
                            if perp_y >= 0.0 {
                                (perp_x * offset_amount, perp_y * offset_amount)
                            } else {
                                (-perp_x * offset_amount, -perp_y * offset_amount)
                            }
                        } else {
                            (0.0, font_size * 0.8)
                        };

                        let text_config = GlyphTextConfig::rotated(
                            font_size,
                            overlay_color,
                            billboard_rotation(label_pos_3d),
                        );
                        paint_chart_text_at(
                            window,
                            cx,
                            label,
                            label_screen.x + f32::from(bounds.origin.x) + offset_x,
                            label_screen.y + f32::from(bounds.origin.y) + offset_y,
                            &text_config,
                            HorizontalTextAnchor::Middle,
                            VerticalTextAnchor::Middle,
                        );
                    }
                };

            // Draw Azimuth Labels (Equator)
            // Y data is Azimuth (-180..180).
            let az_ticks = self
                .data
                .y_ticks
                .clone()
                .unwrap_or_else(|| vec![-180.0, -90.0, 0.0, 90.0, 180.0]);

            for (i, &az) in az_ticks.iter().enumerate() {
                // Convert Azimuth to 3D pos on sphere equator (Phi=0)
                // normalize_y maps Azimuth to [-1, 1]
                // mesh.rs: theta = ny * PI => [-PI, PI]
                let ny = self.data.normalize_y(az);
                let theta = ny * std::f32::consts::PI;
                let radius = 1.0;

                // Phi = 0 => y_pos = 0, r_xz=radius
                let x = radius * theta.sin();
                let z = radius * theta.cos();
                let pos = glam::Vec3::new(x, 0.0, z);

                let tick_vec = pos.normalize() * 0.15; // Point out
                let label = cache
                    .azimuth_labels
                    .get(i)
                    .map(|s| s.as_str())
                    .unwrap_or("");
                draw_tick_and_label(window, pos, tick_vec, label);
            }

            // Draw Elevation Labels (Meridian)
            // X data is Elevation (-90..90).
            let el_ticks = self
                .data
                .x_ticks
                .clone()
                .unwrap_or_else(|| vec![-90.0, -45.0, 0.0, 45.0, 90.0]);

            // Draw on Prime Meridian (Theta=0 -> Y=0 in data, Z positive)

            for (i, &el) in el_ticks.iter().enumerate() {
                if el.abs() > 89.0 {
                    continue;
                } // Skip poles to avoid clutter

                let nx = self.data.normalize_x(el);
                let phi = nx * std::f32::consts::FRAC_PI_2;
                let radius = 1.0;

                // Theta = 0
                let y = radius * phi.sin();
                let r_xz = radius * phi.cos();
                let x = 0.0;
                let z = r_xz * 1.0; // theta=0 -> sin=0, cos=1

                let pos = glam::Vec3::new(x, y, z);
                let tick_vec = pos.normalize() * 0.1;
                let label = cache
                    .elevation_labels
                    .get(i)
                    .map(|s| s.as_str())
                    .unwrap_or("");

                draw_tick_and_label(window, pos, tick_vec, label);
            }
        }

        // Draw colorbar legend if enabled
        if self.config.show_colorbar {
            let colorbar_width: f32 = 20.0;
            let colorbar_height: f32 = height * 0.6;
            let colorbar_x = f32::from(bounds.origin.x) + width - colorbar_width - 50.0;
            let colorbar_y = f32::from(bounds.origin.y) + (height - colorbar_height) / 2.0;
            let num_segments = 50;

            // Draw colorbar segments
            for i in 0..num_segments {
                let t = i as f32 / num_segments as f32;
                let segment_height = colorbar_height / num_segments as f32;
                let y = colorbar_y + colorbar_height
                    - (t + 1.0 / num_segments as f32) * colorbar_height;

                // Get color from colormap
                let color = self.config.colormap.color_at(1.0 - t);
                let rgba = gpui::rgba(
                    ((color.0 * 255.0) as u32) << 24
                        | ((color.1 * 255.0) as u32) << 16
                        | ((color.2 * 255.0) as u32) << 8
                        | 0xFF,
                );

                window.paint_quad(gpui::PaintQuad {
                    bounds: gpui::Bounds::new(
                        gpui::point(px(colorbar_x), px(y)),
                        gpui::size(px(colorbar_width), px(segment_height + 1.0)),
                    ),
                    corner_radii: gpui::Corners::default(),
                    background: rgba.into(),
                    border_widths: gpui::Edges::default(),
                    border_color: gpui::transparent_black(),
                    border_style: Default::default(),
                });
            }

            // Draw border around colorbar
            let mut builder = gpui::PathBuilder::stroke(px(1.0));
            builder.move_to(gpui::point(px(colorbar_x), px(colorbar_y)));
            builder.line_to(gpui::point(px(colorbar_x + colorbar_width), px(colorbar_y)));
            builder.line_to(gpui::point(
                px(colorbar_x + colorbar_width),
                px(colorbar_y + colorbar_height),
            ));
            builder.line_to(gpui::point(
                px(colorbar_x),
                px(colorbar_y + colorbar_height),
            ));
            builder.line_to(gpui::point(px(colorbar_x), px(colorbar_y)));
            if let Ok(path) = builder.build() {
                window.paint_path(path, overlay_color);
            }

            // Draw tick labels for colorbar
            let num_ticks = 5;
            let font_size = 9.0;
            for i in 0..=num_ticks {
                let t = i as f64 / num_ticks as f64;
                let y = colorbar_y + colorbar_height * (1.0 - t as f32);

                // Draw tick line
                let mut builder = gpui::PathBuilder::stroke(px(1.0));
                builder.move_to(gpui::point(px(colorbar_x + colorbar_width), px(y)));
                builder.line_to(gpui::point(px(colorbar_x + colorbar_width + 4.0), px(y)));
                if let Ok(path) = builder.build() {
                    window.paint_path(path, overlay_color);
                }

                // Draw label from cache
                let label = cache
                    .colorbar_labels
                    .get(i)
                    .map(|s| s.as_str())
                    .unwrap_or("");
                let text_config = GlyphTextConfig::horizontal(font_size, overlay_color);
                paint_chart_text_at(
                    window,
                    cx,
                    label,
                    colorbar_x + colorbar_width + 6.0,
                    y,
                    &text_config,
                    HorizontalTextAnchor::Start,
                    VerticalTextAnchor::Middle,
                );
            }

            // Draw colorbar title (Z label)
            if let Some(ref z_label) = self.data.z_label {
                let label_x = colorbar_x + colorbar_width / 2.0;
                let label_y = colorbar_y - 15.0;
                let text_config = GlyphTextConfig::horizontal(10.0, overlay_color);
                paint_chart_text_at(
                    window,
                    cx,
                    z_label,
                    label_x,
                    label_y,
                    &text_config,
                    HorizontalTextAnchor::Middle,
                    VerticalTextAnchor::Middle,
                );
            }
        }
    }
}
