// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use serde::Serialize;

/// Which platform design language to follow.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
pub enum DesignLanguage {
    /// Apple Human Interface Guidelines (macOS, iOS).
    AppleHig,
    /// Material Design 3 (Android, ChromeOS, web).
    Material3,
    /// Windows Fluent Design (Windows 10/11).
    Fluent,
    /// GNOME Adwaita / GTK 4 / libadwaita.
    Adwaita,
    /// KDE Breeze / Kirigami.
    Breeze,
    /// IBM Carbon Design System.
    Carbon,
    /// Neutral default — no strong platform opinion. Matches current hardcoded values.
    Neutral,
}

impl DesignLanguage {
    pub fn all() -> &'static [Self] {
        &[
            Self::Neutral,
            Self::AppleHig,
            Self::Material3,
            Self::Fluent,
            Self::Adwaita,
            Self::Breeze,
            Self::Carbon,
        ]
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::AppleHig => "apple_hig",
            Self::Material3 => "material3",
            Self::Fluent => "fluent",
            Self::Adwaita => "adwaita",
            Self::Breeze => "breeze",
            Self::Carbon => "carbon",
            Self::Neutral => "neutral",
        }
    }

    pub fn from_id(value: &str) -> Option<Self> {
        match value {
            "apple_hig" => Some(Self::AppleHig),
            "material3" => Some(Self::Material3),
            "fluent" => Some(Self::Fluent),
            "adwaita" | "gtk" | "gnome" => Some(Self::Adwaita),
            "breeze" | "kde" => Some(Self::Breeze),
            "carbon" => Some(Self::Carbon),
            "neutral" => Some(Self::Neutral),
            _ => None,
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            Self::AppleHig => "Apple HIG",
            Self::Material3 => "Material 3",
            Self::Fluent => "Fluent",
            Self::Adwaita => "Adwaita",
            Self::Breeze => "Breeze",
            Self::Carbon => "Carbon",
            Self::Neutral => "Neutral",
        }
    }
}
