// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::design_conformance_case::DesignConformanceCase;
use super::design_system::all_design_presets;
use super::types::ConformanceFinding;
use serde::Serialize;

/// CI-facing conformance matrix across design presets and motion policies.
#[derive(Debug, Clone, Default, PartialEq, Serialize)]
pub struct DesignConformanceMatrix {
    pub cases: Vec<DesignConformanceCase>,
}

impl DesignConformanceMatrix {
    pub fn all_presets() -> Self {
        let mut cases = Vec::new();
        for (preset_id, system) in all_design_presets() {
            for reduced_motion in [false, true] {
                cases.push(DesignConformanceCase {
                    preset_id,
                    reduced_motion,
                    report: system.conformance_report(reduced_motion),
                    motion: system.motion_spec(reduced_motion),
                    token_count: system.style_dictionary_tokens_ref().len(),
                });
            }
        }
        Self { cases }
    }

    pub fn passed(&self) -> bool {
        self.cases.iter().all(DesignConformanceCase::passed)
    }

    pub fn findings(&self) -> Vec<(&DesignConformanceCase, &ConformanceFinding)> {
        let mut findings = Vec::new();
        for case in &self.cases {
            for finding in &case.report.findings {
                findings.push((case, finding));
            }
        }
        findings
    }

    pub fn to_markdown_table(&self) -> String {
        let mut output = String::from(
            "| preset | motion | tokens | status | findings |\n\
             | --- | --- | ---: | --- | --- |\n",
        );
        for case in &self.cases {
            let mut findings = String::new();
            if case.report.findings.is_empty() {
                findings.push_str("none");
            } else {
                for (i, finding) in case.report.findings.iter().enumerate() {
                    if i > 0 {
                        findings.push_str(", ");
                    }
                    findings.push_str(finding.id);
                }
            }
            output.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                case.preset_id,
                case.motion_label(),
                case.token_count,
                if case.passed() { "pass" } else { "fail" },
                findings
            ));
        }
        output
    }
}
